-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\A1SM03_DefenseReversal.domino.xml
-- User graph: ChurchAssault
-- 
-- Generated on 09/16/2008 16:49:00
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 


export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/System/PlayMusic.lua");
	cbox:RegisterBox("Domino/System/OutputOrder.lua");
	cbox:RegisterBox("Domino/System/SendPierceStim.lua");
	cbox:RegisterBox("Domino/System/GetLocalPlayer.lua");
	cbox:RegisterBox("Domino/System/TextToScreen.lua");
	cbox:RegisterBox("Domino/System/SetWeaponSafeMode.lua");
	cbox:RegisterBox("Domino/System/SimpleNode.lua");
	cbox:RegisterBox("Domino/System/ParticleSystem.lua");
	cbox:RegisterBox("Domino/System/LogToConsole.lua");
	cbox:RegisterBox("Domino/System/DefenceReversal.lua");
	cbox:RegisterBox("Domino/System/SocialRegion.lua");
	cbox:RegisterBox("Domino/System/SetMissionState.lua");
	cbox:RegisterBox("Domino/System/ReinforcementRegion.lua");
	cbox:RegisterBox("Domino/System/ManageWeapon.lua");
	cbox:RegisterBox("Domino/System/PlaySound.lua");
	cbox:RegisterBox("Domino/System/SoundMixing.lua");
	cbox:RegisterBox("Domino/System/OnceOnly.lua");
	cbox:RegisterBox("Domino/System/SetScriptedDeathMode.lua");
	cbox:RegisterBox("Domino/System/Sequence.lua");
	cbox:RegisterBox("Domino/System/PlayerHealthEvents.lua");
	cbox:RegisterBox("Domino/System/Delay.lua");
	cbox:RegisterBox("Domino/System/ProximityTrigger.lua");
	
	-- Load resources
	cbox:LoadResource("sndres0x004c664d", "CSoundResource");
	cbox:LoadResource("sndres0x004c664c", "CSoundResource");
	cbox:LoadResource("sndres0x004e1a12", "CSoundResource");
	cbox:LoadResource("sndres0x004c664b", "CSoundResource");
	cbox:LoadResource("sndres0x004c6649", "CSoundResource");
	cbox:LoadResource("sndres0x004c664a", "CSoundResource");
	cbox:LoadResource("sndres0x004c664e", "CSoundResource");
	cbox:LoadResource("sndres0x004e1d49", "CSoundResource");
	cbox:LoadResource("sndres0x00455b16", "CSoundResource");
	cbox:LoadResource("sndres0x004c6693", "CSoundResource");
	cbox:LoadResource("sndres0x004e1a2a", "CSoundResource");
end;

function export:Init(cbox)
	self.Out = DummyFunction;
	self.Player = nil;
	self[60] = cbox:CreateBox("Domino/System/ReinforcementRegion.lua");
	self[60]._graph = self;
	self[60].Out = self._type.f_60_Out;
	self[49] = cbox:CreateBox("Domino/System/Delay.lua");
	self[49]._graph = self;
	self[49].TimeElapsed = self._type.f_49_TimeElapsed;
	self[63] = cbox:CreateBox("Domino/System/Delay.lua");
	self[63]._graph = self;
	self[63].TimeElapsed = self._type.f_63_TimeElapsed;
	self[56] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[56]._graph = self;
	self[56].Started = self._type.f_56_Started;
	self[56].Finished = DummyFunction;
	self[5] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[5]._graph = self;
	self[5].Enter = self._type.f_5_Enter;
	self[5].Leave = DummyFunction;
	self[5].Use = DummyFunction;
	self[21] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[21]._graph = self;
	self[21].Enter = DummyFunction;
	self[21].Leave = self._type.f_21_Leave;
	self[21].Use = DummyFunction;
	self[55] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[55]._graph = self;
	self[55].Started = self._type.f_55_Started;
	self[55].Finished = DummyFunction;
	self[65] = cbox:CreateBox("Domino/System/ReinforcementRegion.lua");
	self[65]._graph = self;
	self[65].Out = self._type.f_65_Out;
	self[26] = cbox:CreateBox("Domino/System/OnceOnly.lua");
	self[26]._graph = self;
	self[26].Out = self._type.f_26_Out;
	self[52] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[52]._graph = self;
	self[52].Started = DummyFunction;
	self[52].Finished = DummyFunction;
	self[53] = cbox:CreateBox("Domino/System/Delay.lua");
	self[53]._graph = self;
	self[53].TimeElapsed = self._type.f_53_TimeElapsed;
	self[36] = cbox:CreateBox("Domino/System/ReinforcementRegion.lua");
	self[36]._graph = self;
	self[36].Out = self._type.f_36_Out;
	self[57] = cbox:CreateBox("Domino/System/ReinforcementRegion.lua");
	self[57]._graph = self;
	self[57].Out = self._type.f_57_Out;
	self[10] = cbox:CreateBox("Domino/System/Delay.lua");
	self[10]._graph = self;
	self[10].TimeElapsed = self._type.f_10_TimeElapsed;
	self[39] = cbox:CreateBox("Domino/System/ReinforcementRegion.lua");
	self[39]._graph = self;
	self[39].Out = self._type.f_39_Out;
	self[45] = cbox:CreateBox("Domino/System/Delay.lua");
	self[45]._graph = self;
	self[45].TimeElapsed = self._type.f_45_TimeElapsed;
	self[17] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[17]._graph = self;
	self[17].Started = DummyFunction;
	self[17].Finished = DummyFunction;
	self[59] = cbox:CreateBox("Domino/System/Delay.lua");
	self[59]._graph = self;
	self[59].TimeElapsed = self._type.f_59_TimeElapsed;
	self[24] = cbox:CreateBox("Domino/System/PlayerHealthEvents.lua");
	self[24]._graph = self;
	self[24].ScriptedDeath = self._type.f_24_ScriptedDeath;
	self[24].MalariaBlackout = DummyFunction;
	self[66] = cbox:CreateBox("Domino/System/Delay.lua");
	self[66]._graph = self;
	self[66].TimeElapsed = self._type.f_66_TimeElapsed;
	self[67] = cbox:CreateBox("Domino/System/DefenceReversal.lua");
	self[67]._graph = self;
	self[67].Out = DummyFunction;
	self[38] = cbox:CreateBox("Domino/System/Delay.lua");
	self[38]._graph = self;
	self[38].TimeElapsed = self._type.f_38_TimeElapsed;
	self[16] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[16]._graph = self;
	self[16].Started = DummyFunction;
	self[16].Finished = DummyFunction;
	self[35] = cbox:CreateBox("Domino/System/Delay.lua");
	self[35]._graph = self;
	self[35].TimeElapsed = self._type.f_35_TimeElapsed;
	self[18] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[18]._graph = self;
	self[18].Started = DummyFunction;
	self[18].Finished = DummyFunction;
	self[64] = cbox:CreateBox("Domino/System/ReinforcementRegion.lua");
	self[64]._graph = self;
	self[64].Out = self._type.f_64_Out;
	self[33] = cbox:CreateBox("Domino/System/OnceOnly.lua");
	self[33]._graph = self;
	self[33].Out = self._type.f_33_Out;
	self[62] = cbox:CreateBox("Domino/System/DefenceReversal.lua");
	self[62]._graph = self;
	self[62].Out = self._type.f_62_Out;
	self[51] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[51]._graph = self;
	self[51].Started = DummyFunction;
	self[51].Finished = DummyFunction;
	self[27] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[27]._graph = self;
	self[27].Started = self._type.f_27_Started;
	self[27].Finished = DummyFunction;
	self[20] = cbox:CreateBox("Domino/System/Delay.lua");
	self[20]._graph = self;
	self[20].TimeElapsed = self._type.f_20_TimeElapsed;
	self[15] = cbox:CreateBox("Domino/System/SetScriptedDeathMode.lua");
	self[15]._graph = self;
	self[15].Out = self._type.f_15_Out;
	self[43] = cbox:CreateBox("Domino/System/DefenceReversal.lua");
	self[43]._graph = self;
	self[43].Out = self._type.f_43_Out;
	self[50] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[50]._graph = self;
	self[50].Started = DummyFunction;
	self[50].Finished = DummyFunction;
	self[61] = cbox:CreateBox("Domino/System/Delay.lua");
	self[61]._graph = self;
	self[61].TimeElapsed = self._type.f_61_TimeElapsed;
	self[46] = cbox:CreateBox("Domino/System/DefenceReversal.lua");
	self[46]._graph = self;
	self[46].Out = self._type.f_46_Out;
	self[6] = cbox:CreateBox("Domino/System/PlaySound.lua");
	self[6]._graph = self;
	self[6].Started = DummyFunction;
	self[6].Finished = DummyFunction;
end;

function export:ShutDown()
	self[60]._type.ShutDown(self[60]);
	self[49]._type.ShutDown(self[49]);
	self[63]._type.ShutDown(self[63]);
	self[56]._type.ShutDown(self[56]);
	self[5]._type.ShutDown(self[5]);
	self[21]._type.ShutDown(self[21]);
	self[55]._type.ShutDown(self[55]);
	self[65]._type.ShutDown(self[65]);
	self[26]._type.ShutDown(self[26]);
	self[52]._type.ShutDown(self[52]);
	self[53]._type.ShutDown(self[53]);
	self[36]._type.ShutDown(self[36]);
	self[57]._type.ShutDown(self[57]);
	self[10]._type.ShutDown(self[10]);
	self[39]._type.ShutDown(self[39]);
	self[45]._type.ShutDown(self[45]);
	self[17]._type.ShutDown(self[17]);
	self[59]._type.ShutDown(self[59]);
	self[24]._type.ShutDown(self[24]);
	self[66]._type.ShutDown(self[66]);
	self[67]._type.ShutDown(self[67]);
	self[38]._type.ShutDown(self[38]);
	self[16]._type.ShutDown(self[16]);
	self[35]._type.ShutDown(self[35]);
	self[18]._type.ShutDown(self[18]);
	self[64]._type.ShutDown(self[64]);
	self[33]._type.ShutDown(self[33]);
	self[62]._type.ShutDown(self[62]);
	self[51]._type.ShutDown(self[51]);
	self[27]._type.ShutDown(self[27]);
	self[20]._type.ShutDown(self[20]);
	self[15]._type.ShutDown(self[15]);
	self[43]._type.ShutDown(self[43]);
	self[50]._type.ShutDown(self[50]);
	self[61]._type.ShutDown(self[61]);
	self[46]._type.ShutDown(self[46]);
	self[6]._type.ShutDown(self[6]);
end;

function export:In()
	-- Update 3.6: Set buddies status to missing to allow them to spawn during the betrayal segment
	GetBuddiesManager():SetDefenceRevesalBetrayedBuddies();

	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Church Attack Started";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
	self._type.en_5(self);
	self[5]._type.Enable(self[5]);
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/StoryMissions/A1SM03/A1SM03_ChurchAttack";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_3_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_1_Out()
	self = self._graph;
	self[15]._type.Enable(self[15]);
end;

function export:f_2_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/_DisableForMission/W1C3_RoadPatrols";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_1_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Off(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_3_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/_DisableForMission/W1C3_Town_Reinforcements";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_2_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Off(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_4_Out()
	self = self._graph;
	self._type.en_5(self);
	self[5]._type.Disable(self[5]);
end;

function export:f_5_Enter()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_4_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
	self[6].Entity = "2057230084636455746";
	self[6].SoundId = "0x004e1d49";
	self[6].SoundType = 11;
	self[6]._type.In(self[6]);
	self[10].Seconds = 2;
	self[10]._type.Start(self[10]);
end;

function export:f_8_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PlayMusic.lua")].SoundId = "0x004e1a12";
	Boxes[PathID("Domino/System/PlayMusic.lua")].SoundType = 18;
	Boxes[PathID("Domino/System/PlayMusic.lua")].FadeOutTime = nil;
	Boxes[PathID("Domino/System/PlayMusic.lua")].Object = nil;
	Boxes[PathID("Domino/System/PlayMusic.lua")]._graph = self;
	Boxes[PathID("Domino/System/PlayMusic.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/PlayMusic.lua")]._type.In(Boxes[PathID("Domino/System/PlayMusic.lua")]);
	self[16].Entity = "2057060581581564807";
	self[16].SoundId = "0x004c6649";
	self[16].SoundType = 11;
	self[16]._type.In(self[16]);
	self[17].Entity = "2057060599417842575";
	self[17].SoundId = "0x004c664b";
	self[17].SoundType = 11;
	self[17]._type.In(self[17]);
	self[18].Entity = "2057060587258555275";
	self[18].SoundId = "0x004c664a";
	self[18].SoundType = 11;
	self[18]._type.In(self[18]);
end;

function export:f_9_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_8_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_10_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/Sequence.lua")].SequenceName = "A1SM03_ChurchDoorRam";
	Boxes[PathID("Domino/System/Sequence.lua")]._graph = self;
	Boxes[PathID("Domino/System/Sequence.lua")].Out = self._type.f_9_Out;
	Boxes[PathID("Domino/System/Sequence.lua")]._type.Play(Boxes[PathID("Domino/System/Sequence.lua")]);
end;

function export:f_11_Finished()
	self = self._graph;
	self[36].GameRegion = "2057134458867331263";
	self[36].MercDensity = 1;
	self[36].MercThreshold = 1;
	self[36]._type.ChangeSpawnRate(self[36]);
end;

function export:f_12_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/ManageWeapon.lua")].WeaponCategory = nil;
	Boxes[PathID("Domino/System/ManageWeapon.lua")]._graph = self;
	Boxes[PathID("Domino/System/ManageWeapon.lua")].Finished = self._type.f_11_Finished;
	Boxes[PathID("Domino/System/ManageWeapon.lua")]._type.Draw(Boxes[PathID("Domino/System/ManageWeapon.lua")]);
end;

function export:f_13_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SocialRegion.lua")].SocialRegion = "2054107021346615318";
	Boxes[PathID("Domino/System/SocialRegion.lua")]._graph = self;
	Boxes[PathID("Domino/System/SocialRegion.lua")].Out = self._type.f_12_Out;
	Boxes[PathID("Domino/System/SocialRegion.lua")]._type.Disable(Boxes[PathID("Domino/System/SocialRegion.lua")]);
end;

function export:f_14_Out()
	self = self._graph;
	self.Player = Boxes[PathID("Domino/System/GetLocalPlayer.lua")].LocalPlayer;
	self._type.en_20(self);
	self[20]._type.Start(self[20]);
	Boxes[PathID("Domino/System/SetWeaponSafeMode.lua")].Player = self.Player;
	Boxes[PathID("Domino/System/SetWeaponSafeMode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetWeaponSafeMode.lua")].Out = self._type.f_13_Out;
	Boxes[PathID("Domino/System/SetWeaponSafeMode.lua")]._type.NormalMode(Boxes[PathID("Domino/System/SetWeaponSafeMode.lua")]);
	self[21].Trigger = "2057920661065588978";
	self[21]._type.Enable(self[21]);
	self._type.en_24(self);
	self[24]._type.Enable(self[24]);
end;

function export:f_15_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GetLocalPlayer.lua")]._graph = self;
	Boxes[PathID("Domino/System/GetLocalPlayer.lua")].Out = self._type.f_14_Out;
	Boxes[PathID("Domino/System/GetLocalPlayer.lua")]._type.In(Boxes[PathID("Domino/System/GetLocalPlayer.lua")]);
end;

function export:f_19_Out()
	self = self._graph;
	self[27].Entity = "2057230104756532042";
	self[27].SoundId = "0x00455b16";
	self[27].SoundType = 11;
	self[27]._type.In(self[27]);
end;

function export:f_20_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/ParticleSystem.lua")].ParticleSystem = "2057780716627844524";
	Boxes[PathID("Domino/System/ParticleSystem.lua")]._graph = self;
	Boxes[PathID("Domino/System/ParticleSystem.lua")].Out = self._type.f_19_Out;
	Boxes[PathID("Domino/System/ParticleSystem.lua")]._type.Start(Boxes[PathID("Domino/System/ParticleSystem.lua")]);
end;

function export:f_22_Out()
	self = self._graph;
	self._type.en_38(self);
	self[38]._type.Start(self[38]);
end;

function export:f_23_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Target = self.Player;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Origin = "2054452203495634753";
	Boxes[PathID("Domino/System/SendPierceStim.lua")].StimLevel = 1000;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._graph = self;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Out = self._type.f_22_Out;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._type.Send(Boxes[PathID("Domino/System/SendPierceStim.lua")]);
end;

function export:f_21_Leave()
	self = self._graph;
	Boxes[PathID("Domino/System/TextToScreen.lua")].Text = "\n\n\nYou can't leave the church";
	Boxes[PathID("Domino/System/TextToScreen.lua")].Duration = 3;
	Boxes[PathID("Domino/System/TextToScreen.lua")]._graph = self;
	Boxes[PathID("Domino/System/TextToScreen.lua")].Out = self._type.f_23_Out;
	Boxes[PathID("Domino/System/TextToScreen.lua")]._type.In(Boxes[PathID("Domino/System/TextToScreen.lua")]);
end;

function export:f_24_ScriptedDeath()
	self = self._graph;
	self[26]._type.In(self[26]);
end;

function export:f_25_Out()
	self = self._graph;
	self._type.en_24(self);
	self[24]._type.Disable(self[24]);
end;

function export:f_26_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_25_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
	self[33]._type.In(self[33]);
end;

function export:f_27_Started()
	self = self._graph;
	self[35].Seconds = 0.25;
	self[35]._type.Start(self[35]);
end;

function export:f_29_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Church Attack Finished";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
	self._type.en_38(self);
	self[38]._type.Stop(self[38]);
	self._type.en_45(self);
	self[45]._type.Stop(self[45]);
	self._type.en_20(self);
	self[20]._type.Stop(self[20]);
	self._type.en_49(self);
	self[49]._type.Stop(self[49]);
end;

function export:f_30_Out_0()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_29_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_32_Out()
	self = self._graph;
	self[50].Entity = "2057060599417842575";
	self[50].SoundId = "0x004c664e";
	self[50].SoundType = 11;
	self[50]._type.In(self[50]);
	self[51].Entity = "2057060587258555275";
	self[51].SoundId = "0x004c664d";
	self[51].SoundType = 11;
	self[51]._type.In(self[51]);
	self[52].Entity = "2057060581581564807";
	self[52].SoundId = "0x004c664c";
	self[52].SoundType = 11;
	self[52]._type.In(self[52]);
	Boxes[PathID("Domino/System/PlayMusic.lua")].SoundId = "0x004e1a2a";
	Boxes[PathID("Domino/System/PlayMusic.lua")].SoundType = 18;
	Boxes[PathID("Domino/System/PlayMusic.lua")].FadeOutTime = nil;
	Boxes[PathID("Domino/System/PlayMusic.lua")].Object = nil;
	Boxes[PathID("Domino/System/PlayMusic.lua")]._graph = self;
	Boxes[PathID("Domino/System/PlayMusic.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/PlayMusic.lua")]._type.In(Boxes[PathID("Domino/System/PlayMusic.lua")]);
end;

function export:f_30_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_32_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_30_Out_2()
	self = self._graph;
	self[43].AttackLevel = 3;
	self[43].IsMikesPlace = 0;
	self[43]._type.StopAttack(self[43]);
end;

function export:f_33_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 3,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_30_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_30_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[2] = self._type.f_30_Out_2;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_34_Out()
	self = self._graph;
	self._type.en_45(self);
	self[45]._type.Start(self[45]);
end;

function export:f_35_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Target = self.Player;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Origin = "2054452202912626496";
	Boxes[PathID("Domino/System/SendPierceStim.lua")].StimLevel = 50;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._graph = self;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Out = self._type.f_34_Out;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._type.Send(Boxes[PathID("Domino/System/SendPierceStim.lua")]);
end;

function export:f_36_Out()
	self = self._graph;
	self[39].GameRegion = "2057134521467318515";
	self[39].MercDensity = 1;
	self[39].MercThreshold = 1;
	self[39]._type.ChangeSpawnRate(self[39]);
end;

function export:f_38_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Target = self.Player;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Origin = "2054452203495634753";
	Boxes[PathID("Domino/System/SendPierceStim.lua")].StimLevel = 1000;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._graph = self;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._type.Send(Boxes[PathID("Domino/System/SendPierceStim.lua")]);
end;

function export:f_39_Out()
	self = self._graph;
	self[46].AttackLevel = 1;
	self[46].IsMikesPlace = 0;
	self[46]._type.StartAttack(self[46]);
end;

function export:f_40_Out()
	self = self._graph;
	self:Out();
end;

function export:f_41_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SocialRegion.lua")].SocialRegion = "2054107021346615318";
	Boxes[PathID("Domino/System/SocialRegion.lua")]._graph = self;
	Boxes[PathID("Domino/System/SocialRegion.lua")].Out = self._type.f_40_Out;
	Boxes[PathID("Domino/System/SocialRegion.lua")]._type.Enable(Boxes[PathID("Domino/System/SocialRegion.lua")]);
end;

function export:f_42_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/_DisableForMission/W1C3_RoadPatrols";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_41_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_43_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/_DisableForMission/W1C3_Town_Reinforcements";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_42_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_44_Out()
	self = self._graph;
	self[56].Entity = "2057230099429765958";
	self[56].SoundId = "0x00455b16";
	self[56].SoundType = 11;
	self[56]._type.In(self[56]);
end;

function export:f_45_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/ParticleSystem.lua")].ParticleSystem = "2057781296733642158";
	Boxes[PathID("Domino/System/ParticleSystem.lua")]._graph = self;
	Boxes[PathID("Domino/System/ParticleSystem.lua")].Out = self._type.f_44_Out;
	Boxes[PathID("Domino/System/ParticleSystem.lua")]._type.Start(Boxes[PathID("Domino/System/ParticleSystem.lua")]);
end;

function export:f_46_Out()
	self = self._graph;
	self[53].Seconds = 10;
	self[53]._type.Start(self[53]);
end;

function export:f_49_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Target = self.Player;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Origin = "2054452203495634753";
	Boxes[PathID("Domino/System/SendPierceStim.lua")].StimLevel = 1000;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._graph = self;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._type.Send(Boxes[PathID("Domino/System/SendPierceStim.lua")]);
	self[55].Entity = "2057060581581564807";
	self[55].SoundId = "0x004c6693";
	self[55].SoundType = 12;
	self[55]._type.In(self[55]);
	Boxes[PathID("Domino/System/PlayMusic.lua")].SoundId = "0x004e1a2a";
	Boxes[PathID("Domino/System/PlayMusic.lua")].SoundType = 18;
	Boxes[PathID("Domino/System/PlayMusic.lua")].FadeOutTime = nil;
	Boxes[PathID("Domino/System/PlayMusic.lua")].Object = nil;
	Boxes[PathID("Domino/System/PlayMusic.lua")]._graph = self;
	Boxes[PathID("Domino/System/PlayMusic.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/PlayMusic.lua")]._type.In(Boxes[PathID("Domino/System/PlayMusic.lua")]);
end;

function export:f_53_TimeElapsed()
	self = self._graph;
	self[57].GameRegion = "2057134458867331263";
	self[57].MercDensity = 2;
	self[57].MercThreshold = 2;
	self[57]._type.ChangeSpawnRate(self[57]);
end;

function export:f_55_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/SoundMixing.lua")].SoundMixing = "Exclusive.KnockOut";
	Boxes[PathID("Domino/System/SoundMixing.lua")]._graph = self;
	Boxes[PathID("Domino/System/SoundMixing.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/SoundMixing.lua")]._type.Start(Boxes[PathID("Domino/System/SoundMixing.lua")]);
end;

function export:f_56_Started()
	self = self._graph;
	self[59].Seconds = 0.25;
	self[59]._type.Start(self[59]);
end;

function export:f_57_Out()
	self = self._graph;
	self[60].GameRegion = "2057134521467318515";
	self[60].MercDensity = 2;
	self[60].MercThreshold = 2;
	self[60]._type.ChangeSpawnRate(self[60]);
end;

function export:f_58_Out()
	self = self._graph;
	self._type.en_49(self);
	self[49]._type.Start(self[49]);
end;

function export:f_59_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Target = self.Player;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Origin = "2054452195729880895";
	Boxes[PathID("Domino/System/SendPierceStim.lua")].StimLevel = 50;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._graph = self;
	Boxes[PathID("Domino/System/SendPierceStim.lua")].Out = self._type.f_58_Out;
	Boxes[PathID("Domino/System/SendPierceStim.lua")]._type.Send(Boxes[PathID("Domino/System/SendPierceStim.lua")]);
end;

function export:f_60_Out()
	self = self._graph;
	self[61].Seconds = 5;
	self[61]._type.Start(self[61]);
end;

function export:f_61_TimeElapsed()
	self = self._graph;
	self[62].AttackLevel = 2;
	self[62].IsMikesPlace = 0;
	self[62]._type.StartAttack(self[62]);
end;

function export:f_62_Out()
	self = self._graph;
	self[63].Seconds = 10;
	self[63]._type.Start(self[63]);
end;

function export:f_63_TimeElapsed()
	self = self._graph;
	self[64].GameRegion = "2057134458867331263";
	self[64].MercDensity = 3;
	self[64].MercThreshold = 3;
	self[64]._type.ChangeSpawnRate(self[64]);
end;

function export:f_64_Out()
	self = self._graph;
	self[65].GameRegion = "2057134521467318515";
	self[65].MercDensity = 3;
	self[65].MercThreshold = 3;
	self[65]._type.ChangeSpawnRate(self[65]);
end;

function export:f_65_Out()
	self = self._graph;
	self[66].Seconds = 10;
	self[66]._type.Start(self[66]);
end;

function export:f_66_TimeElapsed()
	self = self._graph;
	self[67].AttackLevel = 3;
	self[67].IsMikesPlace = 0;
	self[67]._type.StartAttack(self[67]);
end;

function export:en_5()
	self[5].Trigger = "2057110001125732366";
end;

function export:en_20()
	self[20].Seconds = 60;
end;

function export:en_24()
	self[24].Player = self.Player;
end;

function export:en_38()
	self[38].Seconds = 0.75;
end;

function export:en_45()
	self[45].Seconds = 1.5;
end;

function export:en_49()
	self[49].Seconds = 0.75;
end;

-- Empty out anchor definitions
function export:Out()
	
end;
_compilerVersion = 3;
