-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\A3SM15_BuddiesBetrayalFinalBattle.domino.xml
-- User graph: A3SM15_RedemptionEnding
-- 
-- Generated on 09/22/2008 18:35:22
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 


export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/System/PostFx.lua");
	cbox:RegisterBox("Domino/System/ManageWeapon.lua");
	cbox:RegisterBox("Domino/System/LoadAMBXScript.lua");
	cbox:RegisterBox("Domino/System/SetupPlayerForAnchorAnim.lua");
	cbox:RegisterBox("Domino/System/TextToScreen.lua");
	cbox:RegisterBox("Domino/System/ScriptedScenePrefab.lua");
	cbox:RegisterBox("Domino/System/OnceOnly.lua");
	cbox:RegisterBox("Domino/System/SimpleNode.lua");
	cbox:RegisterBox("Domino/System/GetLocalPlayer.lua");
	cbox:RegisterBox("Domino/System/TriggerState.lua");
	cbox:RegisterBox("Domino/System/InterruptAnim.lua");
	cbox:RegisterBox("Domino/System/AddScriptedSceneParticipant.lua");
	cbox:RegisterBox("Domino/System/Delay.lua");
	cbox:RegisterBox("Domino/System/ThreeStringLog.lua");
	cbox:RegisterBox("Domino/System/GetEntityInPrefab.lua");
	cbox:RegisterBox("Domino/System/PlayAnim.lua");
	cbox:RegisterBox("Domino/System/ProximityTrigger.lua");
	cbox:RegisterBox("Domino/System/AnimationPackage.lua");
	cbox:RegisterBox("Domino/System/SetMissionState.lua");
	
	-- Load resources
	cbox:LoadResource("sm16_se02a_player_start", "CMovementResource");
	cbox:LoadResource("sm16_se02a_player_idle", "CMovementResource");
	cbox:LoadResource("sm16_se02a_player_end", "CMovementResource");
end;

function export:Init(cbox)
	self.Out = DummyFunction;
	self.BorderGuard = nil;
	self.DynamiteCenter = nil;
	self.Player = nil;
	self[5] = cbox:CreateBox("Domino/System/GetEntityInPrefab.lua");
	self[5]._graph = self;
	self[5].Out = self._type.f_5_Out;
	self[14] = cbox:CreateBox("Domino/System/AddScriptedSceneParticipant.lua");
	self[14]._graph = self;
	self[14].Out = self._type.f_14_Out;
	self[27] = cbox:CreateBox("Domino/System/OnceOnly.lua");
	self[27]._graph = self;
	self[27].Out = self._type.f_27_Out;
	self[24] = cbox:CreateBox("Domino/System/InterruptAnim.lua");
	self[24]._graph = self;
	self[24].Interrupted = self._type.f_24_Interrupted;
	self[20] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[20]._graph = self;
	self[20].Enter = DummyFunction;
	self[20].Leave = DummyFunction;
	self[20].Use = self._type.f_20_Use;
	self[7] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[7]._graph = self;
	self[7].Enter = DummyFunction;
	self[7].Leave = DummyFunction;
	-- Skip short-circuit bomb animation for custom ending with return to free roam
	-- Update 3.6: Revert to original
	self[7].Use = self._type.f_7_Use;
	--self[7].Use = self._type.f_25_RealFinish;
	self[25] = cbox:CreateBox("Domino/System/PlayAnim.lua");
	self[25]._graph = self;
	self[25].Started = DummyFunction;
	self[25].Finished = DummyFunction;
	self[25].RealFinish = self._type.f_25_RealFinish;
	self[4] = cbox:CreateBox("Domino/System/AnimationPackage.lua");
	self[4]._graph = self;
	self[4].Out = self._type.f_4_Out;
	self[16] = cbox:CreateBox("Domino/System/PlayAnim.lua");
	self[16]._graph = self;
	self[16].Started = self._type.f_16_Started;
	self[16].Finished = self._type.f_16_Finished;
	self[16].RealFinish = DummyFunction;
	self[12] = cbox:CreateBox("Domino/System/AnimationPackage.lua");
	self[12]._graph = self;
	self[12].Out = DummyFunction;
	self[6] = cbox:CreateBox("Domino/System/ScriptedScenePrefab.lua");
	self[6]._graph = self;
	self[6].Out = self._type.f_6_Out;
	self[29] = cbox:CreateBox("Domino/System/AnimationPackage.lua");
	self[29]._graph = self;
	self[29].Out = DummyFunction;
	self[19] = cbox:CreateBox("Domino/System/PlayAnim.lua");
	self[19]._graph = self;
	self[19].Started = self._type.f_19_Started;
	self[19].Finished = DummyFunction;
	self[19].RealFinish = DummyFunction;
	self[28] = cbox:CreateBox("Domino/System/Delay.lua");
	self[28]._graph = self;
	self[28].TimeElapsed = self._type.f_28_TimeElapsed;
end;

function export:ShutDown()
	self[5]._type.ShutDown(self[5]);
	self[14]._type.ShutDown(self[14]);
	self[27]._type.ShutDown(self[27]);
	self[24]._type.ShutDown(self[24]);
	self[20]._type.ShutDown(self[20]);
	self[7]._type.ShutDown(self[7]);
	self[25]._type.ShutDown(self[25]);
	self[4]._type.ShutDown(self[4]);
	self[16]._type.ShutDown(self[16]);
	self[12]._type.ShutDown(self[12]);
	self[6]._type.ShutDown(self[6]);
	self[29]._type.ShutDown(self[29]);
	self[19]._type.ShutDown(self[19]);
	self[28]._type.ShutDown(self[28]);
end;

function export:In()
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/StoryMissions/A3SM15/A3SM15_EndingRedemption";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_2_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_0_Out()
	self = self._graph;
	self[5].PrefabEntity = "2056648033241679207";
	self[5].ObjectName = "Props.CenterScene";
	self[5]._type.In(self[5]);
end;

function export:f_1_Out()
	self = self._graph;
	self.Player = Boxes[PathID("Domino/System/GetLocalPlayer.lua")].LocalPlayer;
	self[4].Entity = "2056648033241679207";
	self[4].PackageName = "PKG_A3SM16_SE02A";
	self[4]._type.Attach(self[4]);
	Boxes[PathID("Domino/System/TextToScreen.lua")].Text = "Make your way to the explosives";
	Boxes[PathID("Domino/System/TextToScreen.lua")].Duration = 3;
	Boxes[PathID("Domino/System/TextToScreen.lua")]._graph = self;
	Boxes[PathID("Domino/System/TextToScreen.lua")].Out = self._type.f_0_Out;
	Boxes[PathID("Domino/System/TextToScreen.lua")]._type.In(Boxes[PathID("Domino/System/TextToScreen.lua")]);
end;

function export:f_2_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GetLocalPlayer.lua")]._graph = self;
	Boxes[PathID("Domino/System/GetLocalPlayer.lua")].Out = self._type.f_1_Out;
	Boxes[PathID("Domino/System/GetLocalPlayer.lua")]._type.In(Boxes[PathID("Domino/System/GetLocalPlayer.lua")]);
end;

function export:f_4_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "PKG_A3SM16_SE02A loaded";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_5_Out()
	self = self._graph;
	self.DynamiteCenter = self[5].ObjectEntity;
	self[6].ScriptedSceneEntity = "2056648033241679207";
	self[6]._type.StartScriptedScene(self[6]);
end;

function export:f_6_Out()
	self = self._graph;
	self._type.en_7(self);
	self[7]._type.Enable(self[7]);
end;

function export:f_8_Finished()
	self = self._graph;
	self[14].ScriptedSceneEntity = "2056648033241679207";
	self[14].ObjectEntity = self.Player;
	self[14]._type.Add(self[14]);
end;

function export:f_9_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/ManageWeapon.lua")].WeaponCategory = nil;
	Boxes[PathID("Domino/System/ManageWeapon.lua")]._graph = self;
	Boxes[PathID("Domino/System/ManageWeapon.lua")].Finished = self._type.f_8_Finished;
	Boxes[PathID("Domino/System/ManageWeapon.lua")]._type.Holster(Boxes[PathID("Domino/System/ManageWeapon.lua")]);
end;

function export:f_10_Out()
	self = self._graph;
	self._type.en_7(self);
	self[7]._type.Disable(self[7]);
end;

function export:f_11_Out()
	self = self._graph;
	self[12].Entity = "2057093875425625654";
	self[12].PackageName = "PKG_A3CINE";
	self[12]._type.Attach(self[12]);
end;

function export:f_7_Use()
	self = self._graph;
	Boxes[PathID("Domino/System/TriggerState.lua")].Trigger = "2053925965664358719";
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckLookAt = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckAngle = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")]._graph = self;
	Boxes[PathID("Domino/System/TriggerState.lua")].Out = self._type.f_9_Out;
	Boxes[PathID("Domino/System/TriggerState.lua")]._type.SetAsUnusable(Boxes[PathID("Domino/System/TriggerState.lua")]);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_10_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/StoryMissions/A3SM15/A3SM15_EndingCine";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_11_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_13_Out()
	self = self._graph;
	self[16].PawnAgent = self.Player;
	self[16].LoopAnim = 0;
	self[16].AnimFile = "sm16_se02a_player_start";
	self[16]._type.StartAnim(self[16]);
end;

function export:f_14_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].Player = self.Player;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].CameraControl = 0;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].Out = self._type.f_13_Out;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]._type.In(Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]);
end;

function export:f_16_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/LoadAMBXScript.lua")].Script = "dropbattery";
	Boxes[PathID("Domino/System/LoadAMBXScript.lua")].StartStop = 1;
	Boxes[PathID("Domino/System/LoadAMBXScript.lua")]._graph = self;
	Boxes[PathID("Domino/System/LoadAMBXScript.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LoadAMBXScript.lua")]._type.In(Boxes[PathID("Domino/System/LoadAMBXScript.lua")]);
end;

function export:f_17_Out()
	self = self._graph;
	self[19].PawnAgent = self.Player;
	self[19].LoopAnim = 1;
	self[19].AnimFile = "sm16_se02a_player_idle";
	self[19]._type.StartAnim(self[19]);
end;

function export:f_16_Finished()
	self = self._graph;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].Player = self.Player;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].CameraControl = 0;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].Out = self._type.f_17_Out;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]._type.In(Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]);
end;

function export:f_18_Out()
	self = self._graph;
	self._type.en_20(self);
	self[20]._type.Enable(self[20]);
end;

function export:f_19_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/TriggerState.lua")].Trigger = "2056661859871758282";
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckLookAt = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckAngle = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")]._graph = self;
	Boxes[PathID("Domino/System/TriggerState.lua")].Out = self._type.f_18_Out;
	Boxes[PathID("Domino/System/TriggerState.lua")]._type.SetAsUsable(Boxes[PathID("Domino/System/TriggerState.lua")]);
end;

function export:f_22_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/TriggerState.lua")].Trigger = "2056661859871758282";
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckLookAt = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckAngle = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")]._graph = self;
	Boxes[PathID("Domino/System/TriggerState.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/TriggerState.lua")]._type.SetAsUnusable(Boxes[PathID("Domino/System/TriggerState.lua")]);
	self._type.en_20(self);
	self[20]._type.Disable(self[20]);
end;

function export:f_20_Use()
	self = self._graph;
	self[24].PawnAgent = self.Player;
	self[24]._type.InterruptAnim(self[24]);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_22_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_23_Out()
	self = self._graph;
	self[25].PawnAgent = self.Player;
	self[25].LoopAnim = 0;
	self[25].AnimFile = "sm16_se02a_player_end";
	self[25]._type.StartAnim(self[25]);
end;

function export:f_24_Interrupted()
	self = self._graph;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].Player = self.Player;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].CameraControl = 0;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")].Out = self._type.f_23_Out;
	Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]._type.In(Boxes[PathID("Domino/System/SetupPlayerForAnchorAnim.lua")]);
end;

function export:f_26_Out()
	self = self._graph;
	self[27]._type.In(self[27]);
end;

function export:f_25_RealFinish()
	self = self._graph;
	Boxes[PathID("Domino/System/PostFx.lua")].PostFxName = "blackscreennowfxhighpriority";
	Boxes[PathID("Domino/System/PostFx.lua")]._graph = self;
	Boxes[PathID("Domino/System/PostFx.lua")].Out = self._type.f_26_Out;
	Boxes[PathID("Domino/System/PostFx.lua")]._type.Enable(Boxes[PathID("Domino/System/PostFx.lua")]);
end;

function export:f_27_Out()
	self = self._graph;
	self[28].Seconds = 1;
	self[28]._type.Start(self[28]);
	self[29].Entity = "2056648033241679207";
	self[29].PackageName = "PKG_A3SM16_SE02A";
	self[29]._type.Detach(self[29]);
end;

function export:f_28_TimeElapsed()
	self = self._graph;
	self:Out();
end;

function export:en_7()
	self[7].Trigger = "2053925965664358719";
end;

function export:en_20()
	self[20].Trigger = "2056661859871758282";
end;

-- Empty out anchor definitions
function export:Out()
	
end;
_compilerVersion = 3;
