-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\Common_BuddySideQuests.domino.xml
-- User graph: BSQ_MissionDebriefing
-- 
-- Generated on 09/10/2008 21:04:46
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 



export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/System/CompareAnims.lua");
	cbox:RegisterBox("Domino/System/SetBoolean.lua");
	cbox:RegisterBox("Domino/System/CompareBoolean.lua");
	cbox:RegisterBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_WAIT_BECKON_GREET.lua");
	cbox:RegisterBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_DIALOG_INTERACT.lua");
	cbox:RegisterBox("Domino/System/OnceOnly.lua");
	cbox:RegisterBox("Domino/System/SetString.lua");
	cbox:RegisterBox("Domino/System/TestIfNil.lua");
	cbox:RegisterBox("Domino/System/SetMissionBarkBankState.lua");
	cbox:RegisterBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_FINISHED.lua");
	cbox:RegisterBox("Domino/System/SetAnimation.lua");
	
	-- Load resources
	cbox:LoadResource("bodywhawha_baselayer_stand", "CMovementResource");
	cbox:LoadResource("", "CMovementResource");
	cbox:LoadResource("STP_DontUseAnimFile", "CMovementResource");
end;

function export:Init(cbox)
	self.Closed = DummyFunction;
	self.Loaded_and_ready = DummyFunction;
	self.Succeeded = DummyFunction;
	self.BeckonOrNone = "none";
	self.DoSTP = 0;
	self.IdleOrStp = "";
	self.IsActive = 0;
	self[13] = cbox:CreateBox("Domino/System/SetMissionBarkBankState.lua");
	self[13]._graph = self;
	self[13].Out = DummyFunction;
	self[13].Loaded = self._type.f_13_Loaded;
	self[12] = cbox:CreateBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_FINISHED.lua");
	self[12]._graph = self;
	self[12].Started = DummyFunction;
	self[12].Exit_finished = DummyFunction;
	self[12].Cancel_finished = self._type.f_12_Cancel_finished;
	self[12].Close_finished = DummyFunction;
	self[9] = cbox:CreateBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_WAIT_BECKON_GREET.lua");
	self[9]._graph = self;
	self[9].Started = self._type.f_9_Started;
	self[9].Beckon_finished = DummyFunction;
	self[9].Greet_finished = self._type.f_9_Greet_finished;
	self[9].Canceled = DummyFunction;
	self[8] = cbox:CreateBox("Domino/System/OnceOnly.lua");
	self[8]._graph = self;
	self[8].Out = self._type.f_8_Out;
	self[10] = cbox:CreateBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_DIALOG_INTERACT.lua");
	self[10]._graph = self;
	self[10].Prepared = self._type.f_10_Prepared;
	self[10].Dialog_started = DummyFunction;
	self[10].Dialog_finished = self._type.f_10_Dialog_finished;
	self[10].Canceled = DummyFunction;
	self[11] = cbox:CreateBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_DIALOG_INTERACT.lua");
	self[11]._graph = self;
	self[11].Prepared = DummyFunction;
	self[11].Dialog_started = self._type.f_11_Dialog_started;
	self[11].Dialog_finished = self._type.f_11_Dialog_finished;
	self[11].Canceled = DummyFunction;
end;

function export:ShutDown()
	self[13]._type.ShutDown(self[13]);
	self[12]._type.ShutDown(self[12]);
	self[9]._type.ShutDown(self[9]);
	self[8]._type.ShutDown(self[8]);
	self[10]._type.ShutDown(self[10]);
	self[11]._type.ShutDown(self[11]);
end;

function export:Start()
	self[8]._type.Reset(self[8]);
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = self.DoBeckon_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_5_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_5_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:Cancel()
	self._type.en_9(self);
	self[9]._type.Cancel(self[9]);
end;

function export:f_0_Out()
	self = self._graph;
	self.DoSTP = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self[13].MissionTag = self.Missiontag;
	self[13].PawnForLoadedEvent = self.BuddyPawn;
	self[13]._type.Load(self[13]);
end;

function export:f_1_Out()
	self = self._graph;
	self.IdleOrStp = Boxes[PathID("Domino/System/SetAnimation.lua")].Target;
	self._type.en_0(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_2_Equal()
	self = self._graph;
	Boxes[PathID("Domino/System/SetAnimation.lua")].AnimFile = "bodywhawha_baselayer_stand";
	Boxes[PathID("Domino/System/SetAnimation.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetAnimation.lua")].Out = self._type.f_1_Out;
	Boxes[PathID("Domino/System/SetAnimation.lua")]._type.FromAnim(Boxes[PathID("Domino/System/SetAnimation.lua")]);
end;

function export:f_3_Out()
	self = self._graph;
	self.IdleOrStp = Boxes[PathID("Domino/System/SetAnimation.lua")].Target;
	self._type.en_0(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_2_NotEqual()
	self = self._graph;
	Boxes[PathID("Domino/System/SetAnimation.lua")].AnimFile = self.StanceAnim;
	Boxes[PathID("Domino/System/SetAnimation.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetAnimation.lua")].Out = self._type.f_3_Out;
	Boxes[PathID("Domino/System/SetAnimation.lua")]._type.FromAnim(Boxes[PathID("Domino/System/SetAnimation.lua")]);
end;

function export:f_4_Out()
	self = self._graph;
	self.BeckonOrNone = Boxes[PathID("Domino/System/SetString.lua")].Target;
	self._type.en_2(self);
	Boxes[PathID("Domino/System/CompareAnims.lua")]._type.In(Boxes[PathID("Domino/System/CompareAnims.lua")]);
end;

function export:f_5_Is_nil()
	self = self._graph;
	self._type.en_4(self);
	Boxes[PathID("Domino/System/SetString.lua")]._type.FromString(Boxes[PathID("Domino/System/SetString.lua")]);
end;

function export:f_6_Out()
	self = self._graph;
	self.BeckonOrNone = Boxes[PathID("Domino/System/SetString.lua")].Target;
	self._type.en_2(self);
	Boxes[PathID("Domino/System/CompareAnims.lua")]._type.In(Boxes[PathID("Domino/System/CompareAnims.lua")]);
end;

function export:f_7_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/SetString.lua")].String = "BECKN";
	Boxes[PathID("Domino/System/SetString.lua")].Integer = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/SetString.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetString.lua")].Out = self._type.f_6_Out;
	Boxes[PathID("Domino/System/SetString.lua")]._type.FromString(Boxes[PathID("Domino/System/SetString.lua")]);
end;

function export:f_7_A_is_False()
	self = self._graph;
	self._type.en_4(self);
	Boxes[PathID("Domino/System/SetString.lua")]._type.FromString(Boxes[PathID("Domino/System/SetString.lua")]);
end;

function export:f_5_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.DoBeckon_;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_7_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_7_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_8_Out()
	self = self._graph;
	-- MODIFIED: Set flag that debriefing has started so reward will be given
	Globals.MASTER_GameGlobals.BSQ_MissionDebriefingStarted = 1;
	self:Succeeded();
end;

function export:f_9_Started()
	self = self._graph;
	self._type.en_10(self);
	self[10]._type.Prepare(self[10]);
	self:Loaded_and_ready();
end;

function export:f_9_Greet_finished()
	self = self._graph;
	self._type.en_10(self);
	self[10]._type.Start(self[10]);
end;

function export:f_9_Canceled()
	self = self._graph;
	-- Update 3.1: Prevent cancelling BSQ missions after rescuing a new buddy (currently unused - not needed)
	--if (Globals.MASTER_GameGlobals.AcceptedMissionID == "A1SM02") or (Globals.MASTER_GameGlobals.AcceptedBuddyMissionID == "x") then
		self._type.en_10(self);
		self[10]._type.Cancel(self[10]);
	--end
end;

function export:f_10_Prepared()
	self = self._graph;
	self._type.en_11(self);
	self[11]._type.Prepare(self[11]);
end;

function export:f_10_Dialog_finished()
	self = self._graph;
	self._type.en_11(self);
	self[11]._type.Start(self[11]);
end;

function export:f_10_Canceled()
	self = self._graph;
	-- Update 3.1: Prevent cancelling BSQ missions after rescuing a new buddy (currently unused - not needed)
	--if (Globals.MASTER_GameGlobals.AcceptedMissionID == "A1SM02") or (Globals.MASTER_GameGlobals.AcceptedBuddyMissionID == "x") then
		self._type.en_11(self);
		self[11]._type.Cancel(self[11]);
	--end
end;

function export:f_11_Dialog_started()
	self = self._graph;
	self[8]._type.In(self[8]);
end;

function export:f_11_Dialog_finished()
	self = self._graph;
	self._type.en_12(self);
	self[12]._type.Start(self[12]);
end;

function export:f_11_Canceled()
	self = self._graph;
	-- Update 3.1: Prevent cancelling BSQ missions after rescuing a new buddy (currently unused - not needed)
	--if (Globals.MASTER_GameGlobals.AcceptedMissionID == "A1SM02") or (Globals.MASTER_GameGlobals.AcceptedBuddyMissionID == "x") then
		self._type.en_12(self);
		self[12]._type.Cancel(self[12]);
	--end
end;

function export:f_12_Cancel_finished()
	self = self._graph;
	self:Closed();
end;

function export:f_13_Loaded()
	self = self._graph;
	self._type.en_9(self);
	self[9]._type.Start(self[9]);
end;

function export:en_0()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_0_Out;
end;

function export:en_2()
	Boxes[PathID("Domino/System/CompareAnims.lua")].Anim1 = self.StanceAnim;
	Boxes[PathID("Domino/System/CompareAnims.lua")].Anim2 = "STP_DontUseAnimFile";
	Boxes[PathID("Domino/System/CompareAnims.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareAnims.lua")].Equal = self._type.f_2_Equal;
	Boxes[PathID("Domino/System/CompareAnims.lua")].NotEqual = self._type.f_2_NotEqual;
end;

function export:en_4()
	Boxes[PathID("Domino/System/SetString.lua")].String = "none";
	Boxes[PathID("Domino/System/SetString.lua")].Integer = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/SetString.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetString.lua")].Out = self._type.f_4_Out;
end;

function export:en_9()
	self[9].BarkMissionTag = self.Missiontag;
	self[9].Pawn = self.BuddyPawn;
	self[9].WaitLoopA = self.StanceAnim;
	self[9].BecknIdleLoop_ = self.IdleOrStp;
	self[9].GreetIdleLoop = self.IdleOrStp;
	self[9].BecknBark_ = self.BeckonOrNone;
	self[9].GreetBark = "GREET";
	self[9].BecknRadius_ = 5;
	self[9].GreetRadius_ = 2;
	self[9].BTriggerFilter1_ = self.TriggerFilter1;
	self[9].BTriggerFilter2_ = self.TriggerFilter2;
	self[9].GTriggerFilter1_ = self.TriggerFilter1;
	self[9].GTriggerFilter2_ = self.TriggerFilter2;
end;

function export:en_10()
	self[10].BarkMissionTag = self.Missiontag;
	self[10].Pawn = self.BuddyPawn;
	self[10].IdleLoop = self.IdleOrStp;
	self[10].DialogBark = "DIALA";
	self[10].PreDialogExitBark_ = "EXITA";
	self[10].DialogExitBark_ = "EXITA";
	self[10].GreetRadius_ = 2;
	self[10].TriggerFilter1_ = self.TriggerFilter1;
	self[10].TriggerFilter2_ = self.TriggerFilter2;
end;

function export:en_11()
	self[11].BarkMissionTag = self.Missiontag;
	self[11].Pawn = self.BuddyPawn;
	self[11].IdleLoop = self.IdleOrStp;
	self[11].DialogBark = "DIALB";
	self[11].PreDialogExitBark_ = "EXITA";
	self[11].DialogExitBark_ = "EXITB";
	self[11].GreetRadius_ = 2;
	self[11].NeedInteract_ = 1;
	self[11].TriggerFilter1_ = self.TriggerFilter1;
	self[11].TriggerFilter2_ = self.TriggerFilter2;
end;

function export:en_12()
	self[12].BarkMissionTag = self.Missiontag;
	self[12].Pawn = self.BuddyPawn;
	self[12].IdleLoop = self.IdleOrStp;
	self[12].ExitBark_ = "EXITB";
	self[12].GreetRadius_ = 2;
	self[12].TriggerFilter1_ = self.TriggerFilter1;
	self[12].TriggerFilter2_ = self.TriggerFilter2;
	self[12].FinalStp_ = self.DoSTP;
end;

-- Empty out anchor definitions
function export:Closed()
	
end;
function export:Loaded_and_ready()
	
end;
function export:Succeeded()
	
end;
_compilerVersion = 3;
