-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\Common_MissionBriefings.domino.xml
-- User graph: SCRIPTEDPAWN_INTERACT_PLUS
-- 
-- Generated on 09/18/2008 16:57:55
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 


export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/System/TestIfNil.lua");
	cbox:RegisterBox("Domino/System/OutputOrder.lua");
	cbox:RegisterBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	cbox:RegisterBox("Domino/System/CompareBoolean.lua");
	cbox:RegisterBox("Domino/System/StatusListener.lua");
	cbox:RegisterBox("Domino/System/ProximityTrigger.lua");
	cbox:RegisterBox("Domino/System/SimpleNode.lua");
	cbox:RegisterBox("Domino/System/SetBoolean.lua");
	cbox:RegisterBox("Domino/System/CheckProximityRadius.lua");
	cbox:RegisterBox("Domino/System/PlayAnim.lua");
	cbox:RegisterBox("Domino/User/Common_MissionBriefings.DialogOverlap_GetStatus.lua");
	cbox:RegisterBox("Domino/System/EvaluateProximityRadius.lua");
	cbox:RegisterBox("Domino/System/PopUpConfirmationMessageBox.lua");
	cbox:RegisterBox("Domino/System/PawnInteraction.lua");
	cbox:RegisterBox("Domino/System/CompareStrings.lua");
	cbox:RegisterBox("Domino/System/InterruptBark.lua");
	cbox:RegisterBox("Domino/System/GetEntityName.lua");
	cbox:RegisterBox("Domino/System/SetFloat.lua");
	cbox:RegisterBox("Domino/System/TriggerState.lua");
	cbox:RegisterBox("Domino/System/ThreeStringLog.lua");
	cbox:RegisterBox("Domino/System/PlayBark.lua");
	cbox:RegisterBox("Domino/System/PawnInteractiveState.lua");
end;

function export:Init(cbox)
	self.Canceled = DummyFunction;
	self.Dialog_finished = DummyFunction;
	self.Dialog_started = DummyFunction;
	self.Prepared = DummyFunction;
	self.DidDialogOnce = 0;
	self.GreetRadius = 5;
	self.InGreetRadius = 1;
	self.PawnEntityName = "";
	self.vOnceOnly = 0;
	self.vSidequestCancel = 0;
	self.vTriggerOnly = 0;
	self.WasCanceled = 0;
	self.WasExited = 0;
	self[81] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_GetStatus.lua");
	self[81]._graph = self;
	self[81].Is_free = self._type.f_81_Is_free;
	self[81].Is_buisy = self._type.f_81_Is_buisy;
	self[51] = cbox:CreateBox("Domino/System/CheckProximityRadius.lua");
	self[51]._graph = self;
	self[51].EnterRadius = DummyFunction;
	self[51].ExitRadius = self._type.f_51_ExitRadius;
	self[64] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_GetStatus.lua");
	self[64]._graph = self;
	self[64].Is_free = self._type.f_64_Is_free;
	self[64].Is_buisy = DummyFunction;
	self[71] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[71]._graph = self;
	self[71].Out = self._type.f_71_Out;
	self[92] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[92]._graph = self;
	self[92].Out = self._type.f_92_Out;
	self[66] = cbox:CreateBox("Domino/System/EvaluateProximityRadius.lua");
	self[66]._graph = self;
	self[66].InsideRadius = self._type.f_66_InsideRadius;
	self[66].OutsideRadius = DummyFunction;
	self[87] = cbox:CreateBox("Domino/System/PlayBark.lua");
	self[87]._graph = self;
	self[87].Started = self._type.f_87_Started;
	self[87].Finished = self._type.f_87_Finished;
	self[72] = cbox:CreateBox("Domino/System/InterruptBark.lua");
	self[72]._graph = self;
	self[72].Interrupted = self._type.f_72_Interrupted;
	self[76] = cbox:CreateBox("Domino/System/PopUpConfirmationMessageBox.lua");
	self[76]._graph = self;
	self[76].Yes = self._type.f_76_Yes;
	self[76].No = DummyFunction;
	self[65] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_GetStatus.lua");
	self[65]._graph = self;
	self[65].Is_free = self._type.f_65_Is_free;
	self[65].Is_buisy = DummyFunction;
	self[85] = cbox:CreateBox("Domino/System/PlayBark.lua");
	self[85]._graph = self;
	self[85].Started = self._type.f_85_Started;
	self[85].Finished = self._type.f_85_Finished;
	self[103] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[103]._graph = self;
	self[103].Out = self._type.f_103_Out;
	self[30] = cbox:CreateBox("Domino/System/StatusListener.lua");
	self[30]._graph = self;
	self[30].Spawned = self._type.f_30_Spawned;
	self[30].Removed = DummyFunction;
	self[93] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[93]._graph = self;
	self[93].Out = self._type.f_93_Out;
	self[108] = cbox:CreateBox("Domino/System/PlayBark.lua");
	self[108]._graph = self;
	self[108].Started = self._type.f_108_Started;
	self[108].Finished = self._type.f_108_Finished;
	self[113] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[113]._graph = self;
	self[113].Out = self._type.f_113_Out;
	self[53] = cbox:CreateBox("Domino/System/CheckProximityRadius.lua");
	self[53]._graph = self;
	self[53].EnterRadius = DummyFunction;
	self[53].ExitRadius = self._type.f_53_ExitRadius;
	self[94] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[94]._graph = self;
	self[94].Out = self._type.f_94_Out;
	self[101] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[101]._graph = self;
	self[101].Out = self._type.f_101_Out;
	self[102] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[102]._graph = self;
	self[102].Out = DummyFunction;
	self[24] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[24]._graph = self;
	self[24].Out = self._type.f_24_Out;
	self[50] = cbox:CreateBox("Domino/System/CheckProximityRadius.lua");
	self[50]._graph = self;
	self[50].EnterRadius = self._type.f_50_EnterRadius;
	self[50].ExitRadius = self._type.f_50_ExitRadius;
	self[75] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[75]._graph = self;
	self[75].Out = self._type.f_75_Out;
	self[97] = cbox:CreateBox("Domino/System/PlayAnim.lua");
	self[97]._graph = self;
	self[97].Started = self._type.f_97_Started;
	self[97].Finished = DummyFunction;
	self[97].RealFinish = DummyFunction;
	self[99] = cbox:CreateBox("Domino/System/PlayAnim.lua");
	self[99]._graph = self;
	self[99].Started = self._type.f_99_Started;
	self[99].Finished = self._type.f_99_Finished;
	self[99].RealFinish = DummyFunction;
	self[48] = cbox:CreateBox("Domino/System/PawnInteraction.lua");
	self[48]._graph = self;
	self[48].PlayerInteracted = self._type.f_48_PlayerInteracted;
	self[29] = cbox:CreateBox("Domino/User/Common_MissionBriefings.DialogOverlap_SetStatus.lua");
	self[29]._graph = self;
	self[29].Out = self._type.f_29_Out;
	self[58] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[58]._graph = self;
	self[58].Enter = DummyFunction;
	self[58].Leave = DummyFunction;
	self[58].Use = self._type.f_58_Use;
	self[46] = cbox:CreateBox("Domino/System/PlayAnim.lua");
	self[46]._graph = self;
	self[46].Started = self._type.f_46_Started;
	self[46].Finished = DummyFunction;
	self[46].RealFinish = DummyFunction;
end;

function export:ShutDown()
	self[81]._type.ShutDown(self[81]);
	self[51]._type.ShutDown(self[51]);
	self[64]._type.ShutDown(self[64]);
	self[71]._type.ShutDown(self[71]);
	self[92]._type.ShutDown(self[92]);
	self[66]._type.ShutDown(self[66]);
	self[87]._type.ShutDown(self[87]);
	self[72]._type.ShutDown(self[72]);
	self[76]._type.ShutDown(self[76]);
	self[65]._type.ShutDown(self[65]);
	self[85]._type.ShutDown(self[85]);
	self[103]._type.ShutDown(self[103]);
	self[30]._type.ShutDown(self[30]);
	self[93]._type.ShutDown(self[93]);
	self[108]._type.ShutDown(self[108]);
	self[113]._type.ShutDown(self[113]);
	self[53]._type.ShutDown(self[53]);
	self[94]._type.ShutDown(self[94]);
	self[101]._type.ShutDown(self[101]);
	self[102]._type.ShutDown(self[102]);
	self[24]._type.ShutDown(self[24]);
	self[50]._type.ShutDown(self[50]);
	self[75]._type.ShutDown(self[75]);
	self[97]._type.ShutDown(self[97]);
	self[99]._type.ShutDown(self[99]);
	self[48]._type.ShutDown(self[48]);
	self[29]._type.ShutDown(self[29]);
	self[58]._type.ShutDown(self[58]);
	self[46]._type.ShutDown(self[46]);
end;

function export:Prepare()
	self[24].Pawn = self.Pawn;
	self[24]._type.Free(self[24]);
end;

function export:Start()
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = self.DialogBark;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "New dialog block started";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_3_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:Cancel()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_4_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_0_A_is_False()
	self = self._graph;
	self[46].PawnAgent = self.Pawn;
	self[46].LoopAnim = 1;
	self[46].AnimFile = self.IdleLoop;
	self[46]._type.StartAnim(self[46]);
end;

function export:f_1_Out()
	self = self._graph;
	self.WasCanceled = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_0(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_2_Out()
	self = self._graph;
	self.DidDialogOnce = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_1_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_3_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_2_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_4_Out()
	self = self._graph;
	self.WasCanceled = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self[29].Pawn = self.Pawn;
	self[29]._type.Free__if_this_pawn(self[29]);
end;

function export:f_5_Out()
	self = self._graph;
	self.PawnEntityName = Boxes[PathID("Domino/System/GetEntityName.lua")].Name;
end;

function export:f_6_Out_0()
	self = self._graph;
	self._type.en_30(self);
	self[30]._type.Enable(self[30]);
	self._type.en_5(self);
	Boxes[PathID("Domino/System/GetEntityName.lua")]._type.Short(Boxes[PathID("Domino/System/GetEntityName.lua")]);
end;

function export:f_7_Out()
	self = self._graph;
	self.InGreetRadius = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_50(self);
	self[50]._type.Enable(self[50]);
	self[66].PawnAgent = self.Pawn;
	self[66].Radius = self.GreetRadius;
	self[66].ProximityTrigger1 = self.TriggerFilter1_;
	self[66].ProximityTrigger2 = self.TriggerFilter2_;
	self[66]._type.In(self[66]);
end;

function export:f_8_Is_nil()
	self = self._graph;
	self._type.en_7(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_9_Out()
	self = self._graph;
	self.GreetRadius = Boxes[PathID("Domino/System/SetFloat.lua")].Target;
	self._type.en_7(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_8_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/SetFloat.lua")].Float = self.GreetRadius_;
	Boxes[PathID("Domino/System/SetFloat.lua")].Integer = nil;
	Boxes[PathID("Domino/System/SetFloat.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetFloat.lua")].Out = self._type.f_9_Out;
	Boxes[PathID("Domino/System/SetFloat.lua")]._type.FromFloat(Boxes[PathID("Domino/System/SetFloat.lua")]);
end;

function export:f_10_Is_nil()
	self = self._graph;
	self._type.en_8(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_11_Out()
	self = self._graph;
	self.vSidequestCancel = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_8(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_10_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = self.SidequestCancel_;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_11_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.FromBool(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_12_Is_nil()
	self = self._graph;
	self._type.en_10(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_13_Out()
	self = self._graph;
	self.vOnceOnly = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_10(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_12_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = self.OnceOnly_;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_13_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.FromBool(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_14_Is_nil()
	self = self._graph;
	self._type.en_12(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_15_Out()
	self = self._graph;
	self.vTriggerOnly = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_12(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_14_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = self.UseTriggerOnly_;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_15_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.FromBool(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_17_Is_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "ERROR, string data must be specified for DialogBark";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_18_Out()
	self = self._graph;
	self._type.en_17(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_19_Is_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "ERROR, data must be specified for IdleLoop";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_18_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_19_Is_not_nil()
	self = self._graph;
	self._type.en_17(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_20_Out()
	self = self._graph;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_21_Is_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "ERROR, data must be specified for Pawn";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_20_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_21_Is_not_nil()
	self = self._graph;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_22_Out()
	self = self._graph;
	self._type.en_21(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_23_Is_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "ERROR, data must be specified for BarkMission";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_22_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_23_Is_not_nil()
	self = self._graph;
	self._type.en_21(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_6_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = self.UseTriggerOnly_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_14_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_14_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = self.BarkMissionTag;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_23_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_23_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_6_Out_2()
	self = self._graph;
	self:Prepared();
end;

function export:f_24_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 3,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_6_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_6_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[2] = self._type.f_6_Out_2;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_26_Out()
	self = self._graph;
	self._type.en_58(self);
	self[58]._type.Disable(self[58]);
end;

function export:f_25_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/TriggerState.lua")].Trigger = self.UsableTrigger_;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckLookAt = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckAngle = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")]._graph = self;
	Boxes[PathID("Domino/System/TriggerState.lua")].Out = self._type.f_26_Out;
	Boxes[PathID("Domino/System/TriggerState.lua")]._type.SetAsUnusable(Boxes[PathID("Domino/System/TriggerState.lua")]);
end;

function export:f_27_Out_0()
	self = self._graph;
	self._type.en_25(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
	self._type.en_48(self);
	self[48]._type.Disable(self[48]);
	self._type.en_50(self);
	self[50]._type.DestroyEventListener(self[50]);
	self._type.en_51(self);
	self[51]._type.DestroyEventListener(self[51]);
	self._type.en_53(self);
	self[53]._type.DestroyEventListener(self[53]);
	self._type.en_30(self);
	self[30]._type.Disable(self[30]);
end;

function export:f_27_Out_1()
	self = self._graph;
	self:Canceled();
end;

function export:f_28_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_27_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_27_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_29_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = self.DialogBark;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "DIALOG_INTERACT block canceled";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_28_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_30_Spawned()
	self = self._graph;
	self._type.en_5(self);
	Boxes[PathID("Domino/System/GetEntityName.lua")]._type.Short(Boxes[PathID("Domino/System/GetEntityName.lua")]);
end;

function export:f_33_Out()
	self = self._graph;
	self._type.en_48(self);
	self[48]._type.Enable(self[48]);
end;

function export:f_34_Is_nil()
	self = self._graph;
	self._type.en_33(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_35_A_is_False()
	self = self._graph;
	self._type.en_33(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_36_Out()
	self = self._graph;
	self._type.en_58(self);
	self[58]._type.Enable(self[58]);
end;

function export:f_34_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.vTriggerOnly;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_35_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
	Boxes[PathID("Domino/System/TriggerState.lua")].Trigger = self.UsableTrigger_;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckLookAt = 1;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckAngle = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")]._graph = self;
	Boxes[PathID("Domino/System/TriggerState.lua")].Out = self._type.f_36_Out;
	Boxes[PathID("Domino/System/TriggerState.lua")]._type.SetAsUsable(Boxes[PathID("Domino/System/TriggerState.lua")]);
end;

function export:f_37_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = self.UsableTrigger_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_34_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_34_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_32_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "Waiting for Interaction to do Dialog";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_37_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_31_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_32_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_38_Out_0()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = DummyFunction;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_31_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_40_A_is_False()
	self = self._graph;
	self._type.en_51(self);
	self[51]._type.Enable(self[51]);
end;

function export:f_41_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_40_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_42_A_is_False()
	self = self._graph;
	self[65].Pawn = self.Pawn;
	self[65]._type.For_this_pawn(self[65]);
end;

function export:f_41_A_is_False()
	self = self._graph;
	self._type.en_42(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_39_Is_not_nil()
	self = self._graph;
	self._type.en_41(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_43_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = self.DialogExitBark_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = DummyFunction;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_39_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_44_Is_not_nil()
	self = self._graph;
	self._type.en_41(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_43_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = self.PreDialogExitBark_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = DummyFunction;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_44_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_38_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.DidDialogOnce;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_43_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_43_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_45_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_38_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_38_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_46_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "IdleLoop started";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_45_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_47_A_is_True()
	self = self._graph;
	self[64].Pawn = self.Pawn;
	self[64]._type.For_this_pawn(self[64]);
end;

function export:f_48_PlayerInteracted()
	self = self._graph;
	self._type.en_47(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_49_Out()
	self = self._graph;
	self.InGreetRadius = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
end;

function export:f_50_EnterRadius()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_50_ExitRadius()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_52_Out()
	self = self._graph;
	self._type.en_51(self);
	self[51]._type.DestroyEventListener(self[51]);
end;

function export:f_51_ExitRadius()
	self = self._graph;
	self._type.en_42(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_52_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_54_Out()
	self = self._graph;
	self._type.en_53(self);
	self[53]._type.DestroyEventListener(self[53]);
end;

function export:f_55_A_is_True()
	self = self._graph;
	self[72].PawnAgent = self.Pawn;
	self[72]._type.Interrupt(self[72]);
end;

function export:f_56_Out()
	self = self._graph;
	self._type.en_0(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_55_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_56_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_57_Out()
	self = self._graph;
	self.WasExited = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.vOnceOnly;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_55_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_55_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_53_ExitRadius()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_54_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
	self._type.en_57(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_58_Use()
	self = self._graph;
	self._type.en_47(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_59_Out_0()
	self = self._graph;
	self._type.en_48(self);
	self[48]._type.Disable(self[48]);
	self._type.en_25(self);
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
	self._type.en_51(self);
	self[51]._type.DestroyEventListener(self[51]);
end;

function export:f_60_Out()
	self = self._graph;
	self.WasExited = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self[81].Pawn = self.Pawn;
	self[81]._type.For_this_pawn(self[81]);
end;

function export:f_61_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_60_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_59_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_61_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_62_A_eq_B()
	self = self._graph;
	self._type.en_59(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_62_A_neq_B()
	self = self._graph;
	self[76].TitleLocId = "SQ_CANCEL";
	self[76].TextLocId = "SQ_CANCEL";
	self[76]._type.In(self[76]);
end;

function export:f_63_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "none";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = self._type.f_62_A_eq_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = self._type.f_62_A_eq_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_63_A_is_False()
	self = self._graph;
	self._type.en_59(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_64_Is_free()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.vSidequestCancel;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_63_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_63_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_65_Is_free()
	self = self._graph;
	self[71].Pawn = self.Pawn;
	self[71]._type.Buisy_with_this_pawn(self[71]);
end;

function export:f_66_InsideRadius()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_67_A_is_True()
	self = self._graph;
	self[85].PawnAgent = self.Pawn;
	self[85].Mission = self.BarkMissionTag;
	self[85].Block = self.DialogExitBark_;
	self[85]._type.Start(self[85]);
end;

function export:f_67_A_is_False()
	self = self._graph;
	self[87].PawnAgent = self.Pawn;
	self[87].Mission = self.BarkMissionTag;
	self[87].Block = self.PreDialogExitBark_;
	self[87]._type.Start(self[87]);
end;

function export:f_68_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.DidDialogOnce;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_67_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_67_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_69_Is_nil()
	self = self._graph;
	self._type.en_68(self);
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")]._type.Disable(Boxes[PathID("Domino/System/PawnInteractiveState.lua")]);
end;

function export:f_70_Out()
	self = self._graph;
	self._type.en_68(self);
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")]._type.Disable(Boxes[PathID("Domino/System/PawnInteractiveState.lua")]);
end;

function export:f_69_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/TriggerState.lua")].Trigger = self.UsableTrigger_;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckLookAt = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckAngle = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")]._graph = self;
	Boxes[PathID("Domino/System/TriggerState.lua")].Out = self._type.f_70_Out;
	Boxes[PathID("Domino/System/TriggerState.lua")]._type.SetAsUnusable(Boxes[PathID("Domino/System/TriggerState.lua")]);
end;

function export:f_71_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = self.UsableTrigger_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_69_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_69_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_72_Interrupted()
	self = self._graph;
	self[75].Pawn = self.Pawn;
	self[75]._type.Free__if_this_pawn(self[75]);
end;

function export:f_74_Out_0()
	self = self._graph;
	self._type.en_50(self);
	self[50]._type.DestroyEventListener(self[50]);
	self._type.en_30(self);
	self[30]._type.Disable(self[30]);
end;

function export:f_74_Out_1()
	self = self._graph;
	self:Dialog_finished();
end;

function export:f_73_A_is_False()
	self = self._graph;
	self._type.en_74(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_75_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_73_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_76_Yes()
	self = self._graph;
	self._type.en_59(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_77_A_is_False()
	self = self._graph;
	self[93].Pawn = self.Pawn;
	self[93]._type.Buisy_with_this_pawn(self[93]);
end;

function export:f_78_Is_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_77_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_79_A_is_False()
	self = self._graph;
	self[94].Pawn = self.Pawn;
	self[94]._type.Buisy_with_this_pawn(self[94]);
end;

function export:f_78_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_79_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_80_Out()
	self = self._graph;
	self.DidDialogOnce = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = self.DialogAnim_;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_78_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_78_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_81_Is_free()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_80_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_83_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = DummyFunction;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = DummyFunction;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_81_Is_buisy()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "Global pawnbrief dialog is buisy";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_83_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_85_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = "Exit bark started (DialogExit)";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = self.DialogExitBark_;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_85_Finished()
	self = self._graph;
	self._type.en_92(self);
	self[92]._type.Free__if_this_pawn(self[92]);
end;

function export:f_87_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = "Exit bark started (PreDialog)";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = self.PreDialogExitBark_;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_87_Finished()
	self = self._graph;
	self._type.en_92(self);
	self[92]._type.Free__if_this_pawn(self[92]);
end;

function export:f_89_Is_nil()
	self = self._graph;
	self._type.en_88(self);
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")]._type.Enable(Boxes[PathID("Domino/System/PawnInteractiveState.lua")]);
end;

function export:f_90_A_is_False()
	self = self._graph;
	self._type.en_88(self);
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")]._type.Enable(Boxes[PathID("Domino/System/PawnInteractiveState.lua")]);
end;

function export:f_89_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.vTriggerOnly;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_90_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
	Boxes[PathID("Domino/System/TriggerState.lua")].Trigger = self.UsableTrigger_;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckLookAt = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")].CheckAngle = nil;
	Boxes[PathID("Domino/System/TriggerState.lua")]._graph = self;
	Boxes[PathID("Domino/System/TriggerState.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/TriggerState.lua")]._type.SetAsUsable(Boxes[PathID("Domino/System/TriggerState.lua")]);
end;

function export:f_92_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = self.UsableTrigger_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_89_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_89_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_93_Out()
	self = self._graph;
	self[97].PawnAgent = self.Pawn;
	self[97].LoopAnim = 1;
	self[97].AnimFile = self.IdleLoop;
	self[97]._type.StartAnim(self[97]);
end;

function export:f_94_Out()
	self = self._graph;
	self[99].PawnAgent = self.Pawn;
	self[99].AnimFile = self.DialogAnim_;
	self[99]._type.StartAnim(self[99]);
end;

function export:f_95_A_is_True()
	self = self._graph;
	self[102].Pawn = self.Pawn;
	self[102]._type.Free__if_this_pawn(self[102]);
end;

function export:f_95_A_is_False()
	self = self._graph;
	self[103].Pawn = self.Pawn;
	self[103]._type.Buisy_with_this_pawn(self[103]);
end;

function export:f_96_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_95_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_95_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_97_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "IdleLoop started for bark";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_96_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_98_Out()
	self = self._graph;
	self:Dialog_started();
end;

function export:f_99_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = "Dialog special anim started";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_98_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_99_Finished()
	self = self._graph;
	self[101].Pawn = self.Pawn;
	self[101]._type.Free__if_this_pawn(self[101]);
end;

function export:f_100_A_is_False()
	self = self._graph;
	self._type.en_74(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_101_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_100_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_103_Out()
	self = self._graph;
	self[108].PawnAgent = self.Pawn;
	self[108].Mission = self.BarkMissionTag;
	self[108].Block = self.DialogBark;
	self[108]._type.Start(self[108]);
end;

function export:f_104_A_is_False()
	self = self._graph;
	self._type.en_53(self);
	self[53]._type.Enable(self[53]);
end;

function export:f_105_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_104_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_105_A_is_False()
	self = self._graph;
	self._type.en_57(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_106_Out_0()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.InGreetRadius;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_105_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_105_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_106_Out_1()
	self = self._graph;
	self:Dialog_started();
end;

function export:f_107_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_106_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_106_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_108_Started()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = self.PawnEntityName;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = "Dialog bark started";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = self.DialogBark;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = self._type.f_107_Out;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_108_Finished()
	self = self._graph;
	self[113].Pawn = self.Pawn;
	self[113]._type.Free__if_this_pawn(self[113]);
end;

function export:f_109_Out()
	self = self._graph;
	self._type.en_53(self);
	self[53]._type.DestroyEventListener(self[53]);
end;

function export:f_110_Out_0()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_109_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_112_A_is_False()
	self = self._graph;
	self._type.en_74(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_111_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_112_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_110_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasExited;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_111_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_113_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_110_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_110_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:en_0()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_0_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
end;

function export:en_30()
	self[30].Entity = self.Pawn;
end;

function export:en_5()
	Boxes[PathID("Domino/System/GetEntityName.lua")].Entity = self.Pawn;
	Boxes[PathID("Domino/System/GetEntityName.lua")]._graph = self;
	Boxes[PathID("Domino/System/GetEntityName.lua")].Out = self._type.f_5_Out;
end;

function export:en_50()
	self[50].PawnAgent = self.Pawn;
	self[50].Radius = self.GreetRadius;
	self[50].RadiusSlot = 0;
	self[50].ProximityTrigger1 = self.TriggerFilter1_;
	self[50].ProximityTrigger2 = self.TriggerFilter2_;
end;

function export:en_7()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_7_Out;
end;

function export:en_8()
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = self.GreetRadius_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_8_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_8_Is_not_nil;
end;

function export:en_10()
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = self.SidequestCancel_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_10_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_10_Is_not_nil;
end;

function export:en_12()
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = self.OnceOnly_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_12_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_12_Is_not_nil;
end;

function export:en_17()
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = self.DialogBark;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_17_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = DummyFunction;
end;

function export:en_19()
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = self.IdleLoop;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_19_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_19_Is_not_nil;
end;

function export:en_21()
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = self.Pawn;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_21_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_21_Is_not_nil;
end;

function export:en_58()
	self[58].Trigger = self.UsableTrigger_;
end;

function export:en_25()
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = self.UsableTrigger_;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = DummyFunction;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_25_Is_not_nil;
end;

function export:en_48()
	self[48].Pawn = self.Pawn;
	self[48].IgnoreOrientation = 0;
end;

function export:en_51()
	self[51].PawnAgent = self.Pawn;
	self[51].Radius = self.GreetRadius;
	self[51].RadiusSlot = 0;
	self[51].ProximityTrigger1 = self.TriggerFilter1_;
	self[51].ProximityTrigger2 = self.TriggerFilter2_;
end;

function export:en_53()
	self[53].PawnAgent = self.Pawn;
	self[53].Radius = self.GreetRadius;
	self[53].RadiusSlot = 0;
	self[53].ProximityTrigger1 = self.TriggerFilter1_;
	self[53].ProximityTrigger2 = self.TriggerFilter2_;
end;

function export:en_33()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_33_Out;
end;

function export:en_42()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.WasCanceled;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_42_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
end;

function export:en_41()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.InGreetRadius;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_41_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_41_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
end;

function export:en_47()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.InGreetRadius;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_47_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
end;

function export:en_49()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_49_Out;
end;

function export:en_57()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_57_Out;
end;

function export:en_59()
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_59_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_59_Out_1;
end;

function export:en_68()
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")].Pawn = self.Pawn;
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")].IgnoreOrientation = 0;
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")].Out = self._type.f_68_Out;
end;

function export:en_74()
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_74_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_74_Out_1;
end;

function export:en_92()
	self[92].Pawn = self.Pawn;
end;

function export:en_88()
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")].Pawn = self.Pawn;
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")].IgnoreOrientation = 0;
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PawnInteractiveState.lua")].Out = DummyFunction;
end;

-- Empty out anchor definitions
function export:Canceled()
	
end;
function export:Dialog_finished()
	
end;
function export:Dialog_started()
	
end;
function export:Prepared()
	
end;
_compilerVersion = 3;
