-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\Common_BuddySideQuests.domino.xml
-- User graph: BSQ_Activate_and_Cancel
-- 
-- Generated on 09/10/2008 21:04:46
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 


export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/System/SetBoolean.lua");
	cbox:RegisterBox("Domino/System/CompareBoolean.lua");
	cbox:RegisterBox("Domino/System/LogToConsole.lua");
	cbox:RegisterBox("Domino/User/Common_CustomBoxes.MissionAcceptedListener.lua");
	cbox:RegisterBox("Domino/System/OutputOrder.lua");
	cbox:RegisterBox("Domino/User/Common_CustomBoxes.MissionCompleteListener.lua");
	cbox:RegisterBox("Domino/System/SimpleNode.lua");
end;

function export:Init(cbox)
	self.New_mission_accepted = DummyFunction;
	self.Ready = DummyFunction;
	self.Restart_briefigns = DummyFunction;
	self.vMissionActive = 0;
	self[8] = cbox:CreateBox("Domino/User/Common_CustomBoxes.MissionAcceptedListener.lua");
	self[8]._graph = self;
	self[8].StoryMission_Accepted = self._type.f_8_StoryMission_Accepted;
	self[8].LibraryMission_Accepted = DummyFunction;
	self[8].SideMissionAccepted = DummyFunction;
	self[11] = cbox:CreateBox("Domino/User/Common_CustomBoxes.MissionCompleteListener.lua");
	self[11]._graph = self;
	self[11].StoryMission_Completed = DummyFunction;
	self[11].LibraryMission_Completed = DummyFunction;
	self[11].SideMission_Completed = DummyFunction;
	self[11].BuddyUnlock_Completed = DummyFunction;
end;

function export:ShutDown()
	self[8]._type.ShutDown(self[8]);
	self[11]._type.ShutDown(self[11]);
end;

function export:Listen_for_accept()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.vMissionActive;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_0_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:Stop_listening()
	self._type.en_4(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_1_Out()
	self = self._graph;
	self.vMissionActive = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self:Ready();
	self[8]._type.Listen(self[8]);
	self[11]._type.Listen(self[11]);
end;

function export:f_0_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_1_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_2_Out()
	self = self._graph;
	self[11]._type.StopListening(self[11]);
	-- Don't cancel the mission accepted listener, we need it for when the final story mission of world1 is accepted (killing UFLL or APR leader), all BSQ missions must be cancelled before heading into world2
	--self[8]._type.StopListening(self[8]);
end;

function export:f_3_Out()
	self = self._graph;
	self.vMissionActive = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_2(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_4_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_3_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_5_Out_0()
	self = self._graph;
	self._type.en_2(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_5_Out_1()
	self = self._graph;
	self:New_mission_accepted();
end;

function export:f_6_Out()
	self = self._graph;
	self.vMissionActive = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_5_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_5_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_7_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_6_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_8_StoryMission_Accepted()
	self = self._graph;
	if (Globals.MASTER_GameGlobals.AcceptedMissionID == "A1SM02") then
		self._type.en_7(self);
		Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
	end
end;

function export:f_8_LibraryMission_Accepted()
	self = self._graph;
	self._type.en_7(self);
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_9_Out_0()
	self = self._graph;
	self._type.en_7(self);
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_10_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.W0_MikesPlace_BSQbriefings = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self:Restart_briefigns();
end;

function export:f_9_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_10_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_8_SideMissionAccepted()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_9_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_9_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_11_SideMission_Completed()
	self = self._graph;
	self._type.en_4(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:en_2()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_2_Out;
end;

function export:en_4()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.vMissionActive;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_4_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
end;

function export:en_7()
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "BSQ mission active while new mission accepted";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_7_Out;
end;

-- Empty out anchor definitions
function export:New_mission_accepted()
	
end;
function export:Ready()
	
end;
function export:Restart_briefigns()
	
end;
_compilerVersion = 3;
