-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\SavePoints\SavePoints.domino.xml
-- User graph: SavePoints
-- 
-- Generated on 09/18/2008 12:22:25
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 


export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/System/SetString.lua");
	cbox:RegisterBox("Domino/System/BroadcastMessage.lua");
	cbox:RegisterBox("Domino/System/CompareBoolean.lua");
	cbox:RegisterBox("Domino/System/ObjectivePopUp.lua");
	cbox:RegisterBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_INTERACT_PLUS.lua");
	cbox:RegisterBox("Domino/System/BuddyRescue.lua");
	cbox:RegisterBox("Domino/System/GetClosestAutomaticPrefab.lua");
	cbox:RegisterBox("Domino/System/SimpleNode.lua");
	cbox:RegisterBox("Domino/System/SetBoolean.lua");
	cbox:RegisterBox("Domino/System/OutputOrder.lua");
	cbox:RegisterBox("Domino/System/SpawnBuddy.lua");
	cbox:RegisterBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_WAIT_BECKON_GREET.lua");
	cbox:RegisterBox("Domino/System/LogToConsole.lua");
	cbox:RegisterBox("Domino/System/BuddyRescueState.lua");
	cbox:RegisterBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_DIALOG_INTERACT.lua");
	cbox:RegisterBox("Domino/System/GetBuddyList.lua");
	cbox:RegisterBox("Domino/System/CompareStrings.lua");
	cbox:RegisterBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	cbox:RegisterBox("Domino/System/SetBuddySavePointMode.lua");
	cbox:RegisterBox("Domino/User/SavePoints/SavePoints.SaveHouse_SpecialEndBark.lua");
	cbox:RegisterBox("Domino/System/StringConcatenate.lua");
	cbox:RegisterBox("Domino/System/ThreeStringLog.lua");
	cbox:RegisterBox("Domino/System/Delay.lua");
	cbox:RegisterBox("Domino/System/GetEntityInPrefab.lua");
	cbox:RegisterBox("Domino/System/RemoveBuddy.lua");
	cbox:RegisterBox("Domino/System/ProximityTrigger.lua");
	
	-- Load resources
	cbox:LoadResource("Safehouse_NotInteractable", "CMovementResource");
	cbox:LoadResource("Safehouse_Interactable", "CMovementResource");
end;

function export:Init(cbox)
	self.BarkDataTag = "";
	self.BU1 = nil;
	self.BU2 = nil;
	self.BU3 = nil;
	self.BuddyName = "";
	self.Current_BuddySpawnPoint = nil;
	self.CurrentTriggerID = nil;
	self.FilterTrigger = nil;
	self.HistoryBarkDataTag = "";
	self.Mission = "";
	self.Missions = "";
	self.Player = nil;
	self.Prepped = 0;
	self.SafehousePrefab = nil;
	self.SavePointsPaused = 0;
	self.SpawnedBuddyEntityID = nil;
	self.Ubidays = 0;
	self[91] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[91]._graph = self;
	self[91].Update = self._type.f_91_Update;
	self[85] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[85]._graph = self;
	self[85].Update = self._type.f_85_Update;
	self[107] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[107]._graph = self;
	self[107].Update = self._type.f_107_Update;
	self[69] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[69]._graph = self;
	self[69].Update = self._type.f_69_Update;
	self[27] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[27]._graph = self;
	self[27].Update = self._type.f_27_Update;
	self[48] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[48]._graph = self;
	self[48].Update = self._type.f_48_Update;
	self[82] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[82]._graph = self;
	self[82].Update = self._type.f_82_Update;
	self[105] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[105]._graph = self;
	self[105].Update = self._type.f_105_Update;
	self[16] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[16]._graph = self;
	self[16].Update = self._type.f_16_Update;
	self[29] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[29]._graph = self;
	self[29].Update = self._type.f_29_Update;
	self[32] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[32]._graph = self;
	self[32].Update = self._type.f_32_Update;
	self[127] = cbox:CreateBox("Domino/System/BroadcastMessage.lua");
	self[127]._graph = self;
	self[127].Out = self._type.f_127_Out;
	self[99] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[99]._graph = self;
	self[99].Update = self._type.f_99_Update;
	self[92] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[92]._graph = self;
	self[92].Update = self._type.f_92_Update;
	self[51] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[51]._graph = self;
	self[51].Update = self._type.f_51_Update;
	self[28] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[28]._graph = self;
	self[28].Update = self._type.f_28_Update;
	self[95] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[95]._graph = self;
	self[95].Update = self._type.f_95_Update;
	self[22] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[22]._graph = self;
	self[22].Enter = self._type.f_22_Enter;
	self[22].Leave = DummyFunction;
	self[22].Use = DummyFunction;
	self[135] = cbox:CreateBox("Domino/System/GetClosestAutomaticPrefab.lua");
	self[135]._graph = self;
	self[135].Out = self._type.f_135_Out;
	self[132] = cbox:CreateBox("Domino/System/SpawnBuddy.lua");
	self[132]._graph = self;
	self[132].Out = self._type.f_132_Out;
	self[132].BuddyReady = self._type.f_132_BuddyReady;
	self[67] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[67]._graph = self;
	self[67].Update = self._type.f_67_Update;
	self[136] = cbox:CreateBox("Domino/System/GetEntityInPrefab.lua");
	self[136]._graph = self;
	self[136].Out = self._type.f_136_Out;
	self[124] = cbox:CreateBox("Domino/System/Delay.lua");
	self[124]._graph = self;
	self[124].TimeElapsed = self._type.f_124_TimeElapsed;
	self[108] = cbox:CreateBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_WAIT_BECKON_GREET.lua");
	self[108]._graph = self;
	self[108].Started = self._type.f_108_Started;
	self[108].Beckon_finished = DummyFunction;
	self[108].Greet_finished = self._type.f_108_Greet_finished;
	self[108].Canceled = self._type.f_108_Canceled;
	self[24] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[24]._graph = self;
	self[24].Update = self._type.f_24_Update;
	self[94] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[94]._graph = self;
	self[94].Update = self._type.f_94_Update;
	self[84] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[84]._graph = self;
	self[84].Update = self._type.f_84_Update;
	self[83] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[83]._graph = self;
	self[83].Update = self._type.f_83_Update;
	self[26] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[26]._graph = self;
	self[26].Update = self._type.f_26_Update;
	self[78] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[78]._graph = self;
	self[78].Update = self._type.f_78_Update;
	self[101] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[101]._graph = self;
	self[101].Update = self._type.f_101_Update;
	self[50] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[50]._graph = self;
	self[50].Update = self._type.f_50_Update;
	self[41] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[41]._graph = self;
	self[41].Update = self._type.f_41_Update;
	self[131] = cbox:CreateBox("Domino/System/Delay.lua");
	self[131]._graph = self;
	self[131].TimeElapsed = self._type.f_131_TimeElapsed;
	self[38] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[38]._graph = self;
	self[38].Update = self._type.f_38_Update;
	self[90] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[90]._graph = self;
	self[90].Update = self._type.f_90_Update;
	self[25] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[25]._graph = self;
	self[25].Update = self._type.f_25_Update;
	self[17] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[17]._graph = self;
	self[17].Update = self._type.f_17_Update;
	self[86] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[86]._graph = self;
	self[86].Update = self._type.f_86_Update;
	self[49] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[49]._graph = self;
	self[49].Update = self._type.f_49_Update;
	self[100] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[100]._graph = self;
	self[100].Update = self._type.f_100_Update;
	self[106] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[106]._graph = self;
	self[106].Update = self._type.f_106_Update;
	self[34] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[34]._graph = self;
	self[34].Update = self._type.f_34_Update;
	self[61] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[61]._graph = self;
	self[61].Update = self._type.f_61_Update;
	self[104] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[104]._graph = self;
	self[104].Update = self._type.f_104_Update;
	self[43] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[43]._graph = self;
	self[43].Update = self._type.f_43_Update;
	self[64] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[64]._graph = self;
	self[64].Update = self._type.f_64_Update;
	self[52] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[52]._graph = self;
	self[52].Update = self._type.f_52_Update;
	self[75] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[75]._graph = self;
	self[75].Update = self._type.f_75_Update;
	self[120] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_SpecialEndBark.lua");
	self[120]._graph = self;
	self[120].Prepared = self._type.f_120_Prepared;
	self[120].DialC_Done = DummyFunction;
	self[120].Finish = self._type.f_120_Finish;
	self[120].Canceled = self._type.f_120_Canceled;
	self[96] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[96]._graph = self;
	self[96].Update = self._type.f_96_Update;
	self[72] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[72]._graph = self;
	self[72].Update = self._type.f_72_Update;
	self[53] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[53]._graph = self;
	self[53].Update = self._type.f_53_Update;
	self[79] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[79]._graph = self;
	self[79].Update = self._type.f_79_Update;
	self[31] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[31]._graph = self;
	self[31].Update = self._type.f_31_Update;
	self[80] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[80]._graph = self;
	self[80].Update = self._type.f_80_Update;
	self[89] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[89]._graph = self;
	self[89].Update = self._type.f_89_Update;
	self[76] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[76]._graph = self;
	self[76].Update = self._type.f_76_Update;
	self[42] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[42]._graph = self;
	self[42].Update = self._type.f_42_Update;
	self[114] = cbox:CreateBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_DIALOG_INTERACT.lua");
	self[114]._graph = self;
	self[114].Prepared = self._type.f_114_Prepared;
	self[114].Dialog_started = DummyFunction;
	self[114].Dialog_finished = self._type.f_114_Dialog_finished;
	self[114].Canceled = self._type.f_114_Canceled;
	self[115] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[115]._graph = self;
	self[115].Enter = DummyFunction;
	self[115].Leave = self._type.f_115_Leave;
	self[115].Use = DummyFunction;
	self[81] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[81]._graph = self;
	self[81].Update = self._type.f_81_Update;
	self[125] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[125]._graph = self;
	self[125].Enter = DummyFunction;
	self[125].Leave = self._type.f_125_Leave;
	self[125].Use = DummyFunction;
	self[23] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[23]._graph = self;
	self[23].Update = self._type.f_23_Update;
	self[77] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[77]._graph = self;
	self[77].Update = self._type.f_77_Update;
	self[57] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[57]._graph = self;
	self[57].Update = self._type.f_57_Update;
	self[118] = cbox:CreateBox("Domino/User/Common_MissionBriefings.SCRIPTEDPAWN_INTERACT_PLUS.lua");
	self[118]._graph = self;
	self[118].Prepared = self._type.f_118_Prepared;
	self[118].Dialog_started = DummyFunction;
	self[118].Dialog_finished = self._type.f_118_Dialog_finished;
	self[118].Canceled = self._type.f_118_Canceled;
	self[45] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[45]._graph = self;
	self[45].Update = self._type.f_45_Update;
	self[30] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[30]._graph = self;
	self[30].Update = self._type.f_30_Update;
	self[58] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[58]._graph = self;
	self[58].Update = self._type.f_58_Update;
	self[87] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[87]._graph = self;
	self[87].Enter = self._type.f_87_Enter;
	self[87].Leave = DummyFunction;
	self[87].Use = DummyFunction;
	self[33] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[33]._graph = self;
	self[33].Update = self._type.f_33_Update;
	self[44] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[44]._graph = self;
	self[44].Update = self._type.f_44_Update;
	self[88] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[88]._graph = self;
	self[88].Update = self._type.f_88_Update;
	self[35] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[35]._graph = self;
	self[35].Update = self._type.f_35_Update;
	self[56] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[56]._graph = self;
	self[56].Update = self._type.f_56_Update;
	self[68] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[68]._graph = self;
	self[68].Update = self._type.f_68_Update;
	self[93] = cbox:CreateBox("Domino/User/SavePoints/SavePoints.SaveHouse_Monitor.lua");
	self[93]._graph = self;
	self[93].Update = self._type.f_93_Update;
end;

function export:ShutDown()
	self[91]._type.ShutDown(self[91]);
	self[85]._type.ShutDown(self[85]);
	self[107]._type.ShutDown(self[107]);
	self[69]._type.ShutDown(self[69]);
	self[27]._type.ShutDown(self[27]);
	self[48]._type.ShutDown(self[48]);
	self[82]._type.ShutDown(self[82]);
	self[105]._type.ShutDown(self[105]);
	self[16]._type.ShutDown(self[16]);
	self[29]._type.ShutDown(self[29]);
	self[32]._type.ShutDown(self[32]);
	self[127]._type.ShutDown(self[127]);
	self[99]._type.ShutDown(self[99]);
	self[92]._type.ShutDown(self[92]);
	self[51]._type.ShutDown(self[51]);
	self[28]._type.ShutDown(self[28]);
	self[95]._type.ShutDown(self[95]);
	self[22]._type.ShutDown(self[22]);
	self[135]._type.ShutDown(self[135]);
	self[132]._type.ShutDown(self[132]);
	self[67]._type.ShutDown(self[67]);
	self[136]._type.ShutDown(self[136]);
	self[124]._type.ShutDown(self[124]);
	self[108]._type.ShutDown(self[108]);
	self[24]._type.ShutDown(self[24]);
	self[94]._type.ShutDown(self[94]);
	self[84]._type.ShutDown(self[84]);
	self[83]._type.ShutDown(self[83]);
	self[26]._type.ShutDown(self[26]);
	self[78]._type.ShutDown(self[78]);
	self[101]._type.ShutDown(self[101]);
	self[50]._type.ShutDown(self[50]);
	self[41]._type.ShutDown(self[41]);
	self[131]._type.ShutDown(self[131]);
	self[38]._type.ShutDown(self[38]);
	self[90]._type.ShutDown(self[90]);
	self[25]._type.ShutDown(self[25]);
	self[17]._type.ShutDown(self[17]);
	self[86]._type.ShutDown(self[86]);
	self[49]._type.ShutDown(self[49]);
	self[100]._type.ShutDown(self[100]);
	self[106]._type.ShutDown(self[106]);
	self[34]._type.ShutDown(self[34]);
	self[61]._type.ShutDown(self[61]);
	self[104]._type.ShutDown(self[104]);
	self[43]._type.ShutDown(self[43]);
	self[64]._type.ShutDown(self[64]);
	self[52]._type.ShutDown(self[52]);
	self[75]._type.ShutDown(self[75]);
	self[120]._type.ShutDown(self[120]);
	self[96]._type.ShutDown(self[96]);
	self[72]._type.ShutDown(self[72]);
	self[53]._type.ShutDown(self[53]);
	self[79]._type.ShutDown(self[79]);
	self[31]._type.ShutDown(self[31]);
	self[80]._type.ShutDown(self[80]);
	self[89]._type.ShutDown(self[89]);
	self[76]._type.ShutDown(self[76]);
	self[42]._type.ShutDown(self[42]);
	self[114]._type.ShutDown(self[114]);
	self[115]._type.ShutDown(self[115]);
	self[81]._type.ShutDown(self[81]);
	self[125]._type.ShutDown(self[125]);
	self[23]._type.ShutDown(self[23]);
	self[77]._type.ShutDown(self[77]);
	self[57]._type.ShutDown(self[57]);
	self[118]._type.ShutDown(self[118]);
	self[45]._type.ShutDown(self[45]);
	self[30]._type.ShutDown(self[30]);
	self[58]._type.ShutDown(self[58]);
	self[87]._type.ShutDown(self[87]);
	self[33]._type.ShutDown(self[33]);
	self[44]._type.ShutDown(self[44]);
	self[88]._type.ShutDown(self[88]);
	self[35]._type.ShutDown(self[35]);
	self[56]._type.ShutDown(self[56]);
	self[68]._type.ShutDown(self[68]);
	self[93]._type.ShutDown(self[93]);
end;

function export:Start()
	self._type.en_16(self);
	self[16]._type.Start_W2(self[16]);
	self._type.en_17(self);
	self[17]._type.StartW1(self[17]);
	self[22].Trigger = "2054257261078906210";
	self[22]._type.Enable(self[22]);
	self._type.en_23(self);
	self[23]._type.Start_W2(self[23]);
	self._type.en_24(self);
	self[24]._type.StartW1(self[24]);
	self._type.en_25(self);
	self[25]._type.StartW1(self[25]);
	self._type.en_26(self);
	self[26]._type.Start_W2(self[26]);
	self._type.en_27(self);
	self[27]._type.StartW1(self[27]);
	self._type.en_28(self);
	self[28]._type.StartW1(self[28]);
	self._type.en_29(self);
	self[29]._type.StartW1(self[29]);
	self._type.en_30(self);
	self[30]._type.StartW1(self[30]);
	self._type.en_31(self);
	self[31]._type.StartW1(self[31]);
	self._type.en_32(self);
	self[32]._type.Start_W2(self[32]);
	self._type.en_33(self);
	self[33]._type.StartW1(self[33]);
	self._type.en_34(self);
	self[34]._type.Start_W2(self[34]);
	self._type.en_35(self);
	self[35]._type.StartW1(self[35]);
	self._type.en_38(self);
	self[38]._type.StartW1(self[38]);
	self._type.en_41(self);
	self[41]._type.StartW1(self[41]);
	self._type.en_42(self);
	self[42]._type.StartW1(self[42]);
	self._type.en_43(self);
	self[43]._type.StartW1(self[43]);
	self._type.en_44(self);
	self[44]._type.Start_W2(self[44]);
	self._type.en_45(self);
	self[45]._type.Start_W2(self[45]);
	self._type.en_48(self);
	self[48]._type.Start_W2(self[48]);
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "*** Save Point  System Enabled***";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
	self._type.en_1(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
	self._type.en_49(self);
	self[49]._type.Start_W2(self[49]);
	self._type.en_50(self);
	self[50]._type.StartW1(self[50]);
	self._type.en_51(self);
	self[51]._type.StartW1(self[51]);
	self._type.en_52(self);
	self[52]._type.StartW1(self[52]);
	self._type.en_53(self);
	self[53]._type.Start_W2(self[53]);
	self._type.en_56(self);
	self[56]._type.Start_W2(self[56]);
	self._type.en_57(self);
	self[57]._type.StartW1(self[57]);
	self._type.en_58(self);
	self[58]._type.Start_W2(self[58]);
	self._type.en_61(self);
	self[61]._type.StartW1(self[61]);
	self._type.en_64(self);
	self[64]._type.Start_W2(self[64]);
	self._type.en_67(self);
	self[67]._type.Start_W2(self[67]);
	self._type.en_68(self);
	self[68]._type.Start_W2(self[68]);
	self._type.en_69(self);
	self[69]._type.Start_W2(self[69]);
	self._type.en_72(self);
	self[72]._type.StartW1(self[72]);
	self._type.en_75(self);
	self[75]._type.StartW1(self[75]);
	self._type.en_76(self);
	self[76]._type.StartW1(self[76]);
	self._type.en_77(self);
	self[77]._type.Start_W2(self[77]);
	self._type.en_78(self);
	self[78]._type.StartW1(self[78]);
	self._type.en_79(self);
	self[79]._type.Start_W2(self[79]);
	self._type.en_80(self);
	self[80]._type.StartW1(self[80]);
	self._type.en_81(self);
	self[81]._type.StartW1(self[81]);
	self._type.en_82(self);
	self[82]._type.Start_W2(self[82]);
	self._type.en_83(self);
	self[83]._type.StartW1(self[83]);
	self._type.en_84(self);
	self[84]._type.Start_W2(self[84]);
	self._type.en_85(self);
	self[85]._type.StartW1(self[85]);
	self._type.en_86(self);
	self[86]._type.StartW1(self[86]);
	self[87].Trigger = "2054303976421065770";
	self[87]._type.Enable(self[87]);
	self._type.en_88(self);
	self[88]._type.Start_W2(self[88]);
	self._type.en_89(self);
	self[89]._type.StartW1(self[89]);
	self._type.en_90(self);
	self[90]._type.Start_W2(self[90]);
	self._type.en_91(self);
	self[91]._type.Start_W2(self[91]);
	self._type.en_92(self);
	self[92]._type.StartW1(self[92]);
	self._type.en_93(self);
	self[93]._type.StartW1(self[93]);
	self._type.en_94(self);
	self[94]._type.StartW1(self[94]);
	self._type.en_95(self);
	self[95]._type.Start_W2(self[95]);
	self._type.en_96(self);
	self[96]._type.StartW1(self[96]);
	self._type.en_99(self);
	self[99]._type.Start_W2(self[99]);
	self._type.en_100(self);
	self[100]._type.Start_W2(self[100]);
	self._type.en_101(self);
	self[101]._type.StartW1(self[101]);
	self._type.en_104(self);
	self[104]._type.StartW1(self[104]);
	self._type.en_105(self);
	self[105]._type.Start_W2(self[105]);
	self._type.en_106(self);
	self[106]._type.StartW1(self[106]);
	self._type.en_107(self);
	self[107]._type.StartW1(self[107]);
end;

function export:Pause()
	self._type.en_64(self);
	self[64]._type.Pause(self[64]);
	self._type.en_101(self);
	self[101]._type.Pause(self[101]);
	self._type.en_91(self);
	self[91]._type.Pause(self[91]);
	self._type.en_86(self);
	self[86]._type.Pause(self[86]);
	self._type.en_100(self);
	self[100]._type.Pause(self[100]);
	self._type.en_89(self);
	self[89]._type.Pause(self[89]);
	self._type.en_34(self);
	self[34]._type.Pause(self[34]);
	self._type.en_94(self);
	self[94]._type.Pause(self[94]);
	self._type.en_81(self);
	self[81]._type.Pause(self[81]);
	self._type.en_93(self);
	self[93]._type.Pause(self[93]);
	self._type.en_28(self);
	self[28]._type.Pause(self[28]);
	self._type.en_24(self);
	self[24]._type.Pause(self[24]);
	self._type.en_49(self);
	self[49]._type.Pause(self[49]);
	self._type.en_52(self);
	self[52]._type.Pause(self[52]);
	self._type.en_68(self);
	self[68]._type.Pause(self[68]);
	self._type.en_106(self);
	self[106]._type.Pause(self[106]);
	self._type.en_44(self);
	self[44]._type.Pause(self[44]);
	self._type.en_82(self);
	self[82]._type.Pause(self[82]);
	self._type.en_76(self);
	self[76]._type.Pause(self[76]);
	self._type.en_84(self);
	self[84]._type.Pause(self[84]);
	self._type.en_53(self);
	self[53]._type.Pause(self[53]);
	self._type.en_108(self);
	self[108]._type.Cancel(self[108]);
	self._type.en_75(self);
	self[75]._type.Pause(self[75]);
	self._type.en_78(self);
	self[78]._type.Pause(self[78]);
	self._type.en_88(self);
	self[88]._type.Pause(self[88]);
	self._type.en_67(self);
	self[67]._type.Pause(self[67]);
	self._type.en_29(self);
	self[29]._type.Pause(self[29]);
	self._type.en_107(self);
	self[107]._type.Pause(self[107]);
	self._type.en_69(self);
	self[69]._type.Pause(self[69]);
	self._type.en_51(self);
	self[51]._type.Pause(self[51]);
	self._type.en_85(self);
	self[85]._type.Pause(self[85]);
	self._type.en_45(self);
	self[45]._type.Pause(self[45]);
	self._type.en_32(self);
	self[32]._type.Pause(self[32]);
	self._type.en_105(self);
	self[105]._type.Pause(self[105]);
	self._type.en_16(self);
	self[16]._type.Pause(self[16]);
	self._type.en_26(self);
	self[26]._type.Pause(self[26]);
	self._type.en_25(self);
	self[25]._type.Pause(self[25]);
	self._type.en_96(self);
	self[96]._type.Pause(self[96]);
	self._type.en_30(self);
	self[30]._type.Pause(self[30]);
	self._type.en_50(self);
	self[50]._type.Pause(self[50]);
	self._type.en_48(self);
	self[48]._type.Pause(self[48]);
	self._type.en_90(self);
	self[90]._type.Pause(self[90]);
	self._type.en_104(self);
	self[104]._type.Pause(self[104]);
	self._type.en_58(self);
	self[58]._type.Pause(self[58]);
	self._type.en_83(self);
	self[83]._type.Pause(self[83]);
	self._type.en_27(self);
	self[27]._type.Pause(self[27]);
	self._type.en_61(self);
	self[61]._type.Pause(self[61]);
	self._type.en_43(self);
	self[43]._type.Pause(self[43]);
	self._type.en_35(self);
	self[35]._type.Pause(self[35]);
	self._type.en_95(self);
	self[95]._type.Pause(self[95]);
	self._type.en_41(self);
	self[41]._type.Pause(self[41]);
	self._type.en_17(self);
	self[17]._type.Pause(self[17]);
	self._type.en_99(self);
	self[99]._type.Pause(self[99]);
	self._type.en_31(self);
	self[31]._type.Pause(self[31]);
	self._type.en_1(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
	self._type.en_38(self);
	self[38]._type.Pause(self[38]);
	self._type.en_23(self);
	self[23]._type.Pause(self[23]);
	self._type.en_72(self);
	self[72]._type.Pause(self[72]);
	self._type.en_80(self);
	self[80]._type.Pause(self[80]);
	self._type.en_56(self);
	self[56]._type.Pause(self[56]);
	self._type.en_77(self);
	self[77]._type.Pause(self[77]);
	self._type.en_57(self);
	self[57]._type.Pause(self[57]);
	self._type.en_92(self);
	self[92]._type.Pause(self[92]);
	self._type.en_42(self);
	self[42]._type.Pause(self[42]);
	self._type.en_79(self);
	self[79]._type.Pause(self[79]);
	self._type.en_33(self);
	self[33]._type.Pause(self[33]);
end;

function export:W1_Spawn_Enable()
	self._type.en_3(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:W1_Spawn_Disable()
	self._type.en_3(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:W2_Spawn_Enable()
	self._type.en_5(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:W2_Spawn_Disable()
	self._type.en_5(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_1_Out()
	self = self._graph;
	self.SavePointsPaused = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
end;

function export:f_3_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.W1_SafeHouseCanSpawn = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = Globals.MASTER_GameGlobals.W1_SafeHouseCanSpawn;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "World 1 Safe house spawning";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_5_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.W2_SafeHouseCanSpawn = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = Globals.MASTER_GameGlobals.W2_SafeHouseCanSpawn;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "World 2 Safe house spawning";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_6_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_10_Activated()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "*** Rescue Buddy already set, cancelling spawn";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_11_Out_0()
	self = self._graph;
	self._type.en_124(self);
	self[124]._type.Start(self[124]);
end;

function export:f_11_Out_1()
	self = self._graph;
	self._type.en_125(self);
	self[125]._type.Enable(self[125]);
end;

function export:f_10_Deactivated()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_11_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_11_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_13_Out()
	self = self._graph;
	self.BarkDataTag = Boxes[PathID("Domino/System/SetString.lua")].Target;
	Boxes[PathID("Domino/System/BuddyRescueState.lua")]._graph = self;
	Boxes[PathID("Domino/System/BuddyRescueState.lua")].Activated = self._type.f_10_Activated;
	Boxes[PathID("Domino/System/BuddyRescueState.lua")].Deactivated = self._type.f_10_Deactivated;
	Boxes[PathID("Domino/System/BuddyRescueState.lua")]._type.In(Boxes[PathID("Domino/System/BuddyRescueState.lua")]);
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "*** Save Point  Bark Data Loaded ***";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_15_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "*** Save Point  Trigger Out ***";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
	self._type.en_115(self);
	self[115]._type.Enable(self[115]);
	Boxes[PathID("Domino/System/SetString.lua")].String = "SAV";
	Boxes[PathID("Domino/System/SetString.lua")].Integer = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/SetString.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetString.lua")].Out = self._type.f_13_Out;
	Boxes[PathID("Domino/System/SetString.lua")]._type.FromString(Boxes[PathID("Domino/System/SetString.lua")]);
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "*** Save Point  System Active ***";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_6_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_16_Update()
	self = self._graph;
	self.CurrentTriggerID = self[16].Current_Trigger;
	self.Current_BuddySpawnPoint = self[16].Current_Spawn;
	-- Update 3.6: Fix library mission checks to prevent rescue buddies spawning in the same safe house as primary buddies
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM12";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_6_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_6_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_17_Update()
	self = self._graph;
	self.CurrentTriggerID = self[17].Current_Trigger;
	self.Current_BuddySpawnPoint = self[17].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_18_A_is_True()
	self = self._graph;
	self._type.en_108(self);
	self[108]._type.Cancel(self[108]);
end;

function export:f_19_Out()
	self = self._graph;
	self._type.en_18(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_20_Out()
	self = self._graph;
	self._sld_Target_20 = Boxes[PathID("Domino/System/StringConcatenate.lua")].Target;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = self._sld_Target_20;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = self.SpawnedBuddyEntityID;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_19_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_21_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Input = "*** Save Point  Buddy  INSTANT Removing ";
	Boxes[PathID("Domino/System/StringConcatenate.lua")].String = self.BuddyName;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Integer = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Float = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")]._graph = self;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Out = self._type.f_20_Out;
	Boxes[PathID("Domino/System/StringConcatenate.lua")]._type.WithString(Boxes[PathID("Domino/System/StringConcatenate.lua")]);
end;

function export:f_22_Enter()
	self = self._graph;
	self._type.en_21(self);
	Boxes[PathID("Domino/System/RemoveBuddy.lua")]._type.In(Boxes[PathID("Domino/System/RemoveBuddy.lua")]);
end;

function export:f_23_Update()
	self = self._graph;
	self.CurrentTriggerID = self[23].Current_Trigger;
	self.Current_BuddySpawnPoint = self[23].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_24_Update()
	self = self._graph;
	self.CurrentTriggerID = self[24].Current_Trigger;
	self.Current_BuddySpawnPoint = self[24].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_25_Update()
	self = self._graph;
	self.CurrentTriggerID = self[25].Current_Trigger;
	self.Current_BuddySpawnPoint = self[25].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_26_Update()
	self = self._graph;
	self.CurrentTriggerID = self[26].Current_Trigger;
	self.Current_BuddySpawnPoint = self[26].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_27_Update()
	self = self._graph;
	self.CurrentTriggerID = self[27].Current_Trigger;
	self.Current_BuddySpawnPoint = self[27].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_28_Update()
	self = self._graph;
	self.CurrentTriggerID = self[28].Current_Trigger;
	self.Current_BuddySpawnPoint = self[28].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_29_Update()
	self = self._graph;
	self.CurrentTriggerID = self[29].Current_Trigger;
	self.Current_BuddySpawnPoint = self[29].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_30_Update()
	self = self._graph;
	self.CurrentTriggerID = self[30].Current_Trigger;
	self.Current_BuddySpawnPoint = self[30].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_31_Update()
	self = self._graph;
	self.CurrentTriggerID = self[31].Current_Trigger;
	self.Current_BuddySpawnPoint = self[31].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_32_Update()
	self = self._graph;
	self.CurrentTriggerID = self[32].Current_Trigger;
	self.Current_BuddySpawnPoint = self[32].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_33_Update()
	self = self._graph;
	self.CurrentTriggerID = self[33].Current_Trigger;
	self.Current_BuddySpawnPoint = self[33].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_34_Update()
	self = self._graph;
	self.CurrentTriggerID = self[34].Current_Trigger;
	self.Current_BuddySpawnPoint = self[34].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_35_Update()
	self = self._graph;
	self.CurrentTriggerID = self[35].Current_Trigger;
	self.Current_BuddySpawnPoint = self[35].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_36_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_36_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_38_Update()
	self = self._graph;
	self.CurrentTriggerID = self[38].Current_Trigger;
	self.Current_BuddySpawnPoint = self[38].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM02";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_36_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_36_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_39_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_39_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_41_Update()
	self = self._graph;
	self.CurrentTriggerID = self[41].Current_Trigger;
	self.Current_BuddySpawnPoint = self[41].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM05";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_39_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_39_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_42_Update()
	self = self._graph;
	self.CurrentTriggerID = self[42].Current_Trigger;
	self.Current_BuddySpawnPoint = self[42].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_43_Update()
	self = self._graph;
	self.CurrentTriggerID = self[43].Current_Trigger;
	self.Current_BuddySpawnPoint = self[43].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_44_Update()
	self = self._graph;
	self.CurrentTriggerID = self[44].Current_Trigger;
	self.Current_BuddySpawnPoint = self[44].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_45_Update()
	self = self._graph;
	self.CurrentTriggerID = self[45].Current_Trigger;
	self.Current_BuddySpawnPoint = self[45].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_46_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_46_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_48_Update()
	self = self._graph;
	self.CurrentTriggerID = self[48].Current_Trigger;
	self.Current_BuddySpawnPoint = self[48].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM08";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_46_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_46_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_49_Update()
	self = self._graph;
	self.CurrentTriggerID = self[49].Current_Trigger;
	self.Current_BuddySpawnPoint = self[49].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_50_Update()
	self = self._graph;
	self.CurrentTriggerID = self[50].Current_Trigger;
	self.Current_BuddySpawnPoint = self[50].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_51_Update()
	self = self._graph;
	self.CurrentTriggerID = self[51].Current_Trigger;
	self.Current_BuddySpawnPoint = self[51].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_52_Update()
	self = self._graph;
	self.CurrentTriggerID = self[52].Current_Trigger;
	self.Current_BuddySpawnPoint = self[52].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_53_Update()
	self = self._graph;
	self.CurrentTriggerID = self[53].Current_Trigger;
	self.Current_BuddySpawnPoint = self[53].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_54_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_54_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_56_Update()
	self = self._graph;
	self.CurrentTriggerID = self[56].Current_Trigger;
	self.Current_BuddySpawnPoint = self[56].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM11";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_54_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_54_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_57_Update()
	self = self._graph;
	self.CurrentTriggerID = self[57].Current_Trigger;
	self.Current_BuddySpawnPoint = self[57].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_58_Update()
	self = self._graph;
	self.CurrentTriggerID = self[58].Current_Trigger;
	self.Current_BuddySpawnPoint = self[58].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_59_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_59_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_61_Update()
	self = self._graph;
	self.CurrentTriggerID = self[61].Current_Trigger;
	self.Current_BuddySpawnPoint = self[61].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM06";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_59_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_59_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_62_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_62_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_64_Update()
	self = self._graph;
	self.CurrentTriggerID = self[64].Current_Trigger;
	self.Current_BuddySpawnPoint = self[64].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM09";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_62_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_62_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_65_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_65_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_67_Update()
	self = self._graph;
	self.CurrentTriggerID = self[67].Current_Trigger;
	self.Current_BuddySpawnPoint = self[67].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM07";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_65_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_65_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_68_Update()
	self = self._graph;
	self.CurrentTriggerID = self[68].Current_Trigger;
	self.Current_BuddySpawnPoint = self[68].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_69_Update()
	self = self._graph;
	self.CurrentTriggerID = self[69].Current_Trigger;
	self.Current_BuddySpawnPoint = self[69].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_70_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_70_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_72_Update()
	self = self._graph;
	self.CurrentTriggerID = self[72].Current_Trigger;
	self.Current_BuddySpawnPoint = self[72].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM03";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_70_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_70_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_73_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_73_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_75_Update()
	self = self._graph;
	self.CurrentTriggerID = self[75].Current_Trigger;
	self.Current_BuddySpawnPoint = self[75].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM01";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_73_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_73_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_76_Update()
	self = self._graph;
	self.CurrentTriggerID = self[76].Current_Trigger;
	self.Current_BuddySpawnPoint = self[76].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_77_Update()
	self = self._graph;
	self.CurrentTriggerID = self[77].Current_Trigger;
	self.Current_BuddySpawnPoint = self[77].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_78_Update()
	self = self._graph;
	self.CurrentTriggerID = self[78].Current_Trigger;
	self.Current_BuddySpawnPoint = self[78].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_79_Update()
	self = self._graph;
	self.CurrentTriggerID = self[79].Current_Trigger;
	self.Current_BuddySpawnPoint = self[79].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_80_Update()
	self = self._graph;
	self.CurrentTriggerID = self[80].Current_Trigger;
	self.Current_BuddySpawnPoint = self[80].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_81_Update()
	self = self._graph;
	self.CurrentTriggerID = self[81].Current_Trigger;
	self.Current_BuddySpawnPoint = self[81].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_82_Update()
	self = self._graph;
	self.CurrentTriggerID = self[82].Current_Trigger;
	self.Current_BuddySpawnPoint = self[82].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_83_Update()
	self = self._graph;
	self.CurrentTriggerID = self[83].Current_Trigger;
	self.Current_BuddySpawnPoint = self[83].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_84_Update()
	self = self._graph;
	self.CurrentTriggerID = self[84].Current_Trigger;
	self.Current_BuddySpawnPoint = self[84].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_85_Update()
	self = self._graph;
	self.CurrentTriggerID = self[85].Current_Trigger;
	self.Current_BuddySpawnPoint = self[85].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_86_Update()
	self = self._graph;
	self.CurrentTriggerID = self[86].Current_Trigger;
	self.Current_BuddySpawnPoint = self[86].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_87_Enter()
	self = self._graph;
	self._type.en_21(self);
	Boxes[PathID("Domino/System/RemoveBuddy.lua")]._type.In(Boxes[PathID("Domino/System/RemoveBuddy.lua")]);
end;

function export:f_88_Update()
	self = self._graph;
	self.CurrentTriggerID = self[88].Current_Trigger;
	self.Current_BuddySpawnPoint = self[88].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_89_Update()
	self = self._graph;
	self.CurrentTriggerID = self[89].Current_Trigger;
	self.Current_BuddySpawnPoint = self[89].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_90_Update()
	self = self._graph;
	self.CurrentTriggerID = self[90].Current_Trigger;
	self.Current_BuddySpawnPoint = self[90].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_91_Update()
	self = self._graph;
	self.CurrentTriggerID = self[91].Current_Trigger;
	self.Current_BuddySpawnPoint = self[91].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_92_Update()
	self = self._graph;
	self.CurrentTriggerID = self[92].Current_Trigger;
	self.Current_BuddySpawnPoint = self[92].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_93_Update()
	self = self._graph;
	self.CurrentTriggerID = self[93].Current_Trigger;
	self.Current_BuddySpawnPoint = self[93].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_94_Update()
	self = self._graph;
	self.CurrentTriggerID = self[94].Current_Trigger;
	self.Current_BuddySpawnPoint = self[94].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_95_Update()
	self = self._graph;
	self.CurrentTriggerID = self[95].Current_Trigger;
	self.Current_BuddySpawnPoint = self[95].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_96_Update()
	self = self._graph;
	self.CurrentTriggerID = self[96].Current_Trigger;
	self.Current_BuddySpawnPoint = self[96].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_97_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_97_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_99_Update()
	self = self._graph;
	self.CurrentTriggerID = self[99].Current_Trigger;
	self.Current_BuddySpawnPoint = self[99].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM10";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_97_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_97_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_100_Update()
	self = self._graph;
	self.CurrentTriggerID = self[100].Current_Trigger;
	self.Current_BuddySpawnPoint = self[100].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_101_Update()
	self = self._graph;
	self.CurrentTriggerID = self[101].Current_Trigger;
	self.Current_BuddySpawnPoint = self[101].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_102_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String1 = "Secondary Spawn blocked";
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String2 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].String3 = nil;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._graph = self;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ThreeStringLog.lua")]._type.In(Boxes[PathID("Domino/System/ThreeStringLog.lua")]);
end;

function export:f_102_A_ncontains_B()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_104_Update()
	self = self._graph;
	self.CurrentTriggerID = self[104].Current_Trigger;
	self.Current_BuddySpawnPoint = self[104].Current_Spawn;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedLibMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "LM04";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_102_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_102_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_105_Update()
	self = self._graph;
	self.CurrentTriggerID = self[105].Current_Trigger;
	self.Current_BuddySpawnPoint = self[105].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_106_Update()
	self = self._graph;
	self.CurrentTriggerID = self[106].Current_Trigger;
	self.Current_BuddySpawnPoint = self[106].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_107_Update()
	self = self._graph;
	self.CurrentTriggerID = self[107].Current_Trigger;
	self.Current_BuddySpawnPoint = self[107].Current_Spawn;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_108_Started()
	self = self._graph;
	self._type.en_114(self);
	self[114]._type.Prepare(self[114]);
end;

function export:f_110_Out()
	self = self._graph;
	self._sld_Target_110 = Boxes[PathID("Domino/System/StringConcatenate.lua")].Target;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = self._sld_Target_110;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_111_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Input = "*** Save Point  Buddy  Removing ";
	Boxes[PathID("Domino/System/StringConcatenate.lua")].String = self.BuddyName;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Integer = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Float = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")]._graph = self;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Out = self._type.f_110_Out;
	Boxes[PathID("Domino/System/StringConcatenate.lua")]._type.WithString(Boxes[PathID("Domino/System/StringConcatenate.lua")]);
end;

function export:f_113_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/RemoveBuddy.lua")].Buddy = self.SpawnedBuddyEntityID;
	Boxes[PathID("Domino/System/RemoveBuddy.lua")].Instant = nil;
	Boxes[PathID("Domino/System/RemoveBuddy.lua")]._graph = self;
	Boxes[PathID("Domino/System/RemoveBuddy.lua")].Out = self._type.f_111_Out;
	Boxes[PathID("Domino/System/RemoveBuddy.lua")]._type.In(Boxes[PathID("Domino/System/RemoveBuddy.lua")]);
	Boxes[PathID("Domino/System/ObjectivePopUp.lua")].Section = nil;
	Boxes[PathID("Domino/System/ObjectivePopUp.lua")].Type = "Safehouse";
	Boxes[PathID("Domino/System/ObjectivePopUp.lua")].Text = "TU_BUDDY_RESCUE_ACTIVATED";
	Boxes[PathID("Domino/System/ObjectivePopUp.lua")].Time = 5;
	Boxes[PathID("Domino/System/ObjectivePopUp.lua")]._graph = self;
	Boxes[PathID("Domino/System/ObjectivePopUp.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/ObjectivePopUp.lua")]._type.In(Boxes[PathID("Domino/System/ObjectivePopUp.lua")]);
end;

function export:f_108_Greet_finished()
	self = self._graph;
	Boxes[PathID("Domino/System/BuddyRescue.lua")]._graph = self;
	Boxes[PathID("Domino/System/BuddyRescue.lua")].Out = self._type.f_113_Out;
	Boxes[PathID("Domino/System/BuddyRescue.lua")]._type.Activate(Boxes[PathID("Domino/System/BuddyRescue.lua")]);
	self._type.en_114(self);
	self[114]._type.Start(self[114]);
end;

function export:f_108_Canceled()
	self = self._graph;
	self._type.en_114(self);
	self[114]._type.Cancel(self[114]);
end;

function export:f_114_Prepared()
	self = self._graph;
	self._type.en_118(self);
	self[118]._type.Prepare(self[118]);
end;

function export:f_114_Dialog_finished()
	self = self._graph;
	self._type.en_118(self);
	self[118]._type.Start(self[118]);
end;

function export:f_114_Canceled()
	self = self._graph;
	self._type.en_118(self);
	self[118]._type.Cancel(self[118]);
end;

function export:f_117_A_is_True()
	self = self._graph;
	self._type.en_115(self);
	self[115]._type.Disable(self[115]);
end;

function export:f_115_Leave()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "*** Save Point  System Inactive ***";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.SavePointsPaused;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_117_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_118_Prepared()
	self = self._graph;
	self._type.en_120(self);
	self[120]._type.Prepare(self[120]);
end;

function export:f_118_Dialog_finished()
	self = self._graph;
	self._type.en_120(self);
	self[120]._type.Start(self[120]);
end;

function export:f_118_Canceled()
	self = self._graph;
	self._type.en_120(self);
	self[120]._type.Cancel(self[120]);
end;

function export:f_119_Out()
	self = self._graph;
	self.Prepped = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
end;

function export:f_120_Prepared()
	self = self._graph;
	self._type.en_119(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_121_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.SH_PreviousWagerBuddy = Boxes[PathID("Domino/System/SetString.lua")].Target;
end;

function export:f_120_Finish()
	self = self._graph;
	Boxes[PathID("Domino/System/SetString.lua")].String = "";
	Boxes[PathID("Domino/System/SetString.lua")].Integer = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/SetString.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetString.lua")].Out = self._type.f_121_Out;
	Boxes[PathID("Domino/System/SetString.lua")]._type.FromString(Boxes[PathID("Domino/System/SetString.lua")]);
end;

function export:f_120_Canceled()
	self = self._graph;
	self._type.en_119(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_122_Out()
	self = self._graph;
	self._type.en_18(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_123_Out_0()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_122_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_123_Out_1()
	self = self._graph;
	self[127].Message = "Spawning_Safehouse2ndBuddy";
	self[127]._type.In(self[127]);
end;

function export:f_124_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_123_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_123_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_126_Out()
	self = self._graph;
	self._type.en_125(self);
	self[125]._type.Disable(self[125]);
	self._type.en_124(self);
	self[124]._type.Stop(self[124]);
end;

function export:f_125_Leave()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_126_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_127_Out()
	self = self._graph;
	self[131].Seconds = 0.5;
	self[131]._type.Start(self[131]);
end;

function export:f_129_Out()
	self = self._graph;
	self._sld_Target_129 = Boxes[PathID("Domino/System/StringConcatenate.lua")].Target;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = self._sld_Target_129;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_130_Out()
	self = self._graph;
	self.BuddyName = Boxes[PathID("Domino/System/GetBuddyList.lua")].Secondary;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Input = "*** Save Point  Buddy Selected : Spawning ";
	Boxes[PathID("Domino/System/StringConcatenate.lua")].String = self.BuddyName;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Integer = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Float = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/StringConcatenate.lua")]._graph = self;
	Boxes[PathID("Domino/System/StringConcatenate.lua")].Out = self._type.f_129_Out;
	Boxes[PathID("Domino/System/StringConcatenate.lua")]._type.WithString(Boxes[PathID("Domino/System/StringConcatenate.lua")]);
	self[132].BuddyName = self.BuddyName;
	self[132].SpawnPoint = self.Current_BuddySpawnPoint;
	self[132].Unarmed = 1;
	self[132]._type.In(self[132]);
end;

function export:f_131_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/GetBuddyList.lua")]._graph = self;
	Boxes[PathID("Domino/System/GetBuddyList.lua")].Out = self._type.f_130_Out;
	Boxes[PathID("Domino/System/GetBuddyList.lua")]._type.In(Boxes[PathID("Domino/System/GetBuddyList.lua")]);
end;

function export:f_132_Out()
	self = self._graph;
	self._type.ex_132(self);
end;

function export:f_134_Out()
	self = self._graph;
	self[135].Pawn = self.SpawnedBuddyEntityID;
	self[135]._type.In(self[135]);
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "*** Save Point  Mode Set ***";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_132_BuddyReady()
	self = self._graph;
	self._type.ex_132(self);
	Boxes[PathID("Domino/System/SetBuddySavePointMode.lua")].Buddy = self.SpawnedBuddyEntityID;
	Boxes[PathID("Domino/System/SetBuddySavePointMode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBuddySavePointMode.lua")].Out = self._type.f_134_Out;
	Boxes[PathID("Domino/System/SetBuddySavePointMode.lua")]._type.Set(Boxes[PathID("Domino/System/SetBuddySavePointMode.lua")]);
end;

function export:f_135_Out()
	self = self._graph;
	self.SafehousePrefab = self[135].Prefab;
	self[136].PrefabEntity = self.SafehousePrefab;
	self[136].ObjectName = "ProximityTrigger";
	self[136]._type.In(self[136]);
end;

function export:f_136_Out()
	self = self._graph;
	self.FilterTrigger = self[136].ObjectEntity;
	self._type.en_108(self);
	self[108]._type.Start(self[108]);
end;

function export:en_16()
	self[16].SH_Trigger = "2054469948744401947";
	self[16].SH_Spawn = "2054469935781905433";
	self[16].SH_Entity = "2056619128942236130";
end;

function export:en_17()
	self[17].SH_Trigger = "2054478607176178865";
	self[17].SH_Spawn = "2054478599362190511";
	self[17].SH_Entity = "2056538505793766370";
end;

function export:en_23()
	self[23].SH_Trigger = "2054470241456495293";
	self[23].SH_Spawn = "2054470241456495292";
	self[23].SH_Entity = "2056674564926080117";
end;

function export:en_24()
	self[24].SH_Trigger = "2053871684726824731";
	self[24].SH_Spawn = "2054468920638715840";
	self[24].SH_Entity = "2056566325072921184";
end;

function export:en_25()
	self[25].SH_Trigger = "2054478946803657052";
	self[25].SH_Spawn = "2054478970409199965";
	self[25].SH_Entity = "2056551886279965693";
end;

function export:en_26()
	self[26].SH_Trigger = "2057747386494631578";
	self[26].SH_Spawn = "2054467564030920393";
	self[26].SH_Entity = "2056678073652240461";
end;

function export:en_27()
	self[27].SH_Trigger = "2055957872371577840";
	self[27].SH_Spawn = "2055957880154108916";
	self[27].SH_Entity = "2056617930885453068";
end;

function export:en_28()
	self[28].SH_Trigger = "2057746790590988475";
	self[28].SH_Spawn = "2057746783502614713";
	self[28].SH_Entity = "2056483334917206811";
end;

function export:en_29()
	self[29].SH_Trigger = "2054478699421506746";
	self[29].SH_Spawn = "2054478719552068796";
	self[29].SH_Entity = "2056537569782413542";
end;

function export:en_30()
	self[30].SH_Trigger = "2054479509863802541";
	self[30].SH_Spawn = "2054479523998607022";
	self[30].SH_Entity = "2056579466697659405";
end;

function export:en_31()
	self[31].SH_Trigger = "2054464802289365748";
	self[31].SH_Spawn = "2054464786848035561";
	self[31].SH_Entity = "2056565915929031741";
end;

function export:en_32()
	self[32].SH_Trigger = "2057749291039992722";
	self[32].SH_Spawn = "2056344961489579338";
	self[32].SH_Entity = "2056746906123519587";
end;

function export:en_33()
	self[33].SH_Trigger = "2054479072225927733";
	self[33].SH_Spawn = "2054479065231925811";
	self[33].SH_Entity = "2056549121218596225";
end;

function export:en_34()
	self[34].SH_Trigger = "2054470189591829173";
	self[34].SH_Spawn = "2054470178143476403";
	self[34].SH_Entity = "2056673342668145911";
end;

function export:en_35()
	self[35].SH_Trigger = "2054464829338432249";
	self[35].SH_Spawn = "2054464782093791976";
	self[35].SH_Entity = "2056563140438531167";
end;

function export:en_38()
	self[38].SH_Trigger = "2054465008898684900";
	self[38].SH_Spawn = "2054461228818184899";
	self[38].SH_Entity = "2056552397399959166";
end;

function export:en_41()
	self[41].SH_Trigger = "2054479045789229618";
	self[41].SH_Spawn = "2054420496133391717";
	self[41].SH_Entity = "2056549814918730816";
end;

function export:en_42()
	self[42].SH_Trigger = "2054464814454944501";
	self[42].SH_Spawn = "2054464741486637778";
	self[42].SH_Entity = "2056565363069428925";
end;

function export:en_43()
	self[43].SH_Trigger = "2054464822132617975";
	self[43].SH_Spawn = "2054464752869978836";
	self[43].SH_Entity = "2056564872371511735";
end;

function export:en_44()
	self[44].SH_Trigger = "2054481240878242603";
	self[44].SH_Spawn = "2054480914915806344";
	self[44].SH_Entity = "2056748478528247292";
end;

function export:en_45()
	self[45].SH_Trigger = "2054470016358679584";
	self[45].SH_Spawn = "2054470003886916639";
	self[45].SH_Entity = "2056621375721836635";
end;

function export:en_48()
	self[48].SH_Trigger = "2057749195657325454";
	self[48].SH_Spawn = "2054490311962889999";
	self[48].SH_Entity = "2056747840006276884";
end;

function export:en_1()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_1_Out;
end;

function export:en_49()
	self[49].SH_Trigger = "2056634789032655639";
	self[49].SH_Spawn = "2056634836063386933";
	self[49].SH_Entity = "2056634216392716657";
end;

function export:en_50()
	self[50].SH_Trigger = "2054479034428959075";
	self[50].SH_Spawn = "2054479034428959074";
	self[50].SH_Entity = "2056535454118861771";
end;

function export:en_51()
	self[51].SH_Trigger = "2054465002655463393";
	self[51].SH_Spawn = "2054465002653366240";
	self[51].SH_Entity = "2056551427880297324";
end;

function export:en_52()
	self[52].SH_Trigger = "2054478643951836340";
	self[52].SH_Spawn = "2054478639587663026";
	self[52].SH_Entity = "2056539057596401462";
end;

function export:en_53()
	self[53].SH_Trigger = "2057748187973690638";
	self[53].SH_Spawn = "2054468806480239844";
	self[53].SH_Entity = "2056674638057973479";
end;

function export:en_56()
	self[56].SH_Trigger = "2054470227929864890";
	self[56].SH_Spawn = "2054470227929864889";
	self[56].SH_Entity = "2056647786513852446";
end;

function export:en_57()
	self[57].SH_Trigger = "2054479610252371639";
	self[57].SH_Spawn = "2054479610252371638";
	self[57].SH_Entity = "2056579620387443991";
end;

function export:en_58()
	self[58].SH_Trigger = "2057749535288995057";
	self[58].SH_Spawn = "2057749524211838191";
	self[58].SH_Entity = "2056563770450249244";
end;

function export:en_61()
	self[61].SH_Trigger = "2054489414255519186";
	self[61].SH_Spawn = "2054489540043355822";
	self[61].SH_Entity = "2056548750702153509";
end;

function export:en_64()
	self[64].SH_Trigger = "2057748285570950418";
	self[64].SH_Spawn = "2054468737899175132";
	self[64].SH_Entity = "2056636753432819314";
end;

function export:en_67()
	self[67].SH_Trigger = "2057748320410936596";
	self[67].SH_Spawn = "2054468771793345761";
	self[67].SH_Entity = "2056663251065772943";
end;

function export:en_68()
	self[68].SH_Trigger = "2054481584366559770";
	self[68].SH_Spawn = "2054481590110659109";
	self[68].SH_Entity = "2056830206913567122";
end;

function export:en_69()
	self[69].SH_Trigger = "2057747430625001116";
	self[69].SH_Spawn = "2054467594466887375";
	self[69].SH_Entity = "2056717773289054013";
end;

function export:en_72()
	self[72].SH_Trigger = "2054464993421703131";
	self[72].SH_Spawn = "2054464993217009988";
	self[72].SH_Entity = "2056552060763022696";
end;

function export:en_75()
	self[75].SH_Trigger = "2054468852672116665";
	self[75].SH_Spawn = "2054468822577663333";
	self[75].SH_Entity = "2056539858916115082";
end;

function export:en_76()
	self[76].SH_Trigger = "2054479102259241531";
	self[76].SH_Spawn = "2054479096655651385";
	self[76].SH_Entity = "2056552051044797096";
end;

function export:en_77()
	self[77].SH_Trigger = "2054468611487057494";
	self[77].SH_Spawn = "2054467435924301464";
	self[77].SH_Entity = "2056567551812458704";
end;

function export:en_78()
	self[78].SH_Trigger = "2057336720508088695";
	self[78].SH_Spawn = "2054479741976585246";
	self[78].SH_Entity = "2056564699488605649";
end;

function export:en_79()
	self[79].SH_Trigger = "2057355880984249872";
	self[79].SH_Spawn = "2054469859615441782";
	self[79].SH_Entity = "2056745416197693637";
end;

function export:en_80()
	self[80].SH_Trigger = "2054479798861833258";
	self[80].SH_Spawn = "2054479793788822568";
	self[80].SH_Entity = "2056563117231461241";
end;

function export:en_81()
	self[81].SH_Trigger = "2054478993362528608";
	self[81].SH_Spawn = "2054478993362528607";
	self[81].SH_Entity = "2056551278374320821";
end;

function export:en_82()
	self[82].SH_Trigger = "2054467403932247702";
	self[82].SH_Spawn = "2054467398672590484";
	self[82].SH_Entity = "2056563587106757582";
end;

function export:en_83()
	self[83].SH_Trigger = "2054478668576595127";
	self[83].SH_Spawn = "2054478657063230645";
	self[83].SH_Entity = "2056538800426845439";
end;

function export:en_84()
	self[84].SH_Trigger = "2056620585147986120";
	self[84].SH_Spawn = "2056621193997349589";
	self[84].SH_Entity = "2056619013439516274";
end;

function export:en_85()
	self[85].SH_Trigger = "2055957831946875884";
	self[85].SH_Spawn = "2054479536032065200";
	self[85].SH_Entity = "2056579120057307823";
end;

function export:en_86()
	self[86].SH_Trigger = "2054464824741475064";
	self[86].SH_Spawn = "2054464767170458343";
	self[86].SH_Entity = "2056563728156991129";
end;

function export:en_88()
	self[88].SH_Trigger = "2054480818186767484";
	self[88].SH_Spawn = "2054480462948084139";
	self[88].SH_Entity = "2056831727304731221";
end;

function export:en_89()
	self[89].SH_Trigger = "2053871705281011487";
	self[89].SH_Spawn = "2054468937193633729";
	self[89].SH_Entity = "2056542480886721248";
end;

function export:en_90()
	self[90].SH_Trigger = "2054470255421430464";
	self[90].SH_Spawn = "2054470255421430463";
	self[90].SH_Entity = "2056672159138343445";
end;

function export:en_91()
	self[91].SH_Trigger = "2057748888531523226";
	self[91].SH_Spawn = "2054469959657980957";
	self[91].SH_Entity = "2056620654465163886";
end;

function export:en_92()
	self[92].SH_Trigger = "2057746715523432629";
	self[92].SH_Spawn = "2054479086759192933";
	self[92].SH_Entity = "2056538200414906232";
end;

function export:en_93()
	self[93].SH_Trigger = "2054464995627907038";
	self[93].SH_Spawn = "2054464995625809885";
	self[93].SH_Entity = "2056551612083643500";
end;

function export:en_94()
	self[94].SH_Trigger = "2054464817906856694";
	self[94].SH_Spawn = "2054464749554381523";
	self[94].SH_Entity = "2056563372844916107";
end;

function export:en_95()
	self[95].SH_Trigger = "2054482759899947562";
	self[95].SH_Spawn = "2054482724906869268";
	self[95].SH_Entity = "2056831458999297212";
end;

function export:en_96()
	self[96].SH_Trigger = "2053869521636168599";
	self[96].SH_Spawn = "2054489398554142160";
	self[96].SH_Entity = "2056547748265618449";
end;

function export:en_99()
	self[99].SH_Trigger = "2057351810911341614";
	self[99].SH_Spawn = "2054469631127444566";
	self[99].SH_Entity = "2056621873856280018";
end;

function export:en_100()
	self[100].SH_Trigger = "2057337201437473111";
	self[100].SH_Spawn = "2054470204179618486";
	self[100].SH_Entity = "2056662448844309551";
end;

function export:en_101()
	self[101].SH_Trigger = "2054479090418721336";
	self[101].SH_Spawn = "2054479086348149302";
	self[101].SH_Entity = "2056551119391310843";
end;

function export:en_104()
	self[104].SH_Trigger = "2057746259713733167";
	self[104].SH_Spawn = "2054479648556852921";
	self[104].SH_Entity = "2056578823637455235";
end;

function export:en_105()
	self[105].SH_Trigger = "2057748247769785616";
	self[105].SH_Spawn = "2054468746331823326";
	self[105].SH_Entity = "2056664851935141930";
end;

function export:en_106()
	self[106].SH_Trigger = "2054479809764926509";
	self[106].SH_Spawn = "2054479807252538411";
	self[106].SH_Entity = "2056563701984548031";
end;

function export:en_107()
	self[107].SH_Trigger = "2054464989984471000";
	self[107].SH_Spawn = "2054464989984470999";
	self[107].SH_Entity = "2056562040142604003";
end;

function export:en_108()
	self[108].BarkMissionTag = self.BarkDataTag;
	self[108].Pawn = self.SpawnedBuddyEntityID;
	self[108].WaitLoopA = "Safehouse_Interactable";
	self[108].BecknIdleLoop_ = "Safehouse_Interactable";
	self[108].GreetIdleLoop = "Safehouse_Interactable";
	self[108].BecknBark_ = "BECKN";
	self[108].GreetBark = "GREET";
	self[108].ExitBark_ = "EXITA";
	self[108].ExitRadius_ = 4;
	self[108].BecknRadius_ = 3;
	self[108].GreetRadius_ = 2;
	self[108].BTriggerFilter1_ = self.FilterTrigger;
	self[108].GTriggerFilter1_ = self.FilterTrigger;
end;

function export:en_3()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_3_Out;
end;

function export:en_5()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_5_Out;
end;

function export:en_115()
	self[115].Trigger = self.CurrentTriggerID;
end;

function export:en_124()
	self[124].Seconds = 1;
end;

function export:en_125()
	self[125].Trigger = self.CurrentTriggerID;
end;

function export:en_15()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_15_Out;
end;

function export:en_18()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.Prepped;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_18_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
end;

function export:en_21()
	Boxes[PathID("Domino/System/RemoveBuddy.lua")].Buddy = self.SpawnedBuddyEntityID;
	Boxes[PathID("Domino/System/RemoveBuddy.lua")].Instant = 1;
	Boxes[PathID("Domino/System/RemoveBuddy.lua")]._graph = self;
	Boxes[PathID("Domino/System/RemoveBuddy.lua")].Out = self._type.f_21_Out;
end;

function export:en_114()
	self[114].BarkMissionTag = self.BarkDataTag;
	self[114].Pawn = self.SpawnedBuddyEntityID;
	self[114].IdleLoop = "Safehouse_Interactable";
	self[114].DialogBark = "DIALA";
	self[114].PreDialogExitBark_ = "EXITA";
	self[114].DialogExitBark_ = "EXITA";
	self[114].GreetRadius_ = 2;
	self[114].TriggerFilter1_ = self.FilterTrigger;
end;

function export:en_118()
	self[118].BarkMissionTag = self.BarkDataTag;
	self[118].Pawn = self.SpawnedBuddyEntityID;
	self[118].IdleLoop = "Safehouse_Interactable";
	self[118].DialogBark = "DIALB";
	self[118].PreDialogExitBark_ = "EXITB";
	self[118].DialogExitBark_ = "EXITB";
	self[118].GreetRadius_ = 2;
	self[118].TriggerFilter1_ = self.FilterTrigger;
	self[118].OnceOnly_ = 1;
end;

function export:en_120()
	self[120].GreetRadius = 2;
	self[120].Pawn = self.SpawnedBuddyEntityID;
	self[120].SecondaryBuddy = self.BuddyName;
	self[120].FilterTrigger_ = self.FilterTrigger;
	self[120].IdleAnim = "Safehouse_NotInteractable";
end;

function export:en_119()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_119_Out;
end;

function export:ex_132()
	self.SpawnedBuddyEntityID = self[132].SpawnedBuddy;
end;

-- Empty out anchor definitions
_compilerVersion = 3;
