-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\SideMissions\Assassination_Missions.domino.xml
-- User graph: AssassinationCellTowerInteracted
-- 
-- Generated on 09/10/2008 21:05:07
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 


export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/System/PopUpConfirmationMessageBox.lua");
	cbox:RegisterBox("Domino/System/SimpleNode.lua");
	cbox:RegisterBox("Domino/System/PhoneCall.lua");
	cbox:RegisterBox("Domino/System/CompareStrings.lua");
	cbox:RegisterBox("Domino/System/CompareBoolean.lua");
	cbox:RegisterBox("Domino/System/LogToConsole.lua");
	cbox:RegisterBox("Domino/System/PickupListener.lua");
	cbox:RegisterBox("Domino/System/GameElementObjective.lua");
	cbox:RegisterBox("Domino/System/PickupState.lua");
	
	-- Load resources
	cbox:LoadResource("sndres0x004ef967", "CSoundResource");
end;

function export:Init(cbox)
	self.World1Output = DummyFunction;
	self.World2Output = DummyFunction;
	self[53] = cbox:CreateBox("Domino/System/PhoneCall.lua");
	self[53]._graph = self;
	self[53].Out = self._type.f_53_Out;
	self[53].CallTimeout = DummyFunction;
	self[53].CallPicked = DummyFunction;
	self[53].HangUpCall = DummyFunction;
	self[53].VoiceFinished = DummyFunction;
	self[55] = cbox:CreateBox("Domino/System/PhoneCall.lua");
	self[55]._graph = self;
	self[55].Out = self._type.f_55_Out;
	self[55].CallTimeout = DummyFunction;
	self[55].CallPicked = DummyFunction;
	self[55].HangUpCall = DummyFunction;
	self[55].VoiceFinished = DummyFunction;
	self[30] = cbox:CreateBox("Domino/System/PickupListener.lua");
	self[30]._graph = self;
	self[30].PickedUp = self._type.f_30_PickedUp;
	self[34] = cbox:CreateBox("Domino/System/PickupListener.lua");
	self[34]._graph = self;
	self[34].PickedUp = self._type.f_34_PickedUp;
	self[32] = cbox:CreateBox("Domino/System/PickupListener.lua");
	self[32]._graph = self;
	self[32].PickedUp = self._type.f_32_PickedUp;
	self[45] = cbox:CreateBox("Domino/System/PickupListener.lua");
	self[45]._graph = self;
	self[45].PickedUp = self._type.f_45_PickedUp;
	self[48] = cbox:CreateBox("Domino/System/PopUpConfirmationMessageBox.lua");
	self[48]._graph = self;
	self[48].Yes = self._type.f_48_Yes;
	self[48].No = self._type.f_48_No;
	self[36] = cbox:CreateBox("Domino/System/PickupListener.lua");
	self[36]._graph = self;
	self[36].PickedUp = self._type.f_36_PickedUp;
	self[43] = cbox:CreateBox("Domino/System/PickupListener.lua");
	self[43]._graph = self;
	self[43].PickedUp = self._type.f_43_PickedUp;
	self[41] = cbox:CreateBox("Domino/System/PickupListener.lua");
	self[41]._graph = self;
	self[41].PickedUp = self._type.f_41_PickedUp;
	self[50] = cbox:CreateBox("Domino/System/PopUpConfirmationMessageBox.lua");
	self[50]._graph = self;
	self[50].Yes = self._type.f_50_Yes;
	self[50].No = self._type.f_50_No;
	self[47] = cbox:CreateBox("Domino/System/PickupListener.lua");
	self[47]._graph = self;
	self[47].PickedUp = self._type.f_47_PickedUp;
end;

function export:ShutDown()
	self[53]._type.ShutDown(self[53]);
	self[55]._type.ShutDown(self[55]);
	self[30]._type.ShutDown(self[30]);
	self[34]._type.ShutDown(self[34]);
	self[32]._type.ShutDown(self[32]);
	self[45]._type.ShutDown(self[45]);
	self[48]._type.ShutDown(self[48]);
	self[36]._type.ShutDown(self[36]);
	self[43]._type.ShutDown(self[43]);
	self[41]._type.ShutDown(self[41]);
	self[50]._type.ShutDown(self[50]);
	self[47]._type.ShutDown(self[47]);
end;

function export:World1Input()
	self._type.en_0(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:World2Input()
	self._type.en_13(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_0_A_is_True()
	self = self._graph;
	self:World1Output();
end;

function export:f_1_Out()
	self = self._graph;
	self[30].Pickup = "2056051824053472409";
	self[30]._type.Enable(self[30]);
end;

function export:f_2_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "EnableCellTower2";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_1_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_3_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PickupState.lua")].Pickup = "2056051824053472409";
	Boxes[PathID("Domino/System/PickupState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PickupState.lua")].Out = self._type.f_2_Out;
	Boxes[PathID("Domino/System/PickupState.lua")]._type.SetAsPickable(Boxes[PathID("Domino/System/PickupState.lua")]);
end;

function export:f_4_Out()
	self = self._graph;
	self[32].Pickup = "2056051768531374078";
	self[32]._type.Enable(self[32]);
end;

function export:f_5_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "EnableCellTower4";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_4_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_6_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PickupState.lua")].Pickup = "2056051768531374078";
	Boxes[PathID("Domino/System/PickupState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PickupState.lua")].Out = self._type.f_5_Out;
	Boxes[PathID("Domino/System/PickupState.lua")]._type.SetAsPickable(Boxes[PathID("Domino/System/PickupState.lua")]);
end;

function export:f_7_Out()
	self = self._graph;
	self[34].Pickup = "2056041842205541385";
	self[34]._type.Enable(self[34]);
end;

function export:f_8_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "EnableCellTower3";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_7_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_9_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PickupState.lua")].Pickup = "2056041842205541385";
	Boxes[PathID("Domino/System/PickupState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PickupState.lua")].Out = self._type.f_8_Out;
	Boxes[PathID("Domino/System/PickupState.lua")]._type.SetAsPickable(Boxes[PathID("Domino/System/PickupState.lua")]);
end;

function export:f_10_Out()
	self = self._graph;
	self[36].Pickup = "2056051935372395699";
	self[36]._type.Enable(self[36]);
end;

function export:f_11_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "EnableCellTower1";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_10_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_12_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PickupState.lua")].Pickup = "2056051935372395699";
	Boxes[PathID("Domino/System/PickupState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PickupState.lua")].Out = self._type.f_11_Out;
	Boxes[PathID("Domino/System/PickupState.lua")]._type.SetAsPickable(Boxes[PathID("Domino/System/PickupState.lua")]);
end;

function export:f_0_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = "2056051840025382043";
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_3_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = "2056051736631590208";
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_6_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = "2056041868120048651";
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_9_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = "2056051933111665839";
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_12_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_13_A_is_True()
	self = self._graph;
	self:World2Output();
end;

function export:f_14_Out()
	self = self._graph;
	self[41].Pickup = "2056084748998031660";
	self[41]._type.Enable(self[41]);
end;

function export:f_15_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "W2 EnableCellTower4";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_14_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_16_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PickupState.lua")].Pickup = "2056084748998031660";
	Boxes[PathID("Domino/System/PickupState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PickupState.lua")].Out = self._type.f_15_Out;
	Boxes[PathID("Domino/System/PickupState.lua")]._type.SetAsPickable(Boxes[PathID("Domino/System/PickupState.lua")]);
end;

function export:f_17_Out()
	self = self._graph;
	self[43].Pickup = "2056042119778294003";
	self[43]._type.Enable(self[43]);
end;

function export:f_18_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "W2 EnableCellTower3";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_17_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_19_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PickupState.lua")].Pickup = "2056042119778294003";
	Boxes[PathID("Domino/System/PickupState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PickupState.lua")].Out = self._type.f_18_Out;
	Boxes[PathID("Domino/System/PickupState.lua")]._type.SetAsPickable(Boxes[PathID("Domino/System/PickupState.lua")]);
end;

function export:f_20_Out()
	self = self._graph;
	self[45].Pickup = "2056054589421016574";
	self[45]._type.Enable(self[45]);
end;

function export:f_21_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "W2 EnableCellTower1";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_20_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_22_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PickupState.lua")].Pickup = "2056054589421016574";
	Boxes[PathID("Domino/System/PickupState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PickupState.lua")].Out = self._type.f_21_Out;
	Boxes[PathID("Domino/System/PickupState.lua")]._type.SetAsPickable(Boxes[PathID("Domino/System/PickupState.lua")]);
end;

function export:f_23_Out()
	self = self._graph;
	self[47].Pickup = "2056052628047021422";
	self[47]._type.Enable(self[47]);
end;

function export:f_24_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "W2 EnableCellTower2";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_23_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_25_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/PickupState.lua")].Pickup = "2056052628047021422";
	Boxes[PathID("Domino/System/PickupState.lua")]._graph = self;
	Boxes[PathID("Domino/System/PickupState.lua")].Out = self._type.f_24_Out;
	Boxes[PathID("Domino/System/PickupState.lua")]._type.SetAsPickable(Boxes[PathID("Domino/System/PickupState.lua")]);
end;

function export:f_13_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = "2056084736752756120";
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_16_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = "2056042112599742703";
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_19_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = "2056054603989931520";
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_22_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = "2056052555487654576";
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_25_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_26_Out()
	self = self._graph;
	self[53].PhonecallSound = "0x004ef967";
	self[53]._type.In(self[53]);
end;

function export:f_27_A_eq_B()
	self = self._graph;
	self._type.en_26(self);
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_27_A_neq_B()
	self = self._graph;
	self[48].TitleLocId = "SQ_CANCEL";
	self[48].TextLocId = "SQ_CANCEL";
	self[48]._type.In(self[48]);
end;

function export:f_28_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "none";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = self._type.f_27_A_eq_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = self._type.f_27_A_eq_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_29_Out()
	self = self._graph;
	self._type.en_28(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_30_PickedUp()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "EnterCellTower2";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_29_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_31_Out()
	self = self._graph;
	self._type.en_28(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_32_PickedUp()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "EnterCellTower4";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_31_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_33_Out()
	self = self._graph;
	self._type.en_28(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_34_PickedUp()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "EnterCellTower3";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_33_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_35_Out()
	self = self._graph;
	self._type.en_28(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_36_PickedUp()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "EnterCellTower1";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_35_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_37_Out()
	self = self._graph;
	self[55].PhonecallSound = "0x004ef967";
	self[55]._type.In(self[55]);
end;

function export:f_38_A_eq_B()
	self = self._graph;
	self._type.en_37(self);
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_38_A_neq_B()
	self = self._graph;
	self[50].TitleLocId = "SQ_CANCEL";
	self[50].TextLocId = "SQ_CANCEL";
	self[50]._type.In(self[50]);
end;

function export:f_39_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "none";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = self._type.f_38_A_eq_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = self._type.f_38_A_eq_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_40_Out()
	self = self._graph;
	self._type.en_39(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_41_PickedUp()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "W2 UseCellTower4";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_40_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_42_Out()
	self = self._graph;
	self._type.en_39(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_43_PickedUp()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "W2 UseCellTower3";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_42_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_44_Out()
	self = self._graph;
	self._type.en_39(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_45_PickedUp()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "W2 UseCellTower1";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_44_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_46_Out()
	self = self._graph;
	self._type.en_39(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_47_PickedUp()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "W2 UseCellTower2";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_46_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_48_Yes()
	self = self._graph;
	self._type.en_26(self);
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_49_Out()
	self = self._graph;
	self._type.en_0(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_48_No()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_49_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_50_Yes()
	self = self._graph;
	self._type.en_37(self);
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_51_Out()
	self = self._graph;
	self._type.en_13(self);
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_50_No()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_51_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_52_Out()
	self = self._graph;
	self:World1Output();
end;

function export:f_53_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Recieved Phone Call";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_52_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_54_Out()
	self = self._graph;
	self:World2Output();
end;

function export:f_55_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Recieved Phone Call";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_54_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:en_0()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.AM_Active;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_0_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_0_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
end;

function export:en_13()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.AM_Active;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_13_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_13_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
end;

function export:en_26()
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Cell Tower Activated";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_26_Out;
end;

function export:en_28()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_28_Out;
end;

function export:en_37()
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Cell Tower Activated";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_37_Out;
end;

function export:en_39()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_39_Out;
end;

-- Empty out anchor definitions
function export:World1Output()
	
end;
function export:World2Output()
	
end;
_compilerVersion = 3;
