-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\SideMissions\ConvoyMissions.domino.xml
-- User graph: Convoy_Missions
-- 
-- Generated on 09/23/2008 15:09:25
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 


export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/System/SetBoolean.lua");
	cbox:RegisterBox("Domino/System/OnceOnly.lua");
	cbox:RegisterBox("Domino/System/ObjectiveState.lua");
	cbox:RegisterBox("Domino/System/OutputOrder.lua");
	cbox:RegisterBox("Domino/User/Common_CustomBoxes.MissionCompleteBroadcast.lua");
	cbox:RegisterBox("Domino/System/CompareBoolean.lua");
	cbox:RegisterBox("Domino/System/IntegerArithmetics.lua");
	cbox:RegisterBox("Domino/User/SideMissions/ConvoyMissions.SelectRandomMission.lua");
	cbox:RegisterBox("Domino/System/SimpleNode.lua");
	cbox:RegisterBox("Domino/User/SideMissions/ConvoyMissions.Convoy_PawnBriefing.lua");
	cbox:RegisterBox("Domino/System/SetInteger.lua");
	cbox:RegisterBox("Domino/System/ConvoyMission.lua");
	cbox:RegisterBox("Domino/System/ConsoleCommand.lua");
	cbox:RegisterBox("Domino/System/SetMissionState.lua");
	cbox:RegisterBox("Domino/System/SetEntity.lua");
	cbox:RegisterBox("Domino/User/Common_CustomBoxes.MissionAcceptedBroadcast.lua");
	cbox:RegisterBox("Domino/User/SideMissions/ConvoyMissions.UnlockWeapons.lua");
	cbox:RegisterBox("Domino/System/LogToConsole.lua");
	cbox:RegisterBox("Domino/System/GameElementObjective.lua");
	cbox:RegisterBox("Domino/System/IndexList.lua");
end;

function export:Init(cbox)
	self.Accepted = DummyFunction;
	self.Failed = DummyFunction;
	self.Finished = DummyFunction;
	self.Success = DummyFunction;
	self.AllMissionsFinished = 0;
	self.ConvoyMission_ID = nil;
	self.CurrentMission = 0;
	self.CurrentWorld = 0;
	self.DisableLayer = "";
	self.IsLastConvoyMission = 0;
	self.MerchantMarker_1 = nil;
	self.MerchantMarker_2 = nil;
	self.MerchantMarker_3 = nil;
	self.MerchantMarker_4 = nil;
	self.MerchantMarker_5 = nil;
	self.MissionID = "";
	self.MissionLayer = "";
	self.MissionTag = "";
	self.ObjectiveState = "";
	self.Paused = 0;
	self[62] = cbox:CreateBox("Domino/User/SideMissions/ConvoyMissions.UnlockWeapons.lua");
	self[62]._graph = self;
	self[62].Out = self._type.f_62_Out;
	self[88] = cbox:CreateBox("Domino/System/IntegerArithmetics.lua");
	self[88]._graph = self;
	self[88].Out = self._type.f_88_Out;
	self[65] = cbox:CreateBox("Domino/User/Common_CustomBoxes.MissionCompleteBroadcast.lua");
	self[65]._graph = self;
	-- FIX: If a enemy AI destroys the convoy truck, the mission is still completed
	self[65].BroadcastSent = self._type.f_85_BroadcastSent;
	self[32] = cbox:CreateBox("Domino/System/ConsoleCommand.lua");
	self[32]._graph = self;
	self[32].Out = self._type.f_32_Out;
	self[48] = cbox:CreateBox("Domino/System/IndexList.lua");
	self[48]._graph = self;
	self[48]._DynamicAnchors = {
		Output = 3,
	};
	self[48].Output[0] = self._type.f_48_Output_0;
	self[48].Output[1] = self._type.f_48_Output_1;
	self[48].Output[2] = self._type.f_48_Output_2;
	self[34] = cbox:CreateBox("Domino/User/SideMissions/ConvoyMissions.Convoy_PawnBriefing.lua");
	self[34]._graph = self;
	self[34].Accepted = self._type.f_34_Accepted;
	self[34].Finished = self._type.f_34_Finished;
	self[85] = cbox:CreateBox("Domino/User/Common_CustomBoxes.MissionCompleteBroadcast.lua");
	self[85]._graph = self;
	self[85].BroadcastSent = self._type.f_85_BroadcastSent;
	self[87] = cbox:CreateBox("Domino/System/OnceOnly.lua");
	self[87]._graph = self;
	self[87].Out = self._type.f_87_Out;
	self[68] = cbox:CreateBox("Domino/User/Common_CustomBoxes.MissionAcceptedBroadcast.lua");
	self[68]._graph = self;
	self[68].BroadcastSent = self._type.f_68_BroadcastSent;
	self[33] = cbox:CreateBox("Domino/System/ConvoyMission.lua");
	self[33]._graph = self;
	self[33].Success = self._type.f_33_Success;
	self[33].Failure = self._type.f_33_Failure;
	self[25] = cbox:CreateBox("Domino/System/OnceOnly.lua");
	self[25]._graph = self;
	self[25].Out = self._type.f_25_Out;
	self[66] = cbox:CreateBox("Domino/User/SideMissions/ConvoyMissions.SelectRandomMission.lua");
	self[66]._graph = self;
	self[66].Out = self._type.f_66_Out;
end;

function export:ShutDown()
	self[62]._type.ShutDown(self[62]);
	self[88]._type.ShutDown(self[88]);
	self[65]._type.ShutDown(self[65]);
	self[32]._type.ShutDown(self[32]);
	self[48]._type.ShutDown(self[48]);
	self[34]._type.ShutDown(self[34]);
	self[85]._type.ShutDown(self[85]);
	self[87]._type.ShutDown(self[87]);
	self[68]._type.ShutDown(self[68]);
	self[33]._type.ShutDown(self[33]);
	self[25]._type.ShutDown(self[25]);
	self[66]._type.ShutDown(self[66]);
end;

function export:Start()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.AllMissionsFinished;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_0_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:Interrupt()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.AllMissionsFinished;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:Resume()
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.AllMissionsFinished;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = DummyFunction;
	-- Prevent the game from initializing a convoy mission that is already active
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:Prep()
	self[25]._type.In(self[25]);
end;

function export:Stop()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_23_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_3_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_5;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_4_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_4;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_3_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_5_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_3;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_4_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_6_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_2;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_5_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_7_Out()
	self = self._graph;
	self.CurrentMission = Boxes[PathID("Domino/System/SetInteger.lua")].Target;
	self[66].World = self.CurrentWorld;
	self[66]._type.In(self[66]);
end;

function export:f_8_Out()
	self = self._graph;
	self._type.en_6(self);
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
	Boxes[PathID("Domino/System/SetInteger.lua")].Integer = 0;
	Boxes[PathID("Domino/System/SetInteger.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetInteger.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetInteger.lua")].Out = self._type.f_7_Out;
	Boxes[PathID("Domino/System/SetInteger.lua")]._type.FromInteger(Boxes[PathID("Domino/System/SetInteger.lua")]);
end;

function export:f_9_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Convoy Missions Started";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
	self._type.en_8(self);
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
	self[32].Command = "convoy_accept";
	self[32]._type.In(self[32]);
end;

function export:f_0_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_9_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_12_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_5;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_13_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_4;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_12_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_14_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_3;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_13_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_15_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_2;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_14_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_16_Out()
	self = self._graph;
	self._type.en_15(self);
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_17_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = self.MissionLayer;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_16_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Disable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_18_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = self.DisableLayer;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_17_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_19_Out()
	self = self._graph;
	self._type.en_33(self);
	self[33]._type.Cancel(self[33]);
	self._type.en_18(self);
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Disable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
	self._type.en_34(self);
	self[34]._type.Cancel(self[34]);
end;

function export:f_10_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_19_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_21_Out()
	self = self._graph;
	self._type.en_6(self);
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Available(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
	self._type.en_34(self);
	self[34]._type.Start(self[34]);
end;

function export:f_20_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_21_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_22_Out()
	self = self._graph;
	self._type.en_34(self);
	self[34]._type.Cancel(self[34]);
	self._type.en_33(self);
	self[33]._type.Cancel(self[33]);
	self._type.en_18(self);
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Off(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_23_Out()
	self = self._graph;
	self.AllMissionsFinished = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_22_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_24_Out()
	self = self._graph;
	self.CurrentWorld = Boxes[PathID("Domino/System/SetInteger.lua")].Target;
	self[48].Index = self.CurrentWorld;
	self[48]._type.In(self[48]);
end;

function export:f_25_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetInteger.lua")].Integer = self.World;
	Boxes[PathID("Domino/System/SetInteger.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetInteger.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetInteger.lua")].Out = self._type.f_24_Out;
	Boxes[PathID("Domino/System/SetInteger.lua")]._type.FromInteger(Boxes[PathID("Domino/System/SetInteger.lua")]);
end;

function export:f_26_Out_0()
	self = self._graph;
	self[68].MissionID = self.MissionID;
	self[68].MissionType = "CM";
	self[68]._type.SideMission_Accepted(self[68]);
end;

function export:f_27_Out()
	self = self._graph;
	self._type.en_33(self);
	self[33]._type.Start(self[33]);
	self._type.en_15(self);
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_28_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/ObjectiveState.lua")].ObjectiveState = self.ObjectiveState;
	Boxes[PathID("Domino/System/ObjectiveState.lua")].ShowPopup = nil;
	Boxes[PathID("Domino/System/ObjectiveState.lua")]._graph = self;
	Boxes[PathID("Domino/System/ObjectiveState.lua")].Out = self._type.f_27_Out;
	Boxes[PathID("Domino/System/ObjectiveState.lua")]._type.Set(Boxes[PathID("Domino/System/ObjectiveState.lua")]);
end;

function export:f_29_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = self.MissionLayer;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_28_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_30_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = self.DisableLayer;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_29_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Disable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_26_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/ConvoyMissions/ArmsMerchant";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_30_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Disable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_31_Out()
	self = self._graph;
	self._type.en_26(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_32_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_31_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
	self._type.en_34(self);
	self[34]._type.Cancel(self[34]);
end;

function export:f_33_Success()
	self = self._graph;
	self[62].World = self.CurrentWorld;
	self[62]._type.In(self[62]);
end;

function export:f_33_Failure()
	self = self._graph;
	self[65].ShowPopup = 0;
	self[65].SideMissionType = "CM";
	self[65]._type.SideMission_Complete(self[65]);
end;

function export:f_34_Accepted()
	self = self._graph;
	self._type.en_26(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_35_Out()
	self = self._graph;
	self._type.en_34(self);
	self[34]._type.Cancel(self[34]);
end;

function export:f_34_Finished()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_35_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_37_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_5;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_38_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_4;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_37_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_39_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_3;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_38_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_40_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_2;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_39_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_41_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_1;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_40_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_42_Out()
	self = self._graph;
	self._type.en_41(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_43_Out()
	self = self._graph;
	self.MerchantMarker_5 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_42_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_44_Out()
	self = self._graph;
	self.MerchantMarker_4 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056068541666308064";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_43_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_45_Out()
	self = self._graph;
	self.MerchantMarker_3 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056084066859499705";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_44_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_46_Out()
	self = self._graph;
	self.MerchantMarker_2 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056099714163561456";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_45_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_47_Out()
	self = self._graph;
	self.MerchantMarker_1 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056079361659924512";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_46_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_48_Output_0()
	self = self._graph;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056078503794723290";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_47_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_49_Out()
	self = self._graph;
	self._type.en_41(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_50_Out()
	self = self._graph;
	self.MerchantMarker_5 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_49_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_51_Out()
	self = self._graph;
	self.MerchantMarker_4 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056178491822445886";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_50_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_52_Out()
	self = self._graph;
	self.MerchantMarker_3 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056770170667423783";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_51_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_53_Out()
	self = self._graph;
	self.MerchantMarker_2 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056757858518702518";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_52_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_54_Out()
	self = self._graph;
	self.MerchantMarker_1 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056093314630826866";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_53_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_48_Output_1()
	self = self._graph;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056525831972339862";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_54_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_55_Out()
	self = self._graph;
	self._type.en_41(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_56_Out()
	self = self._graph;
	self.MerchantMarker_5 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_55_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_57_Out()
	self = self._graph;
	self.MerchantMarker_4 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = nil;
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_56_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_58_Out()
	self = self._graph;
	self.MerchantMarker_3 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056487892806533800";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_57_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_59_Out()
	self = self._graph;
	self.MerchantMarker_2 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056487892458406486";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_58_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_60_Out()
	self = self._graph;
	self.MerchantMarker_1 = Boxes[PathID("Domino/System/SetEntity.lua")].Target;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056487891403538948";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_59_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_48_Output_2()
	self = self._graph;
	Boxes[PathID("Domino/System/SetEntity.lua")].Entity = "2056485996305842514";
	Boxes[PathID("Domino/System/SetEntity.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetEntity.lua")].Out = self._type.f_60_Out;
	Boxes[PathID("Domino/System/SetEntity.lua")]._type.FromEntity(Boxes[PathID("Domino/System/SetEntity.lua")]);
end;

function export:f_61_Out_0()
	self = self._graph;
	self:Success();
end;

function export:f_61_Out_1()
	self = self._graph;
	self[85].SideMissionType = "CM";
	self[85]._type.SideMission_Complete(self[85]);
end;

function export:f_62_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_61_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_61_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_63_Out()
	self = self._graph;
	self:Failed();
end;

function export:f_64_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = self.DisableLayer;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_63_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_65_BroadcastSent()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = self.MissionLayer;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_64_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Disable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_66_Out()
	self = self._graph;
	self.CurrentMission = self[66].CurrentMission;
	self.ObjectiveState = self[66].ObjectiveState;
	self.MissionTag = self[66].MissionTag;
	self.MissionLayer = self[66].MissionLayer;
	self.ConvoyMission_ID = self[66].ConvoyMission;
	self.DisableLayer = self[66].DisableLayer;
	self.IsLastConvoyMission = self[66].IsLastConvoyMission;
	self.MissionID = self[66].MissionID;
	self._type.en_34(self);
	self[34]._type.Start(self[34]);
end;

function export:f_67_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.ConvoyMissionAccepted = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self:Accepted();
end;

function export:f_68_BroadcastSent()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_67_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_70_Out_0()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Convoy Mission Succeeded";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_71_Out_0()
	self = self._graph;
	self._type.en_34(self);
	self[34]._type.Unload(self[34]);
end;

function export:f_72_Out()
	self = self._graph;
	self.AllMissionsFinished = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self:Finished();
end;

function export:f_71_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_72_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_73_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_71_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_71_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_74_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_5;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_73_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_75_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_4;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_74_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_76_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_3;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_75_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_77_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_2;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_76_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_78_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_1;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_77_Out;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_79_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/ConvoyMissions/ArmsMerchant";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_78_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Off(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_80_Out()
	self = self._graph;
	self._type.en_8(self);
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_79_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_80_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_70_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.IsLastConvoyMission;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;

	-- Update 2.7: Fix convoy missions ending before player is able to complete all of them
	local worldChk = CGameMissionMgr_GetInstance():GetMission("Missions/StoryMissions/A1SM01/A1SM01_StreetFighting");
	if (worldChk ~= nil) then
		-- World1
		if (Globals.MASTER_GameGlobals.ConvoyMissionsAccepted_W1 >= 4) then
			Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_79_A_is_True;
			Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_79_A_is_True;
		else
			Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_79_A_is_False;
			Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_79_A_is_False;
		end
	else
		-- World2
		-- Update 3.2: Secondary fix for the same bug
		if (Globals.MASTER_GameGlobals.ConvoyMissionsAccepted_W2 >= 4) and (Globals.MASTER_GameGlobals.FinalConvoyMissionCompleted == 1) then
			Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_79_A_is_True;
			Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_79_A_is_True;
		else
			Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_79_A_is_False;
			Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_79_A_is_False;
		end
	end

	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_81_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_70_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_70_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_82_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = self.DisableLayer;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_81_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Enable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_83_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = self.MissionLayer;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_82_Out;
	Boxes[PathID("Domino/System/SetMissionState.lua")]._type.Disable(Boxes[PathID("Domino/System/SetMissionState.lua")]);
end;

function export:f_84_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.ConvoyMissionAccepted = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_83_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_85_BroadcastSent()
	self = self._graph;
	self[87]._type.In(self[87]);
	self[88].A = Globals.MASTER_GameGlobals.MissionCounterConvoy;
	self[88].B = 1;
	self[88]._type.Add(self[88]);
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_84_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_86_Out()
	self = self._graph;
	self._type.en_34(self);
	self[34]._type.FirstMissionAccepted(self[34]);
end;

function export:f_87_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_86_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_88_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.MissionCounterConvoy = self[88].Target;
end;

function export:en_6()
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_1;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_6_Out;
end;

function export:en_8()
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/ConvoyMissions/ArmsMerchant";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_8_Out;
end;

function export:en_33()
	self[33].ConvoyEntity = self.ConvoyMission_ID;
end;

function export:en_15()
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.MerchantMarker_1;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = self._type.f_15_Out;
end;

function export:en_18()
	Boxes[PathID("Domino/System/SetMissionState.lua")].Mission = "Missions/ConvoyMissions/ArmsMerchant";
	Boxes[PathID("Domino/System/SetMissionState.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetMissionState.lua")].Out = self._type.f_18_Out;
end;

function export:en_34()
	self[34].MissionTag = self.MissionTag;
	self[34].World = self.CurrentWorld;
end;

function export:en_26()
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_26_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_26_Out_1;
end;

function export:en_41()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_41_Out;
end;

-- Empty out anchor definitions
function export:Accepted()
	
end;
function export:Failed()
	
end;
function export:Finished()
	
end;
function export:Success()
	
end;
_compilerVersion = 3;
