-- {\v/} Domino auto-generated LUA script file
-- 
-- Generated by BlackBox 2.1.2.9
-- Plugin: Domino 1.0.1.0
-- Platform: Nomad LUA 1.1.1.4
-- 
-- Script document: R:\main\data\Domino\User\SideMissions\SideMissions.domino.xml
-- User graph: MikesPlace_BSQmanager_W1
-- 
-- Generated on 09/11/2008 01:48:07
-- 
-- DO NOT EDIT MANUALLY THIS FILE OR YOUR CHANGES WILL BE LOST!
-- Please modify the original Domino script instead. You have been warned.
-- 


export = {
};


function export:LuaDependencies()
	return {
	};
end;

function export:Create(cbox)
	-- External box dependencies
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.MikesPlace_ObjectivePoint.lua");
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.MikesPlace_IfBuddy_Spawned.lua");
	cbox:RegisterBox("Domino/User/Common_CustomBoxes.MissionAcceptedListener.lua");
	cbox:RegisterBox("Domino/User/Common_CustomBoxes.MissionCompleteListener.lua");
	cbox:RegisterBox("Domino/System/Door.lua");
	cbox:RegisterBox("Domino/User/BSQ08_ThePrototype.BSQ08_Mission.lua");
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.MikesPlace_PawnbriefSelection_Timer.lua");
	cbox:RegisterBox("Domino/User/BSQ06_HarshDefault.BSQ06_Mission.lua");
	cbox:RegisterBox("Domino/User/BSQ12_LemonBeater.BSQ12_Mission.lua");
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.MikesPlace_NewSecondaryBuddy_Spawned.lua");
	cbox:RegisterBox("Domino/System/TestIfNil.lua");
	cbox:RegisterBox("Domino/System/CompareIntegers.lua");
	cbox:RegisterBox("Domino/System/SetString.lua");
	cbox:RegisterBox("Domino/System/SetBoolean.lua");
	cbox:RegisterBox("Domino/User/BSQ10_AgentYellow.BSQ10_Mission.lua");
	cbox:RegisterBox("Domino/User/BSQ02_LostInTheGY.BSQ02_Mission.lua");
	cbox:RegisterBox("Domino/User/BSQ07_GreenFingers.BSQ07_Mission.lua");
	cbox:RegisterBox("Domino/User/BSQ04_BurnTheWater.BSQ04_Mission.lua");
	cbox:RegisterBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	cbox:RegisterBox("Domino/System/ProximityTrigger.lua");
	cbox:RegisterBox("Domino/System/SimpleNode.lua");
	cbox:RegisterBox("Domino/User/BSQ13_Dreadlock.BSQ13_Mission.lua");
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.MikesPlace_BSQmission_and_Pawnbrief_Selection.lua");
	cbox:RegisterBox("Domino/User/BSQ15_Brewery.BSQ15_Mission.lua");
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.MikesPlace_WaitForLoadedBuddy.lua");
	cbox:RegisterBox("Domino/User/BSQ03_HiddenArmory.BSQ03_Mission.lua");
	cbox:RegisterBox("Domino/System/GameElementObjective.lua");
	cbox:RegisterBox("Domino/System/Delay.lua");
	cbox:RegisterBox("Domino/System/CompareBoolean.lua");
	cbox:RegisterBox("Domino/System/TextToScreen.lua");
	cbox:RegisterBox("Domino/System/OutputOrder.lua");
	cbox:RegisterBox("Domino/User/BSQ09_JunkMedicine.BSQ09_Mission.lua");
	cbox:RegisterBox("Domino/System/ConsoleCommand.lua");
	cbox:RegisterBox("Domino/User/BSQ01_FuelTheViolence.BSQ01_Mission.lua");
	cbox:RegisterBox("Domino/User/BSQ05_SupplyAndDemand.BSQ05_Mission.lua");
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.Flush_BSQ_BarkBanks.lua");
	cbox:RegisterBox("Domino/System/LogToConsole.lua");
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.MikesPlace_RemoveBuddies_W1.lua");
	cbox:RegisterBox("Domino/User/SideMissions/SideMissions.MikesPlace_ForEachBuddy_Spawned.lua");
	cbox:RegisterBox("Domino/System/MultipleAND.lua");
	cbox:RegisterBox("Domino/System/SetInteger.lua");
	cbox:RegisterBox("Domino/System/CompareStrings.lua");
	cbox:RegisterBox("Domino/User/BSQ11_Hazelnuts.BSQ11_Mission.lua");
	
	-- Load resources
	cbox:LoadResource("", "CMovementResource");
end;

function export:Init(cbox)
	self.Anim_FloraGuillen = "";
	self.Anim_JosipIdromeno = "";
	self.Anim_MartyAlencar = "";
	self.Anim_MicheleDachss = "";
	self.Anim_PaulFerenc = "";
	self.Anim_QuarbaniSingh = "";
	self.Anim_WarrenClyde = "";
	self.DoBeckon_FloraGuillen = 0;
	self.DoBeckon_JosipIdromeno = 0;
	self.DoBeckon_MartyAlencar = 0;
	self.DoBeckon_MicheleDachss = 0;
	self.DoBeckon_PaulFerenc = 0;
	self.DoBeckon_QuarbaniSingh = 0;
	self.DoBeckon_WarrenClyde = 0;
	self.Entity_FloraGuillen = nil;
	self.Entity_JosipIdromeno = nil;
	self.Entity_MartyAlencar = nil;
	self.Entity_MicheleDachss = nil;
	self.Entity_PaulFerenc = nil;
	self.Entity_QuarbaniSingh = nil;
	self.Entity_WarrenClyde = nil;
	self.ForEach_BuddyAnim = "";
	self.ForEach_BuddyBeckon = 0;
	self.ForEach_BuddyEntity = nil;
	self.ForEach_BuddyName = "";
	self.GetBriefing_FloraGuillen = 0;
	self.GetBriefing_JosipIdromeno = 0;
	self.GetBriefing_MartyAlencar = 0;
	self.GetBriefing_MicheleDachss = 0;
	self.GetBriefing_PaulFerenc = 0;
	self.GetBriefing_QuarbaniSingh = 0;
	self.GetBriefing_WarrenClyde = 0;
	self.MikesPlace_BriefingsReady = 0;
	self.MikesPlace_BSQselectionTimer = 10;
	self.MikesPlace_InsideLocation = 0;
	self.MikesPlace_PawnsReady = 0;
	self.MikesPlace_RegenerateBuddies = 0;
	self.ObjectivePoint = "2053718060851798534";
	self.WeaponSafeDoor = "2055612104047625477";
	self[35] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_BSQmission_and_Pawnbrief_Selection.lua");
	self[35]._graph = self;
	self[35].New_pawnbrief_availability_set = self._type.f_35_New_pawnbrief_availability_set;
	self[35].Cancel_process_finished__or_nothing_active = self._type.f_35_Cancel_process_finished__or_nothing_active;
	self[35].Pawnbrief_ready__or_buddy_not_available = self._type.f_35_Pawnbrief_ready__or_buddy_not_available;
	self[35].Cancel_finished__was_secondairy_buddy = self._type.f_35_Cancel_finished__was_secondairy_buddy;
	self[35].Start_mission_BSQA = self._type.f_35_Start_mission_BSQA;
	self[35].Start_mission_BSQB = self._type.f_35_Start_mission_BSQB;
	self[47] = cbox:CreateBox("Domino/System/MultipleAND.lua");
	self[47]._graph = self;
	self[47]._DynamicAnchors = {
		Condition = 7,
	};
	self[47].Out = self._type.f_47_Out;
	self[31] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_BSQmission_and_Pawnbrief_Selection.lua");
	self[31]._graph = self;
	self[31].New_pawnbrief_availability_set = self._type.f_31_New_pawnbrief_availability_set;
	self[31].Cancel_process_finished__or_nothing_active = self._type.f_31_Cancel_process_finished__or_nothing_active;
	self[31].Pawnbrief_ready__or_buddy_not_available = self._type.f_31_Pawnbrief_ready__or_buddy_not_available;
	self[31].Cancel_finished__was_secondairy_buddy = self._type.f_31_Cancel_finished__was_secondairy_buddy;
	self[31].Start_mission_BSQA = self._type.f_31_Start_mission_BSQA;
	self[31].Start_mission_BSQB = self._type.f_31_Start_mission_BSQB;
	self[71] = cbox:CreateBox("Domino/User/BSQ03_HiddenArmory.BSQ03_Mission.lua");
	self[71]._graph = self;
	self[71].Succeeded = self._type.f_71_Succeeded;
	self[71].Finished = DummyFunction;
	self[55] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[55]._graph = self;
	self[55].Ready = self._type.f_55_Ready;
	self[55].New_mission_accepted = self._type.f_55_New_mission_accepted;
	self[55].Restart_briefigns = self._type.f_55_Restart_briefigns;
	self[95] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_ForEachBuddy_Spawned.lua");
	self[95]._graph = self;
	self[95].ForEach_spawned_buddy = self._type.f_95_ForEach_spawned_buddy;
	self[95].ForeEach_finished = self._type.f_95_ForeEach_finished;
	self[95].None_spawned_for_Story_mode = self._type.f_95_None_spawned_for_Story_mode;
	self[87] = cbox:CreateBox("Domino/System/ProximityTrigger.lua");
	self[87]._graph = self;
	self[87].Enter = self._type.f_87_Enter;
	self[87].Leave = self._type.f_87_Leave;
	self[87].Use = DummyFunction;
	self[112] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_IfBuddy_Spawned.lua");
	self[112]._graph = self;
	self[112].Output_buddy_data = self._type.f_112_Output_buddy_data;
	self[54] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[54]._graph = self;
	self[54].Ready = self._type.f_54_Ready;
	self[54].New_mission_accepted = self._type.f_54_New_mission_accepted;
	self[54].Restart_briefigns = self._type.f_54_Restart_briefigns;
	self[34] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_BSQmission_and_Pawnbrief_Selection.lua");
	self[34]._graph = self;
	self[34].New_pawnbrief_availability_set = self._type.f_34_New_pawnbrief_availability_set;
	self[34].Cancel_process_finished__or_nothing_active = self._type.f_34_Cancel_process_finished__or_nothing_active;
	self[34].Pawnbrief_ready__or_buddy_not_available = self._type.f_34_Pawnbrief_ready__or_buddy_not_available;
	self[34].Cancel_finished__was_secondairy_buddy = self._type.f_34_Cancel_finished__was_secondairy_buddy;
	self[34].Start_mission_BSQA = self._type.f_34_Start_mission_BSQA;
	self[34].Start_mission_BSQB = self._type.f_34_Start_mission_BSQB;
	self[45] = cbox:CreateBox("Domino/System/MultipleAND.lua");
	self[45]._graph = self;
	self[45]._DynamicAnchors = {
		Condition = 7,
	};
	self[45].Out = self._type.f_45_Out;
	self[69] = cbox:CreateBox("Domino/User/BSQ11_Hazelnuts.BSQ11_Mission.lua");
	self[69]._graph = self;
	self[69].Succeeded = self._type.f_69_Succeeded;
	self[69].Finished = DummyFunction;
	self[37] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_BSQmission_and_Pawnbrief_Selection.lua");
	self[37]._graph = self;
	self[37].New_pawnbrief_availability_set = self._type.f_37_New_pawnbrief_availability_set;
	self[37].Cancel_process_finished__or_nothing_active = self._type.f_37_Cancel_process_finished__or_nothing_active;
	self[37].Pawnbrief_ready__or_buddy_not_available = self._type.f_37_Pawnbrief_ready__or_buddy_not_available;
	self[37].Cancel_finished__was_secondairy_buddy = self._type.f_37_Cancel_finished__was_secondairy_buddy;
	self[37].Start_mission_BSQA = self._type.f_37_Start_mission_BSQA;
	self[37].Start_mission_BSQB = self._type.f_37_Start_mission_BSQB;
	self[80] = cbox:CreateBox("Domino/User/BSQ06_HarshDefault.BSQ06_Mission.lua");
	self[80]._graph = self;
	self[80].Succeeded = self._type.f_80_Succeeded;
	self[80].Finished = DummyFunction;
	self[122] = cbox:CreateBox("Domino/System/Delay.lua");
	self[122]._graph = self;
	self[122].TimeElapsed = self._type.f_122_TimeElapsed;
	self[61] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[61]._graph = self;
	self[61].Ready = self._type.f_61_Ready;
	self[61].New_mission_accepted = self._type.f_61_New_mission_accepted;
	self[61].Restart_briefigns = self._type.f_61_Restart_briefigns;
	self[48] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[48]._graph = self;
	self[48].Ready = self._type.f_48_Ready;
	self[48].New_mission_accepted = self._type.f_48_New_mission_accepted;
	self[48].Restart_briefigns = self._type.f_48_Restart_briefigns;
	self[28] = cbox:CreateBox("Domino/System/Door.lua");
	self[28]._graph = self;
	self[28].Out = self._type.f_28_Out;
	self[28].OnPush = DummyFunction;
	self[28].OnPull = DummyFunction;
	self[50] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[50]._graph = self;
	self[50].Ready = self._type.f_50_Ready;
	self[50].New_mission_accepted = self._type.f_50_New_mission_accepted;
	self[50].Restart_briefigns = self._type.f_50_Restart_briefigns;
	self[72] = cbox:CreateBox("Domino/User/BSQ15_Brewery.BSQ15_Mission.lua");
	self[72]._graph = self;
	self[72].Succeeded = self._type.f_72_Succeeded;
	self[72].Finished = DummyFunction;
	self[92] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_PawnbriefSelection_Timer.lua");
	self[92]._graph = self;
	self[92].Timer_elapsed = self._type.f_92_Timer_elapsed;
	self[81] = cbox:CreateBox("Domino/User/BSQ09_JunkMedicine.BSQ09_Mission.lua");
	self[81]._graph = self;
	self[81].Succeeded = self._type.f_81_Succeeded;
	self[81].Finished = DummyFunction;
	self[59] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[59]._graph = self;
	self[59].Ready = self._type.f_59_Ready;
	self[59].New_mission_accepted = self._type.f_59_New_mission_accepted;
	self[59].Restart_briefigns = self._type.f_59_Restart_briefigns;
	self[62] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[62]._graph = self;
	self[62].Ready = self._type.f_62_Ready;
	self[62].New_mission_accepted = self._type.f_62_New_mission_accepted;
	self[62].Restart_briefigns = self._type.f_62_Restart_briefigns;
	self[65] = cbox:CreateBox("Domino/User/BSQ01_FuelTheViolence.BSQ01_Mission.lua");
	self[65]._graph = self;
	self[65].Succeeded = self._type.f_65_Succeeded;
	self[65].Finished = DummyFunction;
	self[11] = cbox:CreateBox("Domino/User/Common_CustomBoxes.MissionAcceptedListener.lua");
	self[11]._graph = self;
	-- We need to cancel all BSQ missions before heading into world2
	self[11].StoryMission_Accepted = self._type.f_11_LibraryMission_Accepted;
	self[11].LibraryMission_Accepted = DummyFunction;
	self[11].SideMissionAccepted = DummyFunction;
	self[74] = cbox:CreateBox("Domino/User/BSQ05_SupplyAndDemand.BSQ05_Mission.lua");
	self[74]._graph = self;
	self[74].Succeeded = self._type.f_74_Succeeded;
	self[74].Finished = DummyFunction;
	self[84] = cbox:CreateBox("Domino/User/BSQ07_GreenFingers.BSQ07_Mission.lua");
	self[84]._graph = self;
	self[84].Succeeded = self._type.f_84_Succeeded;
	self[84].Finished = DummyFunction;
	self[126] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_ObjectivePoint.lua");
	self[126]._graph = self;
	self[75] = cbox:CreateBox("Domino/User/BSQ10_AgentYellow.BSQ10_Mission.lua");
	self[75]._graph = self;
	self[75].Succeeded = self._type.f_75_Succeeded;
	self[75].Finished = DummyFunction;
	self[68] = cbox:CreateBox("Domino/User/BSQ02_LostInTheGY.BSQ02_Mission.lua");
	self[68]._graph = self;
	self[68].Succeeded = self._type.f_68_Succeeded;
	self[68].Finished = DummyFunction;
	self[90] = cbox:CreateBox("Domino/System/Door.lua");
	self[90]._graph = self;
	self[90].Out = DummyFunction;
	self[90].OnPush = DummyFunction;
	self[90].OnPull = DummyFunction;
	self[53] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[53]._graph = self;
	self[53].Ready = self._type.f_53_Ready;
	self[53].New_mission_accepted = self._type.f_53_New_mission_accepted;
	self[53].Restart_briefigns = self._type.f_53_Restart_briefigns;
	self[66] = cbox:CreateBox("Domino/User/BSQ12_LemonBeater.BSQ12_Mission.lua");
	self[66]._graph = self;
	self[66].Succeeded = self._type.f_66_Succeeded;
	self[66].Finished = DummyFunction;
	self[83] = cbox:CreateBox("Domino/User/BSQ04_BurnTheWater.BSQ04_Mission.lua");
	self[83]._graph = self;
	self[83].Succeeded = self._type.f_83_Succeeded;
	self[83].Finished = DummyFunction;
	self[58] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[58]._graph = self;
	self[58].Ready = self._type.f_58_Ready;
	self[58].New_mission_accepted = self._type.f_58_New_mission_accepted;
	self[58].Restart_briefigns = self._type.f_58_Restart_briefigns;
	self[30] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_NewSecondaryBuddy_Spawned.lua");
	self[30]._graph = self;
	self[30].Spawning = self._type.f_30_Spawning;
	self[117] = cbox:CreateBox("Domino/System/Door.lua");
	self[117]._graph = self;
	self[117].Out = self._type.f_117_Out;
	self[117].OnPush = DummyFunction;
	self[117].OnPull = DummyFunction;
	self[93] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.Flush_BSQ_BarkBanks.lua");
	self[93]._graph = self;
	self[93].Out = self._type.f_93_Out;
	self[40] = cbox:CreateBox("Domino/System/MultipleAND.lua");
	self[40]._graph = self;
	self[40]._DynamicAnchors = {
		Condition = 7,
	};
	self[40].Out = self._type.f_40_Out;
	self[115] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_IfBuddy_Spawned.lua");
	self[115]._graph = self;
	self[115].Output_buddy_data = self._type.f_115_Output_buddy_data;
	self[77] = cbox:CreateBox("Domino/User/BSQ08_ThePrototype.BSQ08_Mission.lua");
	self[77]._graph = self;
	self[77].Succeeded = self._type.f_77_Succeeded;
	self[77].Finished = DummyFunction;
	self[113] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_IfBuddy_Spawned.lua");
	self[113]._graph = self;
	self[113].Output_buddy_data = self._type.f_113_Output_buddy_data;
	self[52] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[52]._graph = self;
	self[52].Ready = self._type.f_52_Ready;
	self[52].New_mission_accepted = self._type.f_52_New_mission_accepted;
	self[52].Restart_briefigns = self._type.f_52_Restart_briefigns;
	self[9] = cbox:CreateBox("Domino/User/Common_CustomBoxes.MissionCompleteListener.lua");
	self[9]._graph = self;
	self[9].StoryMission_Completed = DummyFunction;
	self[9].LibraryMission_Completed = DummyFunction;
	self[9].SideMission_Completed = DummyFunction;
	self[9].BuddyUnlock_Completed = DummyFunction;
	self[38] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_BSQmission_and_Pawnbrief_Selection.lua");
	self[38]._graph = self;
	self[38].New_pawnbrief_availability_set = self._type.f_38_New_pawnbrief_availability_set;
	self[38].Cancel_process_finished__or_nothing_active = self._type.f_38_Cancel_process_finished__or_nothing_active;
	self[38].Pawnbrief_ready__or_buddy_not_available = self._type.f_38_Pawnbrief_ready__or_buddy_not_available;
	self[38].Cancel_finished__was_secondairy_buddy = self._type.f_38_Cancel_finished__was_secondairy_buddy;
	self[38].Start_mission_BSQA = self._type.f_38_Start_mission_BSQA;
	self[38].Start_mission_BSQB = self._type.f_38_Start_mission_BSQB;
	self[56] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[56]._graph = self;
	self[56].Ready = self._type.f_56_Ready;
	self[56].New_mission_accepted = self._type.f_56_New_mission_accepted;
	self[56].Restart_briefigns = self._type.f_56_Restart_briefigns;
	self[125] = cbox:CreateBox("Domino/System/Door.lua");
	self[125]._graph = self;
	self[125].Out = self._type.f_125_Out;
	self[125].OnPush = DummyFunction;
	self[125].OnPull = DummyFunction;
	self[51] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[51]._graph = self;
	self[51].Ready = self._type.f_51_Ready;
	self[51].New_mission_accepted = self._type.f_51_New_mission_accepted;
	self[51].Restart_briefigns = self._type.f_51_Restart_briefigns;
	self[116] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_IfBuddy_Spawned.lua");
	self[116]._graph = self;
	self[116].Output_buddy_data = self._type.f_116_Output_buddy_data;
	self[91] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_WaitForLoadedBuddy.lua");
	self[91]._graph = self;
	self[91].Buddy_removed__or_none_to_wait_for = self._type.f_91_Buddy_removed__or_none_to_wait_for;
	self[22] = cbox:CreateBox("Domino/System/ConsoleCommand.lua");
	self[22]._graph = self;
	self[22].Out = self._type.f_22_Out;
	self[33] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_BSQmission_and_Pawnbrief_Selection.lua");
	self[33]._graph = self;
	self[33].New_pawnbrief_availability_set = self._type.f_33_New_pawnbrief_availability_set;
	self[33].Cancel_process_finished__or_nothing_active = self._type.f_33_Cancel_process_finished__or_nothing_active;
	self[33].Pawnbrief_ready__or_buddy_not_available = self._type.f_33_Pawnbrief_ready__or_buddy_not_available;
	self[33].Cancel_finished__was_secondairy_buddy = self._type.f_33_Cancel_finished__was_secondairy_buddy;
	self[33].Start_mission_BSQA = self._type.f_33_Start_mission_BSQA;
	self[33].Start_mission_BSQB = self._type.f_33_Start_mission_BSQB;
	self[114] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_IfBuddy_Spawned.lua");
	self[114]._graph = self;
	self[114].Output_buddy_data = self._type.f_114_Output_buddy_data;
	self[63] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_RemoveBuddies_W1.lua");
	self[63]._graph = self;
	self[63].Finished = self._type.f_63_Finished;
	self[63].Finished_2nd_buddy_removal = self._type.f_63_Finished_2nd_buddy_removal;
	self[109] = cbox:CreateBox("Domino/System/Delay.lua");
	self[109]._graph = self;
	self[109].TimeElapsed = self._type.f_109_TimeElapsed;
	self[111] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_IfBuddy_Spawned.lua");
	self[111]._graph = self;
	self[111].Output_buddy_data = self._type.f_111_Output_buddy_data;
	self[60] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[60]._graph = self;
	self[60].Ready = self._type.f_60_Ready;
	self[60].New_mission_accepted = self._type.f_60_New_mission_accepted;
	self[60].Restart_briefigns = self._type.f_60_Restart_briefigns;
	self[78] = cbox:CreateBox("Domino/User/BSQ13_Dreadlock.BSQ13_Mission.lua");
	self[78]._graph = self;
	self[78].Succeeded = self._type.f_78_Succeeded;
	self[78].Finished = DummyFunction;
	self[7] = cbox:CreateBox("Domino/User/Common_CustomBoxes.MissionCompleteListener.lua");
	self[7]._graph = self;
	self[7].StoryMission_Completed = DummyFunction;
	-- Regenerate buddies at Mike's after completing library/side missions
	--self[7].LibraryMission_Completed = DummyFunction;
	--self[7].SideMission_Completed = DummyFunction;
	self[7].LibraryMission_Completed = self._type.RegenerateBuddies;
	self[7].SideMission_Completed = self._type.RegenerateBuddies;
	self[7].BuddyUnlock_Completed = self._type.f_7_BuddyUnlock_Completed;
	self[110] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_IfBuddy_Spawned.lua");
	self[110]._graph = self;
	self[110].Output_buddy_data = self._type.f_110_Output_buddy_data;
	self[57] = cbox:CreateBox("Domino/User/Common_BuddySideQuests.BSQ_Activate_and_Cancel.lua");
	self[57]._graph = self;
	self[57].Ready = self._type.f_57_Ready;
	self[57].New_mission_accepted = self._type.f_57_New_mission_accepted;
	self[57].Restart_briefigns = self._type.f_57_Restart_briefigns;
	self[36] = cbox:CreateBox("Domino/User/SideMissions/SideMissions.MikesPlace_BSQmission_and_Pawnbrief_Selection.lua");
	self[36]._graph = self;
	self[36].New_pawnbrief_availability_set = self._type.f_36_New_pawnbrief_availability_set;
	self[36].Cancel_process_finished__or_nothing_active = self._type.f_36_Cancel_process_finished__or_nothing_active;
	self[36].Pawnbrief_ready__or_buddy_not_available = self._type.f_36_Pawnbrief_ready__or_buddy_not_available;
	self[36].Cancel_finished__was_secondairy_buddy = self._type.f_36_Cancel_finished__was_secondairy_buddy;
	self[36].Start_mission_BSQA = self._type.f_36_Start_mission_BSQA;
	self[36].Start_mission_BSQB = self._type.f_36_Start_mission_BSQB;
end;

function export:ShutDown()
	self[35]._type.ShutDown(self[35]);
	self[47]._type.ShutDown(self[47]);
	self[31]._type.ShutDown(self[31]);
	self[71]._type.ShutDown(self[71]);
	self[55]._type.ShutDown(self[55]);
	self[95]._type.ShutDown(self[95]);
	self[87]._type.ShutDown(self[87]);
	self[112]._type.ShutDown(self[112]);
	self[54]._type.ShutDown(self[54]);
	self[34]._type.ShutDown(self[34]);
	self[45]._type.ShutDown(self[45]);
	self[69]._type.ShutDown(self[69]);
	self[37]._type.ShutDown(self[37]);
	self[80]._type.ShutDown(self[80]);
	self[122]._type.ShutDown(self[122]);
	self[61]._type.ShutDown(self[61]);
	self[48]._type.ShutDown(self[48]);
	self[28]._type.ShutDown(self[28]);
	self[50]._type.ShutDown(self[50]);
	self[72]._type.ShutDown(self[72]);
	self[92]._type.ShutDown(self[92]);
	self[81]._type.ShutDown(self[81]);
	self[59]._type.ShutDown(self[59]);
	self[62]._type.ShutDown(self[62]);
	self[65]._type.ShutDown(self[65]);
	self[11]._type.ShutDown(self[11]);
	self[74]._type.ShutDown(self[74]);
	self[84]._type.ShutDown(self[84]);
	self[126]._type.ShutDown(self[126]);
	self[75]._type.ShutDown(self[75]);
	self[68]._type.ShutDown(self[68]);
	self[90]._type.ShutDown(self[90]);
	self[53]._type.ShutDown(self[53]);
	self[66]._type.ShutDown(self[66]);
	self[83]._type.ShutDown(self[83]);
	self[58]._type.ShutDown(self[58]);
	self[30]._type.ShutDown(self[30]);
	self[117]._type.ShutDown(self[117]);
	self[93]._type.ShutDown(self[93]);
	self[40]._type.ShutDown(self[40]);
	self[115]._type.ShutDown(self[115]);
	self[77]._type.ShutDown(self[77]);
	self[113]._type.ShutDown(self[113]);
	self[52]._type.ShutDown(self[52]);
	self[9]._type.ShutDown(self[9]);
	self[38]._type.ShutDown(self[38]);
	self[56]._type.ShutDown(self[56]);
	self[125]._type.ShutDown(self[125]);
	self[51]._type.ShutDown(self[51]);
	self[116]._type.ShutDown(self[116]);
	self[91]._type.ShutDown(self[91]);
	self[22]._type.ShutDown(self[22]);
	self[33]._type.ShutDown(self[33]);
	self[114]._type.ShutDown(self[114]);
	self[63]._type.ShutDown(self[63]);
	self[109]._type.ShutDown(self[109]);
	self[111]._type.ShutDown(self[111]);
	self[60]._type.ShutDown(self[60]);
	self[78]._type.ShutDown(self[78]);
	self[7]._type.ShutDown(self[7]);
	self[110]._type.ShutDown(self[110]);
	self[57]._type.ShutDown(self[57]);
	self[36]._type.ShutDown(self[36]);
end;

function export:RegenerateBuddies()
	self = self._graph;
	-- Regenerate buddies excluding primary (library mission subversion) buddy if a library mission is active
	System:Log("BSQManager: Regenerating buddies for Mike's place");
	self.MikesPlace_PawnsReady = false;
	if (Globals.MASTER_GameGlobals.PrimaryMissionActive == 1) then
		self._type.en_63_PrimaryCheck(self);
	else
		self._type.en_63(self);
	end
	-- Update 3.2: Don't de-spawn buddies if a BSQ mission is active
	if (Globals.MASTER_GameGlobals.AcceptedBuddyMissionID == "x") then
		self[63]._type.Instant_remove(self[63]);
	end
end;

function export:StoryMission_mode()
	self[7]._type.StopListening(self[7]);
	Boxes[PathID("Domino/System/SetInteger.lua")].Integer = 0;
	Boxes[PathID("Domino/System/SetInteger.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetInteger.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetInteger.lua")].Out = self._type.f_2_Out;
	Boxes[PathID("Domino/System/SetInteger.lua")]._type.FromInteger(Boxes[PathID("Domino/System/SetInteger.lua")]);
	self[9]._type.StopListening(self[9]);
	self[11]._type.StopListening(self[11]);
end;

function export:SideQuest_mode()
	self[22].Command = "forcebsq";
	self[22]._type.In(self[22]);
	self[11]._type.Listen(self[11]);
	self[9]._type.Listen(self[9]);
	self[7]._type.Listen(self[7]);
	self._type.en_4(self);
	Boxes[PathID("Domino/System/SetInteger.lua")]._type.FromInteger(Boxes[PathID("Domino/System/SetInteger.lua")]);
end;

function export:LibraryMission_mode()
	self[7]._type.Listen(self[7]);
	self._type.en_6(self);
	Boxes[PathID("Domino/System/SetInteger.lua")]._type.FromInteger(Boxes[PathID("Domino/System/SetInteger.lua")]);
end;

function export:f_1_Out()
	self = self._graph;
	self[30]._type.StopListening(self[30]);
	self._type.en_28(self);
	self[28]._type.SetAsUnusable(self[28]);
	Boxes[PathID("Domino/System/GameElementObjective.lua")].GameElement = self.ObjectivePoint;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._graph = self;
	Boxes[PathID("Domino/System/GameElementObjective.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/GameElementObjective.lua")]._type.Enable(Boxes[PathID("Domino/System/GameElementObjective.lua")]);
end;

function export:f_2_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.W1_MikesPlace_Mode = Boxes[PathID("Domino/System/SetInteger.lua")].Target;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "MikesPlace : \"StoryMission\" mode";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_1_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_3_Out()
	self = self._graph;
	self[30]._type.Listen(self[30]);
	self._type.en_28(self);
	self[28]._type.SetAsUnusable(self[28]);
end;

function export:f_4_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.W1_MikesPlace_Mode = Boxes[PathID("Domino/System/SetInteger.lua")].Target;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "MikesPlace : \"SideQuest\" mode";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_3_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_5_Out()
	self = self._graph;
	self[30]._type.Listen(self[30]);
	self._type.en_28(self);
	self[28]._type.SetAsUnusable(self[28]);
end;

function export:f_6_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.W1_MikesPlace_Mode = Boxes[PathID("Domino/System/SetInteger.lua")].Target;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "MikesPlace : \"LibraryMission\" mode";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_5_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_8_Out()
	self = self._graph;
	self._type.en_28(self);
	self[28]._type.SetAsUnusable(self[28]);
end;

function export:f_7_BuddyUnlock_Completed()
	self = self._graph;
	-- Regenerate buddies only if a library mission isn't active (update 3.1: added BSQ check and buddy regeneration)
	if (Globals.MASTER_GameGlobals.PrimaryMissionActive == 0) and (Globals.MASTER_GameGlobals.AcceptedBuddyMissionID == "x") then
		Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
		Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
		Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
		Boxes[PathID("Domino/System/LogToConsole.lua")].String = "MikesPlace : New unlocked buddy for current mode";
		Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
		Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
		Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_8_Out;
		Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
	-- Update 3.2: Don't de-spawn buddies if a BSQ mission is active
	--else
	elseif (Globals.MASTER_GameGlobals.AcceptedBuddyMissionID == "x") then
		-- Regenerate buddies excluding primary (library mission subversion) buddy
		self.MikesPlace_PawnsReady = false;
		self._type.en_63_PrimaryCheck(self);
		self[63]._type.Instant_remove(self[63]);
	end
end;

function export:f_9_LibraryMission_Completed()
	self = self._graph;
	self._type.en_4(self);
	Boxes[PathID("Domino/System/SetInteger.lua")]._type.FromInteger(Boxes[PathID("Domino/System/SetInteger.lua")]);
end;

function export:f_10_A_contains_B()
	self = self._graph;
	self._type.en_6(self);
	Boxes[PathID("Domino/System/SetInteger.lua")]._type.FromInteger(Boxes[PathID("Domino/System/SetInteger.lua")]);
end;

function export:f_11_StoryMission_Accepted()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.AcceptedMissionID;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "A1SM02";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_10_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_11_LibraryMission_Accepted()
	self = self._graph;
	self._type.en_6(self);
	Boxes[PathID("Domino/System/SetInteger.lua")]._type.FromInteger(Boxes[PathID("Domino/System/SetInteger.lua")]);
end;

function export:f_12_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.ConsoleCommandParameter = Boxes[PathID("Domino/System/SetString.lua")].Target;
end;

function export:f_13_Out()
	self = self._graph;
	self._type.en_12(self);
	Boxes[PathID("Domino/System/SetString.lua")]._type.FromString(Boxes[PathID("Domino/System/SetString.lua")]);
end;

function export:f_14_Out()
	self = self._graph;
	self._type.en_13(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_15_Is_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_14_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_18_Out()
	self = self._graph;
	self._type.en_92(self);
	self[92]._type.Stop_timer(self[92]);
end;

function export:f_19_Out_0()
	self = self._graph;
	self[93]._type.Unload_W1(self[93]);
end;

function export:f_19_Out_1()
	self = self._graph;
	self._type.en_36(self);
	self[36]._type.Select_new_pawnbrief(self[36]);
	self._type.en_33(self);
	self[33]._type.Select_new_pawnbrief(self[33]);
	self._type.en_38(self);
	self[38]._type.Select_new_pawnbrief(self[38]);
	self._type.en_34(self);
	self[34]._type.Select_new_pawnbrief(self[34]);
	self._type.en_37(self);
	self[37]._type.Select_new_pawnbrief(self[37]);
	self._type.en_35(self);
	self[35]._type.Select_new_pawnbrief(self[35]);
	self._type.en_31(self);
	self[31]._type.Select_new_pawnbrief(self[31]);
	-- Manually trigger Mike's "leaving area" check to regenerate new buddy missions automatically after completing one
	--if (GetEntityName("2055612104047625477") ~= "InteractiveDoors.Urbain02_AnimatedDoor01_2") then
		Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
		Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_87_Leave;
		Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
	--end
end;

function export:f_20_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_18_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_17_A_eq_B()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.MikesPlace_PawnsReady;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_20_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_21_Out_0()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareIntegers.lua")].A = Globals.MASTER_GameGlobals.W1_MikesPlace_Mode;
	Boxes[PathID("Domino/System/CompareIntegers.lua")].B = 1;
	Boxes[PathID("Domino/System/CompareIntegers.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareIntegers.lua")].A_lt_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareIntegers.lua")].A_le_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareIntegers.lua")].A_eq_B = self._type.f_17_A_eq_B;
	Boxes[PathID("Domino/System/CompareIntegers.lua")].A_ge_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareIntegers.lua")].A_gt_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareIntegers.lua")].A_ne_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareIntegers.lua")]._type.In(Boxes[PathID("Domino/System/CompareIntegers.lua")]);
end;

function export:f_21_Out_1()
	self = self._graph;
	self._type.en_12(self);
	Boxes[PathID("Domino/System/SetString.lua")]._type.FromString(Boxes[PathID("Domino/System/SetString.lua")]);
end;

function export:f_16_A_contains_B()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_21_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_21_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_16_A_ncontains_B()
	self = self._graph;
	self._type.en_13(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_15_Is_not_nil()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A = Globals.MASTER_GameGlobals.ConsoleCommandParameter;
	Boxes[PathID("Domino/System/CompareStrings.lua")].B = "BSQ";
	Boxes[PathID("Domino/System/CompareStrings.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_eq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_neq_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_contains_B = self._type.f_16_A_contains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")].A_ncontains_B = self._type.f_16_A_ncontains_B;
	Boxes[PathID("Domino/System/CompareStrings.lua")]._type.In(Boxes[PathID("Domino/System/CompareStrings.lua")]);
end;

function export:f_22_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.ConsoleCommandParameter = self[22].Parameter;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Integer = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Float = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].String = Globals.MASTER_GameGlobals.ConsoleCommandParameter;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Entity = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Animation = nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._graph = self;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_nil = self._type.f_15_Is_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")].Is_not_nil = self._type.f_15_Is_not_nil;
	Boxes[PathID("Domino/System/TestIfNil.lua")]._type.In(Boxes[PathID("Domino/System/TestIfNil.lua")]);
end;

function export:f_23_Out_0()
	self = self._graph;
	self[45]._type.Reset(self[45]);
end;

function export:f_23_Out_1()
	self = self._graph;
	self._type.en_31(self);
	self[31]._type.Cancel_pawnbrief__if_any_active(self[31]);
	self._type.en_37(self);
	self[37]._type.Cancel_pawnbrief__if_any_active(self[37]);
	self._type.en_35(self);
	self[35]._type.Cancel_pawnbrief__if_any_active(self[35]);
	self._type.en_34(self);
	self[34]._type.Cancel_pawnbrief__if_any_active(self[34]);
	self._type.en_33(self);
	self[33]._type.Cancel_pawnbrief__if_any_active(self[33]);
	self._type.en_38(self);
	self[38]._type.Cancel_pawnbrief__if_any_active(self[38]);
	self._type.en_36(self);
	self[36]._type.Cancel_pawnbrief__if_any_active(self[36]);
end;

function export:f_24_Out()
	self = self._graph;
	self.MikesPlace_RegenerateBuddies = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self[87].Trigger = "2054468884890662846";
	self[87].CheckNow = 1;
	self[87]._type.Enable(self[87]);
	self._type.en_23(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_25_Out()
	self = self._graph;
	self.MikesPlace_BriefingsReady = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_24_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_26_Out()
	self = self._graph;
	self.MikesPlace_PawnsReady = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_25_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_27_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.W0_MikesPlace_BSQbriefings = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_26_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_28_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_27_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_29_Out()
	self = self._graph;
	--self._type.en_31(self);
	--self[31]._type.Cancel_pawnbrief__if_secondairy_buddy(self[31]);
	--self._type.en_33(self);
	--self[33]._type.Cancel_pawnbrief__if_secondairy_buddy(self[33]);
	--self._type.en_34(self);
	--self[34]._type.Cancel_pawnbrief__if_secondairy_buddy(self[34]);
	--self._type.en_35(self);
	--self[35]._type.Cancel_pawnbrief__if_secondairy_buddy(self[35]);
	--self._type.en_36(self);
	--self[36]._type.Cancel_pawnbrief__if_secondairy_buddy(self[36]);
	--self._type.en_37(self);
	--self[37]._type.Cancel_pawnbrief__if_secondairy_buddy(self[37]);
	--self._type.en_38(self);
	--self[38]._type.Cancel_pawnbrief__if_secondairy_buddy(self[38]);
end;

function export:f_30_Spawning()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_29_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_31_New_pawnbrief_availability_set()
	self = self._graph;
	self._type.ex_31(self);
	self[40]._type.Condition(self[40], 3);
end;

function export:f_31_Cancel_process_finished__or_nothing_active()
	self = self._graph;
	self._type.ex_31(self);
	self[45]._type.Condition(self[45], 3);
end;

function export:f_31_Pawnbrief_ready__or_buddy_not_available()
	self = self._graph;
	self._type.ex_31(self);
	self[47]._type.Condition(self[47], 3);
end;

function export:f_32_Out()
	self = self._graph;
	-- Update 3.2: Don't de-spawn buddies if a BSQ mission is active
	if (Globals.MASTER_GameGlobals.AcceptedBuddyMissionID == "x") then
		self._type.en_63(self);
		self[63]._type.Remove_new_2nd_buddy(self[63]);
	end
end;

function export:f_31_Cancel_finished__was_secondairy_buddy()
	self = self._graph;
	self._type.ex_31(self);
	self._type.en_32(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_31_Start_mission_BSQA()
	self = self._graph;
	self._type.ex_31(self);
	self[48]._type.Listen_for_accept(self[48]);
end;

function export:f_31_Start_mission_BSQB()
	self = self._graph;
	self._type.ex_31(self);
	self[50]._type.Listen_for_accept(self[50]);
end;

function export:f_33_New_pawnbrief_availability_set()
	self = self._graph;
	self._type.ex_33(self);
	self[40]._type.Condition(self[40], 6);
end;

function export:f_33_Cancel_process_finished__or_nothing_active()
	self = self._graph;
	self._type.ex_33(self);
	self[45]._type.Condition(self[45], 6);
end;

function export:f_33_Pawnbrief_ready__or_buddy_not_available()
	self = self._graph;
	self._type.ex_33(self);
	self[47]._type.Condition(self[47], 6);
end;

function export:f_33_Cancel_finished__was_secondairy_buddy()
	self = self._graph;
	self._type.ex_33(self);
	self._type.en_32(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_33_Start_mission_BSQA()
	self = self._graph;
	self._type.ex_33(self);
	self[51]._type.Listen_for_accept(self[51]);
end;

function export:f_33_Start_mission_BSQB()
	self = self._graph;
	self._type.ex_33(self);
	self[52]._type.Listen_for_accept(self[52]);
end;

function export:f_34_New_pawnbrief_availability_set()
	self = self._graph;
	self._type.ex_34(self);
	self[40]._type.Condition(self[40], 1);
end;

function export:f_34_Cancel_process_finished__or_nothing_active()
	self = self._graph;
	self._type.ex_34(self);
	self[45]._type.Condition(self[45], 1);
end;

function export:f_34_Pawnbrief_ready__or_buddy_not_available()
	self = self._graph;
	self._type.ex_34(self);
	self[47]._type.Condition(self[47], 1);
end;

function export:f_34_Cancel_finished__was_secondairy_buddy()
	self = self._graph;
	self._type.ex_34(self);
	self._type.en_32(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_34_Start_mission_BSQA()
	self = self._graph;
	self._type.ex_34(self);
	self[53]._type.Listen_for_accept(self[53]);
end;

function export:f_34_Start_mission_BSQB()
	self = self._graph;
	self._type.ex_34(self);
	self[54]._type.Listen_for_accept(self[54]);
end;

function export:f_35_New_pawnbrief_availability_set()
	self = self._graph;
	self._type.ex_35(self);
	self[40]._type.Condition(self[40], 4);
end;

function export:f_35_Cancel_process_finished__or_nothing_active()
	self = self._graph;
	self._type.ex_35(self);
	self[45]._type.Condition(self[45], 4);
end;

function export:f_35_Pawnbrief_ready__or_buddy_not_available()
	self = self._graph;
	self._type.ex_35(self);
	self[47]._type.Condition(self[47], 4);
end;

function export:f_35_Cancel_finished__was_secondairy_buddy()
	self = self._graph;
	self._type.ex_35(self);
	self._type.en_32(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_35_Start_mission_BSQA()
	self = self._graph;
	self._type.ex_35(self);
	self[55]._type.Listen_for_accept(self[55]);
end;

function export:f_35_Start_mission_BSQB()
	self = self._graph;
	self._type.ex_35(self);
	self[56]._type.Listen_for_accept(self[56]);
end;

function export:f_36_New_pawnbrief_availability_set()
	self = self._graph;
	self._type.ex_36(self);
	self[40]._type.Condition(self[40], 5);
end;

function export:f_36_Cancel_process_finished__or_nothing_active()
	self = self._graph;
	self._type.ex_36(self);
	self[45]._type.Condition(self[45], 5);
end;

function export:f_36_Pawnbrief_ready__or_buddy_not_available()
	self = self._graph;
	self._type.ex_36(self);
	self[47]._type.Condition(self[47], 5);
end;

function export:f_36_Cancel_finished__was_secondairy_buddy()
	self = self._graph;
	self._type.ex_36(self);
	self._type.en_32(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_36_Start_mission_BSQA()
	self = self._graph;
	self._type.ex_36(self);
	self[57]._type.Listen_for_accept(self[57]);
end;

function export:f_36_Start_mission_BSQB()
	self = self._graph;
	self._type.ex_36(self);
	self[58]._type.Listen_for_accept(self[58]);
end;

function export:f_37_New_pawnbrief_availability_set()
	self = self._graph;
	self._type.ex_37(self);
	self[40]._type.Condition(self[40], 0);
end;

function export:f_37_Cancel_process_finished__or_nothing_active()
	self = self._graph;
	self._type.ex_37(self);
	self[45]._type.Condition(self[45], 0);
end;

function export:f_37_Pawnbrief_ready__or_buddy_not_available()
	self = self._graph;
	self._type.ex_37(self);
	self[47]._type.Condition(self[47], 0);
end;

function export:f_37_Cancel_finished__was_secondairy_buddy()
	self = self._graph;
	self._type.ex_37(self);
	self._type.en_32(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_37_Start_mission_BSQA()
	self = self._graph;
	self._type.ex_37(self);
	self[59]._type.Listen_for_accept(self[59]);
end;

function export:f_37_Start_mission_BSQB()
	self = self._graph;
	self._type.ex_37(self);
	self[60]._type.Listen_for_accept(self[60]);
end;

function export:f_38_New_pawnbrief_availability_set()
	self = self._graph;
	self._type.ex_38(self);
	self[40]._type.Condition(self[40], 2);
end;

function export:f_38_Cancel_process_finished__or_nothing_active()
	self = self._graph;
	self._type.ex_38(self);
	self[45]._type.Condition(self[45], 2);
end;

function export:f_38_Pawnbrief_ready__or_buddy_not_available()
	self = self._graph;
	self._type.ex_38(self);
	self[47]._type.Condition(self[47], 2);
end;

function export:f_38_Cancel_finished__was_secondairy_buddy()
	self = self._graph;
	self._type.ex_38(self);
	self._type.en_32(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_38_Start_mission_BSQA()
	self = self._graph;
	self._type.ex_38(self);
	self[61]._type.Listen_for_accept(self[61]);
end;

function export:f_38_Start_mission_BSQB()
	self = self._graph;
	self._type.ex_38(self);
	self[62]._type.Listen_for_accept(self[62]);
end;

function export:f_39_Out()
	self = self._graph;
	self[126].ObjectivePoint = self.ObjectivePoint;
	self[126].GetBriefing_Buddy_A = self.GetBriefing_FloraGuillen;
	self[126].GetBriefing_Buddy_B = self.GetBriefing_JosipIdromeno;
	self[126].GetBriefing_Buddy_C = self.GetBriefing_MartyAlencar;
	self[126].GetBriefing_Buddy_D = self.GetBriefing_MicheleDachss;
	self[126].GetBriefing_Buddy_E = self.GetBriefing_PaulFerenc;
	self[126].GetBriefing_Buddy_F = self.GetBriefing_QuarbaniSingh;
	self[126].GetBriefing_Buddy_G_ = self.GetBriefing_WarrenClyde;
	self[126]._type.Seset_objective_point(self[126]);
end;

function export:f_40_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_39_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_42_Out()
	self = self._graph;
	-- Update 3.2: Don't de-spawn buddies if a BSQ mission is active
	if (Globals.MASTER_GameGlobals.AcceptedBuddyMissionID == "x") then
		self.MikesPlace_PawnsReady = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
		self._type.en_63(self);
		self[63]._type.Instant_remove(self[63]);
	end
end;

function export:f_41_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_42_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_43_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = DummyFunction;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_41_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_44_Out_0()
	self = self._graph;
	self[47]._type.Reset(self[47]);
end;

function export:f_44_Out_1()
	self = self._graph;
	self._type.en_35(self);
	self[35]._type.Start_briefing__if_buddy_available(self[35]);
	self._type.en_33(self);
	self[33]._type.Start_briefing__if_buddy_available(self[33]);
	self._type.en_37(self);
	self[37]._type.Start_briefing__if_buddy_available(self[37]);
	self._type.en_38(self);
	self[38]._type.Start_briefing__if_buddy_available(self[38]);
	self._type.en_34(self);
	self[34]._type.Start_briefing__if_buddy_available(self[34]);
	self._type.en_36(self);
	self[36]._type.Start_briefing__if_buddy_available(self[36]);
	self._type.en_31(self);
	self[31]._type.Start_briefing__if_buddy_available(self[31]);
end;

function export:f_43_A_is_False()
	self = self._graph;
	self._type.en_44(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_45_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.MikesPlace_RegenerateBuddies;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_43_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_43_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_46_Out()
	self = self._graph;
	self.MikesPlace_BriefingsReady = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self[90].Door = self.WeaponSafeDoor;
	self[90]._type.SetAsUsable(self[90]);
end;

function export:f_47_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_46_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_48_Ready()
	self = self._graph;
	self[65]._type.In(self[65]);
end;

function export:f_48_New_mission_accepted()
	self = self._graph;
	self[65]._type.Cancel(self[65]);
end;

function export:f_49_Out()
	self = self._graph;
	self._type.en_92(self);
	self[92]._type.New_buddy_presence(self[92]);
end;

function export:f_48_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_50_Ready()
	self = self._graph;
	self[66]._type.In(self[66]);
end;

function export:f_50_New_mission_accepted()
	self = self._graph;
	self[66]._type.Cancel(self[66]);
end;

function export:f_50_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_51_Ready()
	self = self._graph;
	self[68]._type.In(self[68]);
end;

function export:f_51_New_mission_accepted()
	self = self._graph;
	self[68]._type.Cancel(self[68]);
end;

function export:f_51_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_52_Ready()
	self = self._graph;
	self[69]._type.In(self[69]);
end;

function export:f_52_New_mission_accepted()
	self = self._graph;
	self[69]._type.Cancel(self[69]);
end;

function export:f_52_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_53_Ready()
	self = self._graph;
	self[71]._type.In(self[71]);
end;

function export:f_53_New_mission_accepted()
	self = self._graph;
	self[71]._type.Cancel(self[71]);
end;

function export:f_53_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_54_Ready()
	self = self._graph;
	self[72]._type.In(self[72]);
end;

function export:f_54_New_mission_accepted()
	self = self._graph;
	self[72]._type.Cancel(self[72]);
end;

function export:f_54_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_55_Ready()
	self = self._graph;
	self[74]._type.In(self[74]);
end;

function export:f_55_New_mission_accepted()
	self = self._graph;
	self[74]._type.Cancel(self[74]);
end;

function export:f_55_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_56_Ready()
	self = self._graph;
	self[75]._type.In(self[75]);
end;

function export:f_56_New_mission_accepted()
	self = self._graph;
	self[75]._type.Cancel(self[75]);
end;

function export:f_56_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_57_Ready()
	self = self._graph;
	self[77]._type.In(self[77]);
end;

function export:f_57_New_mission_accepted()
	self = self._graph;
	self[77]._type.Cancel(self[77]);
end;

function export:f_57_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_58_Ready()
	self = self._graph;
	self[78]._type.In(self[78]);
end;

function export:f_58_New_mission_accepted()
	self = self._graph;
	self[78]._type.Cancel(self[78]);
end;

function export:f_58_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_59_Ready()
	self = self._graph;
	self[80]._type.In(self[80]);
end;

function export:f_59_New_mission_accepted()
	self = self._graph;
	self[80]._type.Cancel(self[80]);
end;

function export:f_59_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_60_Ready()
	self = self._graph;
	self[81]._type.In(self[81]);
end;

function export:f_60_New_mission_accepted()
	self = self._graph;
	self[81]._type.Cancel(self[81]);
end;

function export:f_60_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_61_Ready()
	self = self._graph;
	self[83]._type.In(self[83]);
end;

function export:f_61_New_mission_accepted()
	self = self._graph;
	self[83]._type.Cancel(self[83]);
end;

function export:f_61_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_62_Ready()
	self = self._graph;
	self[84]._type.In(self[84]);
end;

function export:f_62_New_mission_accepted()
	self = self._graph;
	self[84]._type.Cancel(self[84]);
end;

function export:f_62_Restart_briefigns()
	self = self._graph;
	self._type.en_49(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_63_Finished()
	self = self._graph;
	self._type.ex_63(self);
	self[91].World_Number = 1;
	self[91]._type.Check_for_loaded_buddy(self[91]);
end;

function export:f_63_Finished_2nd_buddy_removal()
	self = self._graph;
	self._type.ex_63(self);
end;

function export:f_64_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.BSQ_MainObjectiveComplete = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_65_Succeeded()
	self = self._graph;
	self._type.en_64(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_66_Succeeded()
	self = self._graph;
	self._type.en_64(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_67_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.BSQ_MainObjectiveComplete = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_68_Succeeded()
	self = self._graph;
	self._type.en_67(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_69_Succeeded()
	self = self._graph;
	self._type.en_67(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_70_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.BSQ_MainObjectiveComplete = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_71_Succeeded()
	self = self._graph;
	self._type.en_70(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_72_Succeeded()
	self = self._graph;
	self._type.en_70(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_73_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.BSQ_MainObjectiveComplete = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_74_Succeeded()
	self = self._graph;
	self._type.en_73(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_75_Succeeded()
	self = self._graph;
	self._type.en_73(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_76_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.BSQ_MainObjectiveComplete = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_77_Succeeded()
	self = self._graph;
	self._type.en_76(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_78_Succeeded()
	self = self._graph;
	self._type.en_76(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_79_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.BSQ_MainObjectiveComplete = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_80_Succeeded()
	self = self._graph;
	self._type.en_79(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_81_Succeeded()
	self = self._graph;
	self._type.en_79(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_82_Out()
	self = self._graph;
	Globals.MASTER_GameGlobals.BSQ_MainObjectiveComplete = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_83_Succeeded()
	self = self._graph;
	self._type.en_82(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_84_Succeeded()
	self = self._graph;
	self._type.en_82(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_85_Out()
	self = self._graph;
	self.MikesPlace_InsideLocation = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self[109].Seconds = 2;
	self[109]._type.Start(self[109]);
	self[109]._type.Restart(self[109]);
	self._type.en_92(self);
	self[92]._type.Enter_area(self[92]);
end;

function export:f_86_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_85_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_87_Enter()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Mikes Place : Enter area";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_86_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_88_Out()
	self = self._graph;
	self.MikesPlace_InsideLocation = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_92(self);
	self[92]._type.Leave_area(self[92]);
end;

function export:f_89_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_88_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_87_Leave()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Mikes Place : Leave area";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_89_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_91_Buddy_removed__or_none_to_wait_for()
	self = self._graph;
	self[95].World_Number = 1;
	self[95].Primary_Spawnpoint = "2054468973614872514";
	self[95].BufferFirst_Spawnpoint = "2054468981563078598";
	self[95].BufferSecond_Spawnpoint = "2054468981749725128";
	self[95].BufferThird_Spawnpoint = "2054468982538254282";
	self[95]._type.Start_spawning_for_MikesPlace_mode(self[95]);
end;

function export:f_92_Timer_elapsed()
	self = self._graph;
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_93_Out()
	self = self._graph;
	self[40]._type.Reset(self[40]);
end;

function export:f_94_Out()
	self = self._graph;
	self[110].Buddy_Name = "Flora_Guillen";
	self[110].ForEach_BuddyName = self.ForEach_BuddyName;
	self[110].ForeEach_BuddyEntity = self.ForEach_BuddyEntity;
	self[110].ForeEach_BuddyAnim = self.ForEach_BuddyAnim;
	self[110].ForeEach_BuddyBeckon = self.ForEach_BuddyBeckon;
	self[110]._type.Check_if_buddy(self[110]);
	self[111].Buddy_Name = "Josip_Idromeno";
	self[111].ForEach_BuddyName = self.ForEach_BuddyName;
	self[111].ForeEach_BuddyEntity = self.ForEach_BuddyEntity;
	self[111].ForeEach_BuddyAnim = self.ForEach_BuddyAnim;
	self[111].ForeEach_BuddyBeckon = self.ForEach_BuddyBeckon;
	self[111]._type.Check_if_buddy(self[111]);
	self[112].Buddy_Name = "Paul_Ferenc";
	self[112].ForEach_BuddyName = self.ForEach_BuddyName;
	self[112].ForeEach_BuddyEntity = self.ForEach_BuddyEntity;
	self[112].ForeEach_BuddyAnim = self.ForEach_BuddyAnim;
	self[112].ForeEach_BuddyBeckon = self.ForEach_BuddyBeckon;
	self[112]._type.Check_if_buddy(self[112]);
	self[113].Buddy_Name = "Marty_Alencar";
	self[113].ForEach_BuddyName = self.ForEach_BuddyName;
	self[113].ForeEach_BuddyEntity = self.ForEach_BuddyEntity;
	self[113].ForeEach_BuddyAnim = self.ForEach_BuddyAnim;
	self[113].ForeEach_BuddyBeckon = self.ForEach_BuddyBeckon;
	self[113]._type.Check_if_buddy(self[113]);
	self[114].Buddy_Name = "Michele_Dachss";
	self[114].ForEach_BuddyName = self.ForEach_BuddyName;
	self[114].ForeEach_BuddyEntity = self.ForEach_BuddyEntity;
	self[114].ForeEach_BuddyAnim = self.ForEach_BuddyAnim;
	self[114].ForeEach_BuddyBeckon = self.ForEach_BuddyBeckon;
	self[114]._type.Check_if_buddy(self[114]);
	self[115].Buddy_Name = "Warren_Clyde";
	self[115].ForEach_BuddyName = self.ForEach_BuddyName;
	self[115].ForeEach_BuddyEntity = self.ForEach_BuddyEntity;
	self[115].ForeEach_BuddyAnim = self.ForEach_BuddyAnim;
	self[115].ForeEach_BuddyBeckon = self.ForEach_BuddyBeckon;
	self[115]._type.Check_if_buddy(self[115]);
	self[116].Buddy_Name = "Quarbani_Singh";
	self[116].ForEach_BuddyName = self.ForEach_BuddyName;
	self[116].ForeEach_BuddyEntity = self.ForEach_BuddyEntity;
	self[116].ForeEach_BuddyAnim = self.ForEach_BuddyAnim;
	self[116].ForeEach_BuddyBeckon = self.ForEach_BuddyBeckon;
	self[116]._type.Check_if_buddy(self[116]);
end;

function export:f_95_ForEach_spawned_buddy()
	self = self._graph;
	self._type.ex_95(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_94_Out;
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_96_Out()
	self = self._graph;
	self._type.en_92(self);
	self[92]._type.New_buddy_presence(self[92]);
end;

function export:f_97_Out_0()
	self = self._graph;
	self._type.en_96(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
	self._type.en_19(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_98_Out()
	self = self._graph;
	self.MikesPlace_RegenerateBuddies = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_44(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_99_Out()
	self = self._graph;
	self.MikesPlace_BriefingsReady = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_98_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_100_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_99_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_97_Out_1()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.MikesPlace_InsideLocation;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_100_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_101_Out()
	self = self._graph;
	self.MikesPlace_PawnsReady = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_97_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_97_Out_1;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_95_ForeEach_finished()
	self = self._graph;
	self._type.ex_95(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_101_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_102_Out()
	self = self._graph;
	self.MikesPlace_BriefingsReady = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self[117].Door = self.WeaponSafeDoor;
	self[117]._type.SetAsUsable(self[117]);
end;

function export:f_95_None_spawned_for_Story_mode()
	self = self._graph;
	self._type.ex_95(self);
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_102_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.True(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_103_A_is_True()
	self = self._graph;
	self._type.en_125(self);
	self[125]._type.SetAsUnusable(self[125]);
end;

function export:f_104_Out()
	self = self._graph;
	self._type.en_125(self);
	self[125]._type.SetAsUnusable(self[125]);
end;

function export:f_103_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Mikes Place : WARNING, Attempt to cancel Pawnbriefs while they are not all ready";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = self._type.f_104_Out;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_105_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.MikesPlace_BriefingsReady;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_103_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_103_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_106_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.MikesPlace_InsideLocation;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_105_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_106_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Integer = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Float = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")].String = "Mikes Place : No buddy pawns available yet";
	Boxes[PathID("Domino/System/LogToConsole.lua")].Entity = nil;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._graph = self;
	Boxes[PathID("Domino/System/LogToConsole.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/LogToConsole.lua")]._type.In(Boxes[PathID("Domino/System/LogToConsole.lua")]);
end;

function export:f_108_Out()
	self = self._graph;
	self[122].Seconds = 1;
	self[122]._type.Start(self[122]);
end;

function export:f_109_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.MikesPlace_PawnsReady;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_106_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_106_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
	self._type.en_108(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_110_Output_buddy_data()
	self = self._graph;
	self.Entity_FloraGuillen = self[110].Entity_OfBuddy;
	self.Anim_FloraGuillen = self[110].Anim_OfBuddy;
	self.DoBeckon_FloraGuillen = self[110].DoBeckon_OfBuddy;
end;

function export:f_111_Output_buddy_data()
	self = self._graph;
	self.Entity_JosipIdromeno = self[111].Entity_OfBuddy;
	self.Anim_JosipIdromeno = self[111].Anim_OfBuddy;
	self.DoBeckon_JosipIdromeno = self[111].DoBeckon_OfBuddy;
end;

function export:f_112_Output_buddy_data()
	self = self._graph;
	self.Entity_PaulFerenc = self[112].Entity_OfBuddy;
	self.Anim_PaulFerenc = self[112].Anim_OfBuddy;
	self.DoBeckon_PaulFerenc = self[112].DoBeckon_OfBuddy;
end;

function export:f_113_Output_buddy_data()
	self = self._graph;
	self.Entity_MartyAlencar = self[113].Entity_OfBuddy;
	self.Anim_MartyAlencar = self[113].Anim_OfBuddy;
	self.DoBeckon_MartyAlencar = self[113].DoBeckon_OfBuddy;
end;

function export:f_114_Output_buddy_data()
	self = self._graph;
	self.Entity_MicheleDachss = self[114].Entity_OfBuddy;
	self.Anim_MicheleDachss = self[114].Anim_OfBuddy;
	self.DoBeckon_MicheleDachss = self[114].DoBeckon_OfBuddy;
end;

function export:f_115_Output_buddy_data()
	self = self._graph;
	self.Entity_WarrenClyde = self[115].Entity_OfBuddy;
	self.Anim_WarrenClyde = self[115].Anim_OfBuddy;
	self.DoBeckon_WarrenClyde = self[115].DoBeckon_OfBuddy;
end;

function export:f_116_Output_buddy_data()
	self = self._graph;
	self.Entity_QuarbaniSingh = self[116].Entity_OfBuddy;
	self.Anim_QuarbaniSingh = self[116].Anim_OfBuddy;
	self.DoBeckon_QuarbaniSingh = self[116].DoBeckon_OfBuddy;
end;

function export:f_117_Out()
	self = self._graph;
	self._type.en_96(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_119_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/TextToScreen.lua")].Text = "Mike's Place has finished loading... (Door is now UNLOCKED)";
	Boxes[PathID("Domino/System/TextToScreen.lua")].Duration = 6;
	Boxes[PathID("Domino/System/TextToScreen.lua")]._graph = self;
	Boxes[PathID("Domino/System/TextToScreen.lua")].Out = DummyFunction;
	Boxes[PathID("Domino/System/TextToScreen.lua")]._type.In(Boxes[PathID("Domino/System/TextToScreen.lua")]);
end;

function export:f_120_Out()
	self = self._graph;
	self._type.en_108(self);
	Boxes[PathID("Domino/System/SimpleNode.lua")]._type.In(Boxes[PathID("Domino/System/SimpleNode.lua")]);
end;

function export:f_119_A_is_False()
	self = self._graph;
	Boxes[PathID("Domino/System/TextToScreen.lua")].Text = "Mike's Place is still loading... (Door is LOCKED)";
	Boxes[PathID("Domino/System/TextToScreen.lua")].Duration = 0.8;
	Boxes[PathID("Domino/System/TextToScreen.lua")]._graph = self;
	Boxes[PathID("Domino/System/TextToScreen.lua")].Out = self._type.f_120_Out;
	Boxes[PathID("Domino/System/TextToScreen.lua")]._type.In(Boxes[PathID("Domino/System/TextToScreen.lua")]);
end;

function export:f_121_A_is_True()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.MikesPlace_BriefingsReady;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_119_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = self._type.f_119_A_is_False;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_122_TimeElapsed()
	self = self._graph;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A = self.MikesPlace_InsideLocation;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].B = nil;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_True = self._type.f_121_A_is_True;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_is_False = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_and_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_or_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")].A_xor_B = DummyFunction;
	Boxes[PathID("Domino/System/CompareBoolean.lua")]._type.In(Boxes[PathID("Domino/System/CompareBoolean.lua")]);
end;

function export:f_123_Out()
	self = self._graph;
	self.MikesPlace_RegenerateBuddies = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	self._type.en_23(self);
	Boxes[PathID("Domino/System/OutputOrder.lua")]._type.In(Boxes[PathID("Domino/System/OutputOrder.lua")]);
end;

function export:f_124_Out()
	self = self._graph;
	self.MikesPlace_BriefingsReady = Boxes[PathID("Domino/System/SetBoolean.lua")].Target;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_123_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:f_125_Out()
	self = self._graph;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_124_Out;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._type.False(Boxes[PathID("Domino/System/SetBoolean.lua")]);
end;

function export:en_28()
	self[28].Door = self.WeaponSafeDoor;
end;

function export:en_4()
	Boxes[PathID("Domino/System/SetInteger.lua")].Integer = 1;
	Boxes[PathID("Domino/System/SetInteger.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetInteger.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetInteger.lua")].Out = self._type.f_4_Out;
end;

function export:en_6()
	Boxes[PathID("Domino/System/SetInteger.lua")].Integer = 2;
	Boxes[PathID("Domino/System/SetInteger.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetInteger.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetInteger.lua")].Out = self._type.f_6_Out;
end;

function export:en_12()
	Boxes[PathID("Domino/System/SetString.lua")].String = "";
	Boxes[PathID("Domino/System/SetString.lua")].Integer = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Float = nil;
	Boxes[PathID("Domino/System/SetString.lua")].Boolean = nil;
	Boxes[PathID("Domino/System/SetString.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetString.lua")].Out = self._type.f_12_Out;
end;

function export:en_13()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_13_Out;
end;

function export:en_92()
	self[92].World_Number = 1;
	self[92].MikesPlace_PawnsReady = self.MikesPlace_PawnsReady;
end;

function export:en_36()
	self[36].World_Number = 1;
	self[36].BuddyPawn = self.Entity_QuarbaniSingh;
	self[36].StanceAnim = self.Anim_QuarbaniSingh;
	self[36].DoBeckon = self.DoBeckon_QuarbaniSingh;
	self[36].BuddyName = "Quarbani_Singh";
	self[36].BSQA_MissionID = "BSQ08";
	self[36].BSQB_MissionID = "BSQ13";
end;

function export:en_33()
	self[33].World_Number = 1;
	self[33].BuddyPawn = self.Entity_MicheleDachss;
	self[33].StanceAnim = self.Anim_MicheleDachss;
	self[33].DoBeckon = self.DoBeckon_MicheleDachss;
	self[33].BuddyName = "Michele_Dachss";
	self[33].BSQA_MissionID = "BSQ02";
	self[33].BSQB_MissionID = "BSQ11";
end;

function export:en_38()
	self[38].World_Number = 1;
	self[38].BuddyPawn = self.Entity_WarrenClyde;
	self[38].StanceAnim = self.Anim_WarrenClyde;
	self[38].DoBeckon = self.DoBeckon_WarrenClyde;
	self[38].BuddyName = "Warren_Clyde";
	self[38].BSQA_MissionID = "BSQ04";
	self[38].BSQB_MissionID = "BSQ07";
end;

function export:en_34()
	self[34].World_Number = 1;
	self[34].BuddyPawn = self.Entity_FloraGuillen;
	self[34].StanceAnim = self.Anim_FloraGuillen;
	self[34].DoBeckon = self.DoBeckon_FloraGuillen;
	self[34].BuddyName = "Flora_Guillen";
	self[34].BSQA_MissionID = "BSQ03";
	self[34].BSQB_MissionID = "BSQ15";
end;

function export:en_37()
	self[37].World_Number = 1;
	self[37].BuddyPawn = self.Entity_MartyAlencar;
	self[37].StanceAnim = self.Anim_MartyAlencar;
	self[37].DoBeckon = self.DoBeckon_MartyAlencar;
	self[37].BuddyName = "Marty_Alencar";
	self[37].BSQA_MissionID = "BSQ06";
	self[37].BSQB_MissionID = "BSQ09";
end;

function export:en_35()
	self[35].World_Number = 1;
	self[35].BuddyPawn = self.Entity_PaulFerenc;
	self[35].StanceAnim = self.Anim_PaulFerenc;
	self[35].DoBeckon = self.DoBeckon_PaulFerenc;
	self[35].BuddyName = "Paul_Ferenc";
	self[35].BSQA_MissionID = "BSQ05";
	self[35].BSQB_MissionID = "BSQ10";
end;

function export:en_31()
	self[31].World_Number = 1;
	self[31].BuddyPawn = self.Entity_JosipIdromeno;
	self[31].StanceAnim = self.Anim_JosipIdromeno;
	self[31].DoBeckon = self.DoBeckon_JosipIdromeno;
	self[31].BuddyName = "Josip_Idromeno";
	self[31].BSQA_MissionID = "BSQ01";
	self[31].BSQB_MissionID = "BSQ12";
end;

function export:en_19()
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_19_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_19_Out_1;
end;

function export:en_23()
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_23_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_23_Out_1;
end;

function export:en_63()
	self[63].Marty = self.Entity_MartyAlencar;
	self[63].Flora = self.Entity_FloraGuillen;
	self[63].Warren = self.Entity_WarrenClyde;
	self[63].Josip = self.Entity_JosipIdromeno;
	self[63].Paul = self.Entity_PaulFerenc;
	self[63].Quarbani = self.Entity_QuarbaniSingh;
	self[63].Michele = self.Entity_MicheleDachss;
end;

function export:en_63_PrimaryCheck()
	self[63].Marty = self.Entity_MartyAlencar;
	self[63].Flora = self.Entity_FloraGuillen;
	self[63].Warren = self.Entity_WarrenClyde;
	self[63].Josip = self.Entity_JosipIdromeno;
	self[63].Paul = self.Entity_PaulFerenc;
	self[63].Quarbani = self.Entity_QuarbaniSingh;
	self[63].Michele = self.Entity_MicheleDachss;

	-- Prevent despawning library mission (subversion) buddy
	if (GetBuddiesManager():GetPrimaryBuddyName() == "Marty_Alencar") and (Globals.MASTER_GameGlobals.PrimaryMissionActive == 1) then
		self[63].Marty = nil;
	elseif (GetBuddiesManager():GetPrimaryBuddyName() == "Flora_Guillen") and (Globals.MASTER_GameGlobals.PrimaryMissionActive == 1) then
		self[63].Flora = nil;
	elseif (GetBuddiesManager():GetPrimaryBuddyName() == "Warren_Clyde") and (Globals.MASTER_GameGlobals.PrimaryMissionActive == 1) then
		self[63].Warren = nil;
	elseif (GetBuddiesManager():GetPrimaryBuddyName() == "Josip_Idromeno") and (Globals.MASTER_GameGlobals.PrimaryMissionActive == 1) then
		self[63].Josip = nil;
	elseif (GetBuddiesManager():GetPrimaryBuddyName() == "Paul_Ferenc") and (Globals.MASTER_GameGlobals.PrimaryMissionActive == 1) then
		self[63].Paul = nil;
	elseif (GetBuddiesManager():GetPrimaryBuddyName() == "Quarbani_Singh") and (Globals.MASTER_GameGlobals.PrimaryMissionActive == 1) then
		self[63].Quarbani = nil;
	elseif (GetBuddiesManager():GetPrimaryBuddyName() == "Michele_Dachss") and (Globals.MASTER_GameGlobals.PrimaryMissionActive == 1) then
		self[63].Michele = nil;
	end
end;

function export:en_32()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_32_Out;
end;

function export:en_44()
	Boxes[PathID("Domino/System/OutputOrder.lua")]._graph = self;
	Boxes[PathID("Domino/System/OutputOrder.lua")]._DynamicAnchors = {
		Out = 2,
	};
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[0] = self._type.f_44_Out_0;
	Boxes[PathID("Domino/System/OutputOrder.lua")].Out[1] = self._type.f_44_Out_1;
end;

function export:en_49()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_49_Out;
end;

function export:en_64()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_64_Out;
end;

function export:en_67()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_67_Out;
end;

function export:en_70()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_70_Out;
end;

function export:en_73()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_73_Out;
end;

function export:en_76()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_76_Out;
end;

function export:en_79()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_79_Out;
end;

function export:en_82()
	Boxes[PathID("Domino/System/SetBoolean.lua")].Bool = nil;
	Boxes[PathID("Domino/System/SetBoolean.lua")]._graph = self;
	Boxes[PathID("Domino/System/SetBoolean.lua")].Out = self._type.f_82_Out;
end;

function export:en_96()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_96_Out;
end;

function export:en_125()
	self[125].Door = self.WeaponSafeDoor;
end;

function export:en_108()
	Boxes[PathID("Domino/System/SimpleNode.lua")]._graph = self;
	Boxes[PathID("Domino/System/SimpleNode.lua")].Out = self._type.f_108_Out;
end;

function export:ex_31()
	self.GetBriefing_JosipIdromeno = self[31].GetBriefing;
end;

function export:ex_33()
	self.GetBriefing_MicheleDachss = self[33].GetBriefing;
end;

function export:ex_34()
	self.GetBriefing_FloraGuillen = self[34].GetBriefing;
end;

function export:ex_35()
	self.GetBriefing_PaulFerenc = self[35].GetBriefing;
end;

function export:ex_36()
	self.GetBriefing_QuarbaniSingh = self[36].GetBriefing;
end;

function export:ex_37()
	self.GetBriefing_MartyAlencar = self[37].GetBriefing;
end;

function export:ex_38()
	self.GetBriefing_WarrenClyde = self[38].GetBriefing;
end;

function export:ex_63()
	self.Entity_MartyAlencar = self[63].MartyReset;
	self.Entity_FloraGuillen = self[63].FloraReset;
	self.Entity_WarrenClyde = self[63].WarrenReset;
	self.Entity_JosipIdromeno = self[63].JosipReset;
	self.Entity_PaulFerenc = self[63].PaulReset;
	self.Entity_QuarbaniSingh = self[63].QuarbaniReset;
	self.Entity_MicheleDachss = self[63].MicheleReset;
end;

function export:ex_95()
	self.ForEach_BuddyName = self[95].BuddyName;
	self.ForEach_BuddyEntity = self[95].BuddyEntity;
	self.ForEach_BuddyAnim = self[95].BuddyAnim;
	self.ForEach_BuddyBeckon = self[95].DoBeckon;
end;

-- Empty out anchor definitions
_compilerVersion = 3;
